.circleci/config.yml, test/unit/Makefile, test/unit/random_test.c
Part of #184.
Add a basic set of unit tests for random(). Currently, this relies on
ent and performs only the most trivial tests.
While this is not sufficient to exhaustively test the quality of our
implementation, it should be reasonably sufficient to expose the most
trivial bugs that we are likely to encounter.
Signed-off-by: Alexandru Lazar <alazar@startmail.com>
=> WIP: Add basic unit testing for random

.circleci/config.yml
Apparently the 'qemu' package in the new docker image isn't sufficient to pick up qemu-system-x86_64.
=> fix CI failure

boot/Makefile, mkfs/Makefile, src/runtime/memops.c, src/runtime/runtime.h, stage3/Makefile, test/runtime/Makefile, test/unit/Makefile, test/unit/memops_test.c
**Implementation Detail:**
1. Converted src and destination pointer to word alligned
2. and then made word copy
**Performance Measurement:**
I used x86 64-bit ubuntu machine to compare the performance of new code with existing approach and gcc libc memcpy.
new code shows considerable improvement.
I also included inline x86 assembly approach (code is not included in review but its performace is even better than gcc libc memcpy).
Let me know if this can be used. I will include the code in review.
**Performance Analysis Report:**	 
Following input data used in evaluating performance with different approach:
Size selection: 64B, 128B, 256B, 512B, 1K, 2K ... 1M
Combination: alligned with 64 byte address, non-aligned destination,  non-aligned destination and src
Number of Loops: From 16777216 …
=> Optimized memcpy implementation

src/unix/syscall.c, test/runtime/mkdir.c
Before this commit, getcwd() was always returning the default working directory, i.e. the root directory, ignoring any changes to the working directory made via chdir() or fchdir().
The mkdir runtime test suite has been enhanced to test getcwd() as well.
Closes #415.
=> getcwd(2): return actual current working directory

src/unix/syscall.c, src/unix/system_structs.h, src/unix/unix_clock.c
clock_gettime(2): properly handle monotonic clock
The now() function returns the wall clock time, so it will be subject to discontinuities if the system time is changed (when support for changing the system time is actually implemented), and for this reason it should not be used as time source in clock_gettime() in case the requested clock is a monotonic clock. This commit uses uptime() as time source in such cases.
Closes #357.
=> clock_gettime(2): properly handle monotonic clock

src/runtime/text.h, src/unix/syscall.c
open_internal was attempting to lookup a file's tuple by doing
resolve_cstring. However, resolve_cstring is not parsing UTF-8 strings
correctly; it works only on one byte at a time, and while push_character
is UTF-8-aware, it can't properly encode values given one byte at a
time.
It's not unthinkable that we might want to restrict some things to
ASCII-only. So this commit adds an UTF-8 counterpart called
resolve_utf8, and amends open_internal to use it.
Closes #567.
Signed-off-by: Alexandru Lazar <alazar@startmail.com>
=> Make open_internal UTF-8-aware

src/net/netsyscall.c, src/unix/system_structs.h
This is needed by Vert.x (ticket #824).
Closes #853.
=> getsockopt(2): add stub handler for SO_SNDBUF

src/unix/syscall.c, src/unix/unix_internal.h
Set the function for capset/capget to syscall_ignore. So, it always return true.
Signed-off-by: Bui Trung Kien <trungkiena6@gmail.com>
=> Fixes for Lwan

test/e2e/e2e.go, test/runtime/signal.c, test/unit/random_test.c
This addresses recent failures in the mac build. Note that the e2e tests need to consider whether cross-building is being performed for go and rust (local builds with "prebuild" compile step). go is a no brainer; just set "GOOS" "GOARCH" before the build. rustc is a little more involved and may require additional tools (a quick search brings up "rustup" which could do the job with some further investigation). So I added a "nocross" flag to the e2e tests which allows the test to be skipped if not building on Linux. If we ever need to care about testing e2e rust with the macos build, someone can pick this up and figure out how to script a rustup (or whatever) cross build.
@x64k I'm not quite sure why the random test wasn't able to parse the ent output on mac. I verified that the output (for …
=> Fix mac build

mkfs/dump.c, mkfs/mkfs.c, src/runtime/buffer.c, src/runtime/buffer.h, src/runtime/runtime.h, src/runtime/symbol.c, src/runtime/table.c, src/runtime/table.h, src/tfs/tfs.c, src/unix/syscall.c, src/unix/system_structs.h, src/unix/unix_internal.h, src/unix_process/unix_process_runtime.c, src/x86_64/service.c, stage3/stage3.c
This PR addresses a few issues related to crashes resulting from manifests with a large number of files:
- The unix process runtime was using a small (4MB) mapped area for tagged allocations. This was quickly exhausted with large manifests. Ideally these would come from some kind of growable heap, but for now just expand the mapping to 256MB (anonymous pages faulted in on demand).
- #946 - Tagged allocator in stage3 was handing out whole pages which is wasteful. This uses an mcache with the physically-backed, tagged heap as parent.
- cstring() was being used within loop blocks (e.g. table_foreach), inadvertently causing a blown stack from too many calls to __builtin_alloca. This changes the semantics of cstring() to require a temporary buffer which is allocated outside of said loops.
- …
=> fixes for large number of files

src/runtime/table.c, src/runtime/table.h, src/runtime/uniboot.h, src/x86_64/service.c, test/unit/table_test.c
- only perform table validation in table ops if built with TABLE_PARANOIA (but still validate in unit test); otherwise performance is abysmal for large tables
- invalid comparison was preventing resize to TABLE_MAX_BUCKETS
- use 2M pages for stage3 tagged region, allowing increase to 128k table buckets (256 was too deleterious towards performance with large tables)
- add large table stress test (and complete removal validation) to table unit test
=> more table fixes

contgen/contgen.c, src/runtime/closure.h
Add stack_closure() for the many closures which live only within the scope of a function. Going forward, this will greatly help clean up abuses of the "transient" heap as well as allow use of closures in early init (e.g. in page table code before system heaps are established). This is also required for some upcoming page table and stage2 fixes.
=> stack closures

src/runtime/heap/debug_heap.c, src/runtime/runtime.h, src/virtio/virtqueue.c, src/x86_64/clock.c, src/x86_64/page.c, src/x86_64/page.h
map_range had a bug which was preventing the correct determination of 4k / 2M pages on unmap, so just use the newer, cleaner unmap_pages. This employs stack closures in uses of traverse_entries(), enabling use of the unmap functions in early init, prior to heap setup.
=> fix unmap, page.c cleanup

src/runtime/bitmap.c, src/runtime/bitmap.h, src/runtime/heap/heap.h, src/runtime/heap/id.c, src/runtime/range.h, src/unix/unix.c, test/unit/id_heap_test.c
In order to enable more accurate tracking of user address space, the id heap has been enhanced to allow allocation from within a specified region of space. This will allow us to, for instance, use the process virtual32 heap to track all of the lower 32-bit address space. Allocations may then be confined to specific portions of that space (e.g. MAP_32BIT allocations can come out of the top 2gb of this space, the process stack can be allocated from the top of the lower 2gb space under the kernel reserved area, etc. - these are coming in a follow-up PR).
Along the way, some bugs were found in the bitmap code that led to incorrect handling of given start and end points for an allocation. The id heap unit test has been expanded to test the id_heap_alloc_subrange() as well as various alignment …
=> id heap / bitmap enhancements and fixes

src/unix/mmap.c, src/x86_64/page.c, src/x86_64/page.h, test/runtime/mmap.c
This PR externalizes an interface to walk page tables via src/x86_64/page.h:walk_ptes(), and uses
the interface to implement mincore. We also externalize various PTE helper functions in page.h
Also included are minor updates to the mincore portion of the mmap runtime test.
=> PTE traversal update and mincore reimplementation

boot/service32.s
The bios_tty_write call, needed for stage2 console / debug on xen/aws, was failing on pointers past 16-bit space. This trivial fix computes the data segment for the string pointer and installs it after switching to real mode.
=> fix bios_tty_write

src/unix/mmap.c, src/unix/signal.c, src/unix/system_structs.h, src/unix/unix_internal.h, src/x86_64/crt0.s, src/x86_64/frame.h, src/x86_64/interrupt.c, test/runtime/signal.c
- raise SIGSEGV from mmap fault handler
- add ucontext save/restore to signal delivery/return code
- update signal runtime test with SIGSEGV test
=> SIGSEGV support. Includes:

src/unix/signal.c
An unconditional restore_ucontext in rt_sigreturn was causing a trashed thread frame when a ANSI/BSD-style signal handler (non-siginfo) was used. This led to the signal runtime test hanging in one case where the return to the (corrupted) thread frame was triggering an endless succession of page fault / SIGSEGVs. This change makes the restore conditional on the presence of SA_SIGINFO in the associated sigaction.
Incidentally, setup_sigframe should enforce a 16-byte alignment for the stack pointer before pushing the siginfo / ucontext and/or returning to the signal trampoline. It was, on some test setups, leading to an unaligned stack pointer and incorrect execution for e.g. 'movaps %xmm0, 0x50(%rsp)'.
=> only restore ucontext for sigactions with SA_SIGINFO in rt_sigreturn; align stack in setup_sigframe

src/unix/signal.c
This pulls in @briankoco's change from #969:
https://github.com/nanovms/nanos/pull/969#issuecomment-533066602
This obviates the in-kernel trampoline in favor of the user trampoline set in the sigaction's sa_restorer field. Mandatory for x86-64, this support insures that the correct trampoline (in glibc) is used on handler exit, which is necessary for proper gdb backtraces through signal handlers.
=> Support for SA_RESTORER and glibc signal trampoline

src/runtime/runtime.h, src/runtime/symbol.h, src/runtime/table.c, src/runtime/table.h, src/runtime/tuple.h, src/unix_process/unix_process_runtime.c, test/unit/table_test.c
Add table deconstruction and associated unit test. deallocate_tuple is just an alias for deallocate_table.
Resolves #974
=> deallocate_table, deallocate_tuple

src/runtime/status.h, src/xen/xen.c, src/xen/xennet.c
An XS_TRANSACTION_END request may return an XS_ERROR with a value of EAGAIN, indicating that the transaction should be retried. This amends xennet_inform_backend to retry some number of times after receiving EAGAIN.
=> xennet: handle EAGAIN temporary failure when posting transaction to backend

src/runtime/range.h, src/unix/mmap.c, src/x86_64/page.c
bugfix: remap_pages() can overwrite PTEs beyond the range of the target destination address range when it encounters missing PTE entries. This leads to occasional failures in the mmap runtime test, or anything using mremap
=> remap_pages() bugfix

src/unix/signal.c, src/unix/thread.c, src/unix/unix_internal.h
SA_SIGINFO, since we use it in rt_sigreturn
=> bugfix: signal code needs to put si_signo on the stack even without

src/unix/exec.c, stage3/stage3.c
Without arguments specified via '-a', ops will pass a null argument list to nanos in the manifest. None the wiser, nanos will pass along a zero argument count to the program, causing failures wherever a program expects to find the executable name in argv[0], e.g.:
https://github.com/nanovms/ops/issues/113#issuecomment-539482989
This PR will default to using the value of 'program' in the root tuple if 'arguments' is either undefined or null.
We still may wish to update the behavior of ops here; I imagine most users will expect '-a' to specify arguments to the program without needing to begin with the program name. (A separate flag could be used to override the program name should this be absolutely necessary - e.g. for something like busybox where program name dictates behavior.)
=> exec: use program name as default argument

contgen/contgen.c, src/net/netsyscall.c, src/runtime/closure.h, src/runtime/refcount.h, src/runtime/runtime.h, src/unix/blockq.c, src/unix/mmap.c, src/unix/poll.c, src/unix/signal.c, src/unix/thread.c, src/unix/unix.c, src/unix/unix_internal.h
This contains a variety of clean up around unix land to allow us to free up structures on thread exit. Mostly this consists of straightening out refcounts in various structures (facilitated by adding a refcount interface - a small improvement over fetch_and_add) and finishing cleanup for various types of objects (particularly with poll waiting). Note that yet more additions have been made to closures - specifically the ability to embed a closure struct within another struct, which I used for the various refcount completions.
See #456
=> thread exit cleanup

contgen/contgen.c, src/net/netsyscall.c, src/runtime/closure.h, src/unix/blockq.c, src/unix/eventfd.c, src/unix/futex.c, src/unix/mmap.c, src/unix/pipe.c, src/unix/poll.c, src/unix/signal.c, src/unix/socketpair.c, src/unix/syscall.c, src/unix/system_structs.h, src/unix/thread.c, src/unix/unix.c, src/unix/unix_clock.c, src/unix/unix_internal.h
This rounds out conversion of the remaining cases of uninterruptible blocks that should instead be on a blockq, including the poll waiters (epoll_wait, *select, *poll), nanosleep(2) and TCP connect. The only uninterruptible blocking that remains are filesystem I/O and file-backed mmaps - which are uninterruptible by design.
The blockq actions now take a 'timedout' flag to indicate timer expiry so that the blocking actions don't need to unnecessarily store timestamps and manually check for expiry.
nanosleep(2) implementation should now be complete, and signal interruption will cause the remaining time to be stored in *rem.
The socket code will attempt to abort a TCP connection if a signal was received before lwIP reported connection complete. This could use an explicit test.
Some more …
=> convert uninterruptible waits to blockq where possible

Makefile, boot/stage2.c, mkfs/dump.c, src/gdb/gdbstub.c, src/gdb/gdbtcp.c, src/http/http.c, src/http/http.h, src/net/direct.c, src/net/net.h, src/runtime/buffer.h, src/runtime/metadata.h, src/runtime/runtime.h, src/runtime/status.h, src/unix/exec.c, src/unix_process/socket_user.c, src/x86_64/service.c, src/x86_64/x86_64.h, stage3/Makefile, stage3/stage3.c, test/runtime/Makefile, test/runtime/webg.manifest, test/unit/Makefile
This introduces net/direct.c for handling TCP connections within the kernel. http handling code is moved from src/unix_process to src/http and also built into the kernel. As a (temporary) test, stage3.c contains optional telnet and http test drivers (enabled by setting telnet and http flags in manifest, respectively). We can delete these once we've wired up ftrace and other debug services.
A few general changes are also included:
- A "deferqueue" has been added to service.c to allow bottom half code to re-schedule thunks for execution in the following call to process_bhqueue. This is used, for instance, to allow queued data in a direct_conn to spool out to lwIP as space becomes available in the TCP send window. It also becomes possible to approximate a kernel thread by continuously …
=> in-kernel tcp connection / http interface

src/http/http.c, src/http/http.h, src/net/direct.c, src/runtime/buffer.h, stage3/stage3.c
We can use chunked transfer encoding to form http responses that exceed the maximum buffer size and/or are comprised of multiple buffers.
=> http: add chunked transfer encoding

src/net/direct.c, src/unix/ftrace.c, src/x86_64/service.c
ftrace printer semantics change somewhat: A local rbuf index is set to read_idx on rbuf init and incremented with each print. If a printer returns true, indicating more data to print, another chunk response is scheduled in the future via a runloop timer. False indicates that printing of the rbuf has completed (whether destructive or not), upon which point the http response is finished and rbuf and printers are reset.
One issue is that queued, asynchronous processing of output buffers gets traced after issuing of output has completed on the ftrace side - thus adding a lot of noise to subsequent trace gets. This should only be a concern for trace_pipe, and can be ameliorated by adding an optional completion (status_handler) to buffer_handlers and then tying buffer responses together with a …
=> ftrace: send chunked http response

src/net/netsyscall.c, src/unix/blockq.c, src/unix/futex.c, src/unix/syscall.c, src/unix/system_structs.h, src/unix/thread.c, src/unix/unix.c, src/unix/unix_internal.h
These bugs were found while investigating https://github.com/nanovms/ops/issues/403 and #1003.
- getsockopt needed support for SO_ERROR
- missing poll events method for std files
- futex:
- FUTEX_CMP_REQUEUE was incorrectly interpreting val2 as a timeout, and was also waking waiters before re-queuing them to the uaddr2 futex when it should only re-queue (use blockq_transfer_waiters to re-queue)
- on thread exit, don't call futex syscall directly with a wake (causing a soft create); use futex_wake instead - if the futex isn't found, just ignore it
- file syscalls: explicitly check if file operation completed before putting thread to sleep (triggered by a file_read spanning only a file hole in the write runtime test - not related to node)
=> various bug fixes

src/x86_64/clock.c, src/x86_64/x86_64.h
This is somewhere between 100x and 1000x faster than cpuid+rdtsc
Also, by default disable the use of cpuid when invoking rdtsc even when rdtscp is not present. Users can still have the precision benefit of cpuid+rdtsc by invoking rdtsc_precise() if they really want it
=> Detect hypervisor support for rdtscp instruction and use it by default when user invokes rdtsc()

src/runtime/timer.c, src/runtime/timer.h, src/unix/blockq.c, src/x86_64/x86_64.h
- fix clang build (__rdtsc is reserved word)
- blockq_transfer_waiters: update t->blocked_on, re-register any outstanding, unexpired timers
=> minor fixes

Makefile, src/unix/syscall.c, src/unix/thread.c, src/unix/unix_internal.h, test/runtime/Makefile
iov_transfer* functions were blindly casting fdescs as files, causing corruption to socket descriptors when used with readv(2) and writev(2). Normalize them to use fdescs and, instead of trying to pass the file offset to the op and update afterwards, leave it to the file ops (if applicable) by specifying magic (infinity) as the offset parameter to the op.
Also add missing runtime tests to the runtime-tests* targets.
Rename thread boolean file_op_complete (to file_op_is_complete) to avoid confusion with function of same name.
=> fix iov_transfer / readv / writev

src/x86_64/service.c
try_hw_seed was unnecessarily checking for rdseed/rdrand availability on each call. This trivial fix should confine all (costly) uses of cpuid to initialization.
=> cpuid check for rdseed/rdrand on init only

src/runtime/timer.c, src/x86_64/apic.c, src/x86_64/apic.h, src/x86_64/kvm_platform.c, src/x86_64/pvclock.c, src/x86_64/pvclock.h
Profiling has shown significant latency when programming the local APIC timer. Such writing to the APIC registers is trapped, leading to a vm exit and subsequent device emulation within QEMU. This is quite expensive, taking anywhere from 4 to tens of microseconds in traces of webg performance.
KVM has the capability to emulate the TSC-Deadline timer within the host kernel. This is available in qemu whenever kernel-irqchip is set to on or split (default when KVM is enabled). While an APIC register needs to be written once to enable the timer on initialization, interval updates occur through an MSR which is then handled by the kernel irqchip. Avoiding costly device emulation by qemu in userspace, such updates are measured to take ~1.4us with much less variation.
On my machine, a test run …
=> KVM: use TSC-Deadline timer as runloop timer, if available

src/unix/mmap.c, src/unix/syscall.c, src/unix/unix_internal.h
Use of the ATA driver, which poll-waits for data, exposed discrepancies in unix file operations which expected all tfs operations to block. These changes will detect if a completion has taken place before blocking the calling thread, in which case a direct return will take place instead of a thread sleep.
Note that there are still issues with the iovec operations (readv, writev) which will be addressed in a subsequent PR.
=> unix files: handle fs (I/O) operations that complete without blocking

src/net/netsyscall.c, src/unix/blockq.c, src/unix/eventfd.c, src/unix/pipe.c, src/unix/socketpair.c, src/unix/syscall.c, src/unix/unix.c, src/unix/unix_internal.h
The poll-and-wait ATA driver exposed flaws in the way io_completions were being handled in the iovec and sendfile syscalls. Previously, these completions were applied for blocking operations, but internal versions of those completions were called directly after a direct return from an I/O op. It's likely that this logic was never really tested when using the virtio storage devices - which always block on a read or write. Additionally, certain cases were not being handled, such as partial buffer reads/writes in iovec operations and partial writes in sendfile(2). readv, writev and sendfile runtime tests were all failing when testing with the ATA driver.
These routines have been re-written to eliminate the multiple completion paths. They also take advantage of the new-style closures, which …
=> revised iovec (readv, writev) and sendfile implementations

src/unix/mmap.c, src/unix/syscall.c
- stub out flock (just returns 0)
- A file-backed mmap(2) was leading to a buffer allocation equal to the given mmap length, even if the file length itself is much less. This caused an issue in badger whereby a request for a large amount of address space (2gb in this case) was leading to a buffer alloc failure. Going forward, treat the map as two parts: the file-backed portion, sized at the minimum of the file size or given length, and an anonymous portion if the given length is greater than the file size.
Keep in mind that we do not yet support writing to files through a backed mmap, and any program which does this will not see persistence across reboots (or maps, for that matter).
With these changes, the badger test in #829 gives:
```
assigned: 10.0.2.15 …
```
=> some fixes for badger

Makefile, src/net/lwipopts.h, src/net/net.c, src/xen/xennet.c, stage3/Makefile
While evaluating gcloud and lwIP performance, I bumped up the lwIP tag to the latest release and made appropriate adjustments. Also use optimized mem op (memcmp, memcpy, memset) and string operations from runtime rather than lwIP-specific ones.
This will pick up a number of TCP-related bug fixes as described below, including a leak of TCP PCBs. Webg performance is roughly the same as with 2.0.3, however this test may not show speedup due to optimized (word) mem ops.
from lwip/CHANGELOG (mostly the tcp, ip4 and pbuf stuff will affect us - ignore the socket stuff as we don't use their socket implementation):
```
(STABLE-2.1.2):
++ Bugfixes:
2018-11-21: Jens Nielsen
* netbiosns.c: fix expecting too large packet (bug #55069)
2018-11-19: Dirk Ziegelmeier
* smtp.c: fix compiling with strict C …
```
=> update to lwIP 2.1.2

src/unix/syscall.c
For our purposes, and given that we don't have any file metadata that could be deferred on a sync, fdatasync and fsync are equivalent.
Resolves #980
=> fdatasync(2)

src/unix/syscall.c
Some fcntl(2) commands expect arg to be signed. The change to u64 caused a failure in the mac nightly build (arg < 0 check for F_DUPFD_CLOEXEC would always be false).
=> signed arg for fcntl(2)

boot/stage2.c, src/drivers/ata.c, src/net/net.c, src/net/netsyscall.c, src/runtime/clock.h, src/runtime/format.c, src/runtime/random.c, src/runtime/runtime.h, src/runtime/timer.c, src/runtime/timer.h, src/unix/blockq.c, src/unix/ftrace.c, src/unix/futex.c, src/unix/poll.c, src/unix/signal.c, src/unix/system_structs.h, src/unix/unix.c, src/unix/unix_clock.c, src/unix/unix_internal.h, src/unix_process/unix_process_runtime.c, src/x86_64/apic.c, src/x86_64/clock.c, src/x86_64/rtc.c, src/x86_64/rtc.h, src/x86_64/service.c, src/x86_64/x86_64.h, test/runtime/time.c, test/unit/network_test.c
Clocksource and timer facilities now accept a clock ID parameter (cloning posix 1b interval timer types). To start, this allows measurements and timer deadlines based on real (wall clock) time in addition to monotonic time. clock_gettime(2) now honors the clk_id parameter (if supported), and clock_nanosleep(2) is implemented (sans support for CLOCK_PROCESS_CPUTIME_ID).
=> add clock ID parameter to now, timers and blockq; implement clock_nanosleep(2)

src/x86_64/pci.c
trivial fix from @cdosoftei: use PCI_SLOTMAX + 1 for msi_map size
=> use PCI_SLOTMAX + 1 for msi_map size

src/net/net.c, src/runtime/refcount.h, src/runtime/runtime.h, src/runtime/timer.c, src/runtime/timer.h, src/runtime/uniboot.h, src/unix/blockq.c, src/unix/ftrace.c, src/unix/futex.c, src/unix/poll.c, src/unix/signal.c, src/unix/syscall.c, src/unix/system_structs.h, src/unix/thread.c, src/unix/timer.c, src/unix/unix.c, src/unix/unix_clock.c, src/unix/unix_internal.h, src/x86_64/def64.h, src/x86_64/service.c, stage3/Makefile, test/runtime/Makefile, test/runtime/time.c
This PR introduces support for itimer, timerfd and posix timer interfaces, implementing the following system calls:
- alarm
- getitimer
- setitimer
- timer_create
- timer_settime
- timer_gettime
- timer_getoverrun
- timer_delete
- timerfd_create
- timerfd_gettime
- timerfd_settime
In the process of implementing these, a number of improvements have been made to the runtime timer facility as well as signal handling:
timers
- Runtime timers accept an initial interval as well as an optional, periodic interval to better match the unix interfaces.
- Timer callbacks (of type timer_handler) now accept a count of overruns. When a periodic timer expiry is more than one interval behind the current time, the next expiry is advanced past the current time and the number of overruns is computed from the …
=> unix timers

boot/stage2.c, src/x86_64/interrupt.c, src/x86_64/kvm_platform.c, src/x86_64/service.c, src/x86_64/x86_64.h, test/runtime/webg.manifest
If the flag reboot_on_exit is specified in the build manifest, nanos will reboot (using an induced triple fault) on vm_exit (as a result of exit_group(2), an assertion failure, halt or unrecoverable fault) - as opposed to the default qemu exit with code.
Tested on GCE with a webg image which induces halt after a timeout (not included here). The server restarts and continues serving requests as expected.
(CI failure appears to occur in lepton go build:)
```
go get github.com/nanovms/ops/lepton
/go/src/google.golang.org/api/option/option.go:153:14: undefined: grpc.RoundRobin
/go/src/google.golang.org/api/option/option.go:154:42: undefined: grpc.WithBalancer
make[2]: *** [Makefile:29: deps] Error 2
make[2]: Leaving directory '/home/circleci/project/test/go'
make[1]: *** [Makefile:7: all] …
```
=> add optional reboot on exit

src/x86_64/crt0.s, src/x86_64/interrupt.c, src/x86_64/x86_64.h
Not a serious problem: Incorrect GDT and STAR MSR setup was causing the wrong selector to be loaded on sysret. Eliminates corresponding kludge in common_handler.
=> fix GDT entries for sysret

src/runtime/runtime.h, src/runtime/tuple_parser.c, test/unit/parser_test.c
Create a separate value_parser to differentiate between tuple and value parsing. Spurred by a mkfs crash caused by a malformed manifest (an ops issue), this should help catch malformed tuples rather than parse them as buffers. Also includes recycling of closures in combinate() and closure deallocations where possible.
This is kind of an incremental improvement; more hardening and error catching is possible.
=> some tuple parser cleanup

boot/stage2.c, mkfs/dump.c, mkfs/mkfs.c, src/runtime/uniboot.h, src/tfs/tfs.c, src/tfs/tfs.h, src/tfs/tfs_internal.h, src/tfs/tlog.c, src/unix/syscall.c, src/x86_64/interrupt.c, src/x86_64/service.c, src/x86_64/x86_64.h
This change makes the tfs log extensible. Fixed-size log extensions are allocated from fs storage as needed. Tuple encodings can now be arbitrarily large, spanning log extension boundaries where necessary.
This will hopefully allow manifests of any size, given available storage.
Note that tlog is not backward-compatible with older images, and any local copies of mkfs will need to be updated.
=> tfs log extensions

src/runtime/buffer.h, src/runtime/text.h, src/tfs/tfs.c, src/tfs/tfs.h, src/unix/filesystem.c, src/unix/filesystem.h, src/unix/special.c, src/unix/syscall.c, src/unix/system_structs.h, src/unix/unix_internal.h, stage3/Makefile, test/runtime/Makefile, test/runtime/symlink.c, test/runtime/symlink.manifest
A symlink is represented by a tuple with a symbol called "linktarget", which contains the path of the filesystem entry being linked to.
A new runtime test is also added to exercise symlink-related code.
=> Filesystem: add support for symlinks

src/tfs/tfs.c, src/tfs/tfs.h, src/tfs/tfs_internal.h, src/unix/filesystem.c, src/unix/filesystem.h, src/unix/syscall.c, src/unix/system_structs.h
To retrieve filesystem statistics, fs_blocksize() has been moved from tfs_internal.h and declared in tfs.h, and the 2 new functions fs_totalblocks() and fs_freeblocks() have been implemented.
=> syscalls: add statfs and fstatfs

src/unix/syscall.c
If memory allocation fails, it is retried with a smaller size, until it succeeds.
This commit fixes a crash that happens when an application tries to write to a file more than 1 MB of data with a single write() call.
=> file_write(): properly handle memory allocation errors

src/x86_64/pci.c
A change introduced in #1098 was causing nanos to crash if a call to pci_bar_init was made with an offset > PAGESIZE. Assuming that the correct fix is to map starting the first page boundary at or after the offset (as opposed to further padding the map length).
May have triggered (but not be the root cause of) #1099.
=> pci_bar_init: fix mapping when offset exceeds PAGESIZE

src/runtime/runtime.h
This allows to see failed assertion condition when runtime is not initialized yet
=> assert(): Don't use %s to print assertion condition

boot/service32.s, boot/stage1.s, boot/stage2.c, src/x86_64/region.h
- allocate first available (lowest) physical region instead of highest:
VMware ESXi has second high memory region that intersects with the kernel map
- BIOS E820 memory map: type 3 and 4 are ACPI reclaimable memory and
ACPI NVS memory but they were used for IDENTITY and IDENTITY_RESERVED
region types in nanos
- create_region() and BIOS e820: make sure last region (list terminator) has type == 0
VMware has more regions initially so regions created by boot2 spill over boot0 code
- halt early if bios_read_sectors() failed
This allows nanos on VMware ESXi boot to succeed.
ESXi VIOS E820 memory regions are:
=> Fix boot on VMware ESXi

Makefile, src/runtime/tuple.c, src/runtime/tuple.h, src/tfs/tfs.c, src/tfs/tfs.h, src/unix/filesystem.c, src/unix/filesystem.h, src/unix/syscall.c, src/unix/system_structs.h, test/runtime/Makefile, test/runtime/fallocate.c, test/runtime/fallocate.manifest
Supported operations are allocating disk space (with or without keeping the file size) and deallocating disk space. These are the only operations used by MongoDB and MySQL server.
#1101.
=> syscalls: implement fallocate

src/net/netsyscall.c, src/unix/socket.c, src/unix/socket.h
Needed by MongoDB (#579) to configure a socket as non-blocking.
=> Unix domain sockets: add ioctl implementation

src/tfs/tfs.c
An uninitialized field in extent struct was causing data corruption and intermittent crashes on boot.
=> extent uninited field wasn't being initialized

src/unix/special.c, src/unix/syscall.c
This file is a symbolic link containing the pathname of the executed process.
Now that this file is an actual entry in the filesystem, we can remove the hack in readlink() that was used to be able to get the process file path.
Closes #1076.
=> Special files: add /proc/self/exe

Makefile, src/unix/aio.c, src/unix/syscall.c, src/unix/system_structs.h, src/unix/unix.c, src/unix/unix_internal.h, stage3/Makefile, test/runtime/Makefile, test/runtime/aio.c, test/runtime/aio.manifest
Supported operations are pread and pwrite. Canceling an ongoing operation is not supported.
Closes #1102.
=> syscalls: implement asynchronous I/O functions

src/unix/signal.c, src/unix/system_structs.h, test/runtime/signal.c
Commit 47a38f6e03ffc62b931997e1fb73f0f8eed4382c added an implementation of sigaltstack() but didn't acctually link it to the corresponding syscall number. This commit modifies the implementation to properly handle NULL arguments and invalid argument data, and links the sigaltstack() function to the syscall number; in addition, runtime tests to exercise the new code are being added.
Closes #927.
Closes #1131.
=> Signals: implement sigaltstack()

boot/Makefile, boot/stage2.c, mkfs/Makefile, mkfs/dump.c, src/runtime/range.c, src/runtime/range.h, src/runtime/refcount.h, src/runtime/runtime.h, src/runtime/sg.c, src/runtime/sg.h, src/tfs/tfs.c, src/tfs/tfs.h, src/tfs/tfs_internal.h, src/tfs/tlog.c, src/unix/mmap.c, src/unix/syscall.c, src/unix/unix_internal.h, src/unix_process/unix_process_runtime.c, src/x86_64/pagecache.c, src/x86_64/pagecache.h, src/x86_64/service.c, src/x86_64/symtab.c, stage3/Makefile, test/runtime/Makefile, test/unit/Makefile
This PR proposes to merge an implementation of a page cache as well as a scatter-gather list type (sg_list) that can be used to support vectorized I/O operations. To support zero-copy operations, the page cache exposes a scatter-gather (sg) read interface.
In this phase, a page cache is instantiated as a transparent cache proxy for block storage. TFS has been modified to support only an sg read interface to the backing storage. In the case of stage3, this is the page cache used to create the filesystem. In stage2 and dump, the page cache is replaced with a wrapper that interfaces directly to the block device. Write interfaces are left as buffer-based for the time being, and writes to the page cache are currently write-through only.
While these changes will absorb redundant read accesses …
=> page cache implementation and generic support for scatter-gather I/O

src/x86_64/pagecache.c
When contents of a pagecache page are modified by the application, it's usually not necessary to sync the entire page to storage: only the blocks with modified contents need to be synced.
This commit changes the way a page is synced to storage so that unneeded disk writes (which make filesystem writes inefficient, especially small writes) are avoided.
=> Page cache sync to storage: only write blocks with changed data

src/runtime/uniboot.h, src/unix/syscall.c, src/x86_64/kernel.h, src/x86_64/page.c, src/x86_64/pagecache.c, src/x86_64/pagecache.h, src/x86_64/schedule.c, src/x86_64/service.c
Add drain function to pagecache to evict cached pages. The mm_service routine, called from runloop_internal, simply checks if free physical memory dips below a threshold (CACHE_DRAIN_CUTOFF) and calls the pagecache drain with the delta.
Clearly more can be done to address low memory situations (#1130). Perhaps we could chain drain functions for various caches in the system (of varying types - including object caches) and drain according to some priority scheme. And a low memory threshold could be something more intelligent - a proportion of total memory or something determined dynamically. But a fixed threshold is better than not draining the pagecache at all.
There isn't a runtime test to stress the cache or page eviction. To test these changes, I raised CACHE_DRAIN_CUTOFF to various …
=> page eviction and simple mm service routine

src/net/netsyscall.c
When both TX and RX are shut down on a network socket, we ensure that the the lwIP PCB is not referenced anymore by setting `s->info.tcp.lw` to NULL, but we should also set the TCP callback
argument to NULL (which is needed to prevent callbacks from accessing a deallocated socket structure), because that won't be done by socket_close() if `s->info.tcp.lw` is already NULL when a socket is closed.
=> Socket shutdown: set lwIP callback argument to NULL

src/unix/syscall.c
Without this call, the notify set associated to a file descriptor being closed is leaked, and in addition any notify entries registered on the file descriptor fail to be notified of the file closure.
=> file_close(): add call to release_fdesc()

test/runtime/resolv.conf, test/runtime/webg.go, test/runtime/webg.manifest
- Add resolv.conf (nameserver set to 8.8.8.8)
- Fix panic when http.Get() fails
- Ignore SSL certificate security checks
=> Fix webg /req handling

src/unix/exec.c
Loading the program symbol table only adds to startup time (and badly so given the inefficient implementation), so make it conditional on presence of the 'ingest_program_symbols' flag in the manifest.
Also, the ingest was being skipped for dynamic executables (which is why the delay in #1150 wasn't showing up for a native Linux build, as the musl cross build produced a static binary). This moves the optional ingest to just before the interpreter load.
Resolves #1150
=> disable ingesting of program symbols by default

test/e2e/e2e.go
To avoid ruby e2e test build errors with newer versions of gem, conform to updated flags for excluding documentation build.
=> fix e2e ruby prebuild

src/unix/mmap.c, test/runtime/mmap.c
If the file being mmapped is empty, mmap() should not try to allocate a zero-length buffer, because allocate_buffer() returns INVALID_ADDRESS and thus its return value cannot be de-referenced.
This commit fixes the above issue and add a test case that would trigger this bug.
=> mmap(): fix handling of empty files

src/unix/syscall.c, test/runtime/write.c
Any change in the length of an open file done via ftruncate() must be reflected not only in the filesystem but also in the file struct allocated for the open file.
This commit implements the above behavior and adds a test case that would trigger a failure if the above was not implemented.
=> ftruncate(2): update length member of file structure

src/unix/syscall.c
When the resource argument is set to RLIMIT_AS, getrlimit() returns the maximum size of the process virtual memory.
=> getrlimit(): add support for address space resource

src/unix/syscall.c
This argument allows to retrieve the maximum size of a core file.
Limit values are set to zero because core dumps are not supported yet.
=> getrlimit(): add support for RLIMIT_CORE

src/net/netsyscall.c, src/runtime/uniboot.h, src/unix/aio.c, src/unix/exec.c, src/unix/filesystem.c, src/unix/futex.c, src/unix/mmap.c, src/unix/poll.c, src/unix/signal.c, src/unix/socket.c, src/unix/socket.h, src/unix/syscall.c, src/unix/thread.c, src/unix/timer.c, src/unix/unix_clock.c, src/unix/unix_internal.h
Now that there is a clean delineation between user and kernel addresses, we can do trivial range checks to validate that no kernel memory is referenced in a syscall. This adds functions to validate user buffers, including null-terminated constant strings and iovec arrays. A first pass has been made through the syscalls to insert such checks, which typically return -EFAULT on failure.
Also fix mistaken mapping of interpreter ELF in virtual_huge rather than p->virtual.
=> validation of user address arguments in syscalls

src/runtime/buffer.h, src/unix/pipe.c, src/unix/syscall.c, src/unix/system_structs.h, src/unix/unix_internal.h, test/runtime/pipe.c, test/unit/buffer_test.c
These commands allow to set and get the capacity of a pipe.
=> fcntl: add support for F_SETPIPE_SZ and F_SETPIPE_SZ commands

src/runtime/uniboot.h, src/unix/unix.c, src/x86_64/interrupt.c, src/x86_64/kernel.h, src/x86_64/mp.c, src/x86_64/service.c, test/runtime/signal.c
This resolves a problem where an uninitialized TSS stack base was causing a page fault whenever a process triggered an exception other than a page fault. Change the page fault stack, once necessary to allow faulting in pages at interrupt level (!), into one for use with all exceptions, so that if an interrupt handler causes any exception, its stack won't be trashed. All possible vectors are now covered with an IST, obviating the use of the TSS stack switch triggered by protection level change.
In addition, send segv to a process which causes a general protection fault (i.e. as a result of an illegal instruction).
=> fix exception handling for user mode

boot/Makefile, mkfs/Makefile, src/runtime/heap/id.c, src/runtime/range.c, src/runtime/range.h, src/runtime/rbtree.c, src/runtime/rbtree.h, src/runtime/runtime.h, src/tfs/tfs.c, stage3/Makefile, test/runtime/Makefile, test/unit/Makefile, test/unit/range_test.c, test/unit/rbtree_test.c
This introduces a left-leaning red black tree implementation for more efficient rangemap operations. The rbtree type can be used in non-range situations as an alternative to a list, vector or table.
Resolves #1152 and #235
=> red-black tree implementation

src/unix/unix_clock.c, test/runtime/time.c
This clock id reports the amount of CPU time spent executing for the calling thread, in either user or system mode.
This clock id and CLOCK_PROCESS_CPUTIME_ID are now covered by unit tests.
=> clock_gettime(): add support for CLOCK_THREAD_CPUTIME_ID

src/net/net.c, src/net/net.h, src/virtio/virtio.h, src/virtio/virtio_net.c
The maximum MTU on GCE is 1460. For ease of use and to avoid building special images for gce, we'll change the default to 1460 and allow the user to override the value with an "mtu" value in the manifest. This also fixes static IP configuration - which was using values as C strings (!)...
Resolves #1176
=> change default MTU for virtio-net; fix static IP configuration

src/unix/poll.c, test/runtime/epoll.c
If a file descriptor is registered to an epoll instance, when the file is closed the descriptor is unregistered from the epoll instance, while the corresponding epollfd structure remains associated to the epoll instance. If the file descriptor is later re-used (by opening another file) and re-added to the epoll instance, the EPOLL_CTL_ADD operation fails with -EEXIST when the epollfd structure is found in the epoll instance, but the correct behavior is for EPOLL_CTL_ADD not to fail. Fix this issue by checking whether a given epollfd is registered, and only failing if it is actually registered.
A test case that catches this issue has been added to the epoll runtime tests.
=> EPOLL_CTL_ADD: fix handling of unregistered file descriptors

src/unix/thread.c
Any alternate signal stack that may have been assigned to a given thread is part of memory allocated by the user application, and as such it is memory available for the entire process; therefore, it should not be deallocated by the kernel when the thread is destroyed.
=> exit_thread(): do not deallocate alternate signal stack

src/net/lwipopts.h, src/net/net_system_structs.h, src/net/netsyscall.c, src/unix/socket.h, src/unix/system_structs.h, stage3/Makefile
Dual-stack operation (i.e. using an AF_INET6 socket to listen for IPv4 and IPv6 packets) is supported, for both TCP and UDP servers.
Closes #1179.
=> Network stack: add IPv6 support

src/net/netsyscall.c
Setting the state to TCP_SOCK_OPEN when binding a TCP socket makes it impossible to later connect() the socket to another address (calling bind() and then connect() on a given socket is a perfectly valid use case).
This commit fixes the above issue by not changing the socket state in netsock_bind(), and instead checking the binding state via the local_port field of the underlying lwIP structure; the same check is also added for UDP sockets.
=> netsock_bind(): do not set socket state to TCP_SOCK_OPEN

src/unix/poll.c
If a file descriptor on which a select() call is waiting is closed, the EPOLLHUP event flag is set; this flag is included in both POLLFDMASK_READ and POLLFDMASK_WRITE, thus if the select() caller is interested in either read or write events (but not both), either wset or rset may be NULL in the epoll_blocked kernel structure, and as a result select_notify() could dereference a NULL pointer.
Fix the above issue by checking that a given bitmap (rset, wset or eset) is non-NULL before accessing it.
=> select_notify(): check fd sets before setting event flags

src/unix/syscall.c
It is legal to pass to the readv and writev syscalls iovec structures with zero length (which should be simply ignored). When such a structure is found, the corresponding iov_base field should not be checked for validity (it will most likely be a NULL pointer), otherwise spurious EFAULT errors may be returned to userspace.
=> syscalls: validate_iovec(): skip array entries with zero length

src/net/lwipopts.h, src/net/net.c, src/net/netsyscall.c
This is needed by the Erlang runtime system, which when started in "distributed" mode spawns the Erlang process mapper daemon and then communicates with it via the loopback interface. This also prevents a "Failed to find the loopback interface" NetUtil warning from OpenJDK.
The loopback interface is assigned index number 0 in the network interface list, thus the "real" network interface is assigned index number 1 and then named "en1".
In order to receive packets from the loopback interface, netif_poll() must be called by the kernel, and this is achieved via the netsock_poll() thunk, which is put in the runqueue and then invoked by the scheduler.
=> Network interfaces: add loopback interface

src/net/netsyscall.c, src/unix/system_structs.h
The values of these two options are requested by the Erlang runtime system. Changing the option values is currently not implemented.
=> getsockopt(): add support for SO_PRIORITY and SO_LINGER

boot/stage2.c, mkfs/dump.c, mkfs/mkfs.c, src/runtime/runtime.h, src/tfs/tfs.c, src/tfs/tfs.h, src/tfs/tfs_internal.h, src/tfs/tlog.c, src/unix/syscall.c, src/x86_64/kvm_platform.c, src/x86_64/pagecache.c, src/x86_64/pagecache.h, src/x86_64/service.c, stage3/Makefile, test/runtime/write.c, test/runtime/write.manifest, test/runtime/write_contents/hello
This update to the pagecache applies write completions immediately upon posting the write to the page buffer, resulting in improved performance as file writes no longer need to wait for I/O completion to finish. Spurred by scheduling changes needed to implement file-backed page faults in the kernel, this also allows pagecache storage I/O completions to be safely applied outside of the scope of the kernel lock (upcoming PR). Pagecache read/write completions are now queued up to be applied in a service routine that runs on runqueue (which will remain under the kernel lock).
A sync function has been added to the cache to allow flushing of pending writes on fsync(2), fdatasync(2), newly-added sync(2) and syncfs(2), and on system shutdown.
A simple bulk write performance test has been added to …
=> pagecache asynchronous writes

src/unix/syscall.c
We don't need to deal with file ownership.
Closes #1193.
=> Syscalls: stub fchown, fchownat and lchown

src/runtime/buffer.h, src/runtime/vector.h, src/unix/unix.c
File descriptor allocation is triggered by userspace, thus if the allocation fails it should fail gracefully instead of triggering an assertion failure.
This commit fixes the "assertion buffer_set_capacity(b, new_len) == new_len failed in src/runtime/buffer.h: buffer_extend() on line 90; halt" error that happens if the application tries to open more files than the system can handle.
vector_set(), extend_total() and buffer_extend() have been modified in order to return a boolean value indicating whether the operation was successful.
=> allocate_fd(): fail gracefully if descriptor cannot be allocated

src/runtime/text.h, src/unix/filesystem.h, src/unix/syscall.c, test/runtime/mkdir.c
mkdir() and mkdirat() should detect if the supplied path ends with the '/' delimiter, and strip the trailing delimiter if found. The newly defined dirname_from_path() function implements this.
The mkdir suite of runtime tests has been modified so that it would fail if the above was not implemented correctly.
=> mkdir/mkdirat: fix directory creation when path ends with '/'

Makefile, src/runtime/heap/id.c, src/runtime/heap/id.h, test/runtime/fcntl.c
If the count argument passed to id_heap_alloc_gte() is 1, the return value is guaranteed to be the lowest-numbered non-allocated id starting from the min argument.
This is needed to correctly implement the semantics of dup2() and fcntl(F_DUPFD).
Now that the dup runtime test passes, it is being added to the set of CI-enforced tests. The fcntl runtime test has been amended with a new test case that would have failed without this commit.
Closes #1012.
=> id_heap_alloc_gte(): search for non-allocated ids starting from min

src/net/netsyscall.c, src/unix/socket.c, src/unix/socket.h
Every socket-related syscall must validate the supplied file descriptor number by not only checking that it corresponds to an open file descriptor, but also checking the file type and, if the file type is verified to be a socket, checking the socket domain; otherwise, it's unsafe to dereference the netsock pointer derived from the open file descriptor.
In addition, this allows user programs to call functions such as getsockopt() to check whether a given file descriptor is a socket descriptor (all socket-related syscalls must return -ENOTSOCK if called on a non-socket file descriptor).
=> Socket syscalls: properly validate file descriptor number

Makefile, contgen/contgen.c, src/net/netsyscall.c, src/runtime/closure.h, src/runtime/list.h, src/unix/blockq.c, src/unix/eventfd.c, src/unix/io_uring.c, src/unix/mmap.c, src/unix/pipe.c, src/unix/poll.c, src/unix/signal.c, src/unix/socket.c, src/unix/syscall.c, src/unix/syscalls.h, src/unix/system_structs.h, src/unix/timer.c, src/unix/unix.c, src/unix/unix_internal.h, stage3/Makefile, test/runtime/Makefile, test/runtime/io_uring.c, test/runtime/io_uring.manifest
Supported operations are nop, readv, writev, read_fixed, write_fixed, poll_add, poll_remove, timeout, timeout_remove, close, files_update, read, and write.
A new vmap flag, VMAP_FLAG_PREALLOC, is being defined in order to support mapping and unmapping pre-allocated memory regions.
=> syscalls: add io_uring support

src/vmware/pvscsi.c
only deallocate pvscsi_hcb after completion, not after enqueueing to request ring
=> pvscsi: fix double deallocation

src/x86_64/interrupt.c
Terminate frame dump on zero address: this should get rid of the repeating "runloop_internal" output on an assertion failure. Also limit depth of frame dump so we don't overrun the console window on esxi.
=> fix runaway frame dump, limit to 16 levels deep

src/vmware/pvscsi.c
If the VMWare PVSCSI controller can't keep up with the pace of I/O requests coming from the guest, it may send to the guest driver a response with status code SCSI_STATUS_BUSY. This commit handles a response with such status code by retrying the failed I/O request (up to 3 times) instead of invoking the status handler with an error status.
=> PVSCSI: retry I/O request when response status is SCSI_STATUS_BUSY

src/x86_64/apic.c, src/x86_64/apic.h, src/x86_64/hpet.c
The current HPET driver configures the HPET interrupt mapping using the FSB option, without checking whether this option is actually supported. This prevents the HPET from generating timer interrupts in platforms (such as VMWare ESXi) where FSB mapping is not supported.
This PR adds a check for the FSB capability in the HPET timer configuration register, and sets up interrupt mapping based on this
capability: if FSB mapping is not supported, standard mapping (which routes interrupts to the I/O APIC) is set up instead.
Note: QEMU by default reports its HPET peripheral as not supporting FSB mapping, even though this feature is actually supported; for this reason, after this commit, when running on QEMU without KVM the kernel sets up the HPET using standard mapping instead of FSB mapping …
=> x86 HPET: add support for standard (I/O APIC) interrupt mapping

.circleci/config.yml, .gitignore, test/go/go.mod
This fixes the CI failures triggered by the addition of Azure support to ops (the Azure SDK for Go requires Go 1.13 or newer).
A go.mod file is being added to test/go/ because it is needed with Go 1.13 or newer in order for the github.com/nanovms/ops/lepton dependency to be resolved by "go build".
The go.sum file that is created by "go build" is being gitignored.
=> CircleCI: bump golang version in Docker image to Go 1.14

src/unix/mmap.c, test/runtime/mmap.c
This PR fixes a regression introduced in commit 5a4247ea; if an mprotect syscall causes a new memory map range to be allocated at the tail of an existing mapping, its protection flags should be those of the existing mapping, rather than those being set for the memory range passed to mprotect().
The mmap runtime test suite is also being amended with a new set of tests that would have failed without this fix.
=> vmap_update_protections: fix flags for newly allocated ranges

Makefile, src/net/netsyscall.c, src/unix/system_structs.h, test/runtime/Makefile, test/runtime/netsock.c, test/runtime/netsock.manifest
This ioctl command returns the number of bytes available to be read from a socket.
A runtime test suite to exercise this feature (using the loopback interface) is also being added.
Closes #1036.
=> Network socket ioctl: add support for FIONREAD command

src/drivers/ata-pci.c, src/drivers/ata.c, src/drivers/ata.h, src/runtime/buffer.h, src/runtime/status.h, src/runtime/tuple.c, src/runtime/tuple.h, test/unit/buffer_test.c, test/unit/tuple_test.c
This PR changes the ATA PCI driver in order to use the more efficient DMA transfer mode instead of PIO. Since DMA transfers
can only occur on memory buffers whose addresses fit in 32-bit, the driver falls back to using PIO mode in case a given buffer cannot be used for DMA (which may happen if a machine uses more than 4 GB of memory).
The stage2 bootloader continues to use PIO mode, in order to avoid bloating the bootloader with the PCI support code.
Benchmarks on AWS run with the write runtime test show a performance increase of around 350% on a t2.micro instance, and of more than 400% on a t2.large instance:
t2.micro, PIO mode:
bulk write test, size 20480 KB:
write   26.757145929s
fsync   0.006090302s
read   0.026496127s
total   26.789732358s (764 KB/s)
t2.micro, DMA mode:
bulk write …
=>  ATA PCI storage: add support for bus master DMA

src/unix/syscall.c, src/unix/unix_internal.h, test/runtime/io_uring.c
If the file descriptor on which a vector I/O operation is being invoked implements scatter/gather I/O, the kernel now uses this implementation, instead of invoking the linear read/write closures for each element in the I/O vector.
This PR also adds a scatter/gather write implementation for regular files.
Closes #1115.
=> iov_op(): add support for scatter gather I/O operations

.circleci/config.yml, src/hyperv/include/atomic.h, src/x86_64/crt0.s, test/runtime/Makefile, test/runtime/writev.c, test/unit/tuple_test.c
fix various bugs uncovered by mac nightly build:
- hyperv atomics used asm flags constraints (`@CC<cond>`)without checking for support; use alternate versions when `__GCC_ASM_FLAG_OUTPUTS__` is not defined
- missing include path for runtime tests
- use absolute path for NANOS_TARGET_ROOT
- wrong type in writev test caused always-true condition
- incorrect use of buf->length in tuple_test
- unsupported comment syntax in crt0.s
resolves #1227
=> fix mac ci build

src/hyperv/vmbus/vmbus.c, src/hyperv/vmbus/vmbus_chan.c
Fix master build failure under gcc Debian 6.3.0-18+deb9u1 due to strict aliasing violations:
```
CC      /share/src/nanovms/master02/output/stage3/src/hyperv/vmbus/vmbus.o                                                                                                                                                                     
CC      /share/src/nanovms/master02/output/stage3/src/hyperv/vmbus/vmbus_chan.o                                                                                                                                                                
/share/src/nanovms/master02/src/hyperv/vmbus/vmbus_chan.c: In function ‘vmbus_chan_open_br’: …
```
=> fix strict-aliasing warnings

Makefile
lwIP wasn't being pulled in when invoking make run* rules after a fresh clone - add 'image' dependency
=> fix missing dependency for make run* targets

README.md
I updated the README with a couple things I had to figure out. Mainly, that you need to have NANOS_TARGET_ROOT set in order to create the images, but I didn't find that mentioned in the docs.
=> Builddoc fixes

Makefile, src/unix/filesystem.c, src/unix/filesystem.h, src/unix/syscall.c, src/unix/system_structs.h, test/runtime/Makefile, test/runtime/fadvise.c, test/runtime/fadvise.manifest
Added a stub and a test for the fadvise64 syscall used by posix_fadvise, issue #1101 . This stub checks the fd and advice parameters and returns appropriate errors.
=> Added fadvise64 syscall stub and test

Makefile, platform/pc/Makefile, platform/pc/boot/stage2.c, platform/pc/service.c, src/kernel/pagecache.c, src/kernel/pagecache.h, src/kernel/pagecache_internal.h, src/kernel/stage3.c, src/kernel/storage.c, src/runtime/buffer.h, src/runtime/extra_prints.c, src/runtime/runtime.h, src/runtime/storage.h, src/runtime/text.h, src/tfs/tfs.c, src/tfs/tfs.h, src/tfs/tfs_internal.h, src/tfs/tlog.c, src/unix/exec.c, src/unix/filesystem.c, src/unix/filesystem.h, src/unix/special.c, src/unix/syscall.c, src/unix/unix.c, src/unix/unix.h, src/unix/unix_internal.h, src/virtio/virtio_scsi.c, test/runtime/rename.c, tools/dump.c, tools/mkfs.c
Multiple filesystems can now be mounted by specifying a "mounts" entry in the root tuple of the manifest file. This entry is a tuple containing one entry for each mount, with format <uuid>:<mountpoint>, where <uuid> is a volume identifier (which corresponds to the UUID of the filesystem contained in the volume) and <mountpoint> is the path of the directory in which the filesystem is to be mounted (this directory must exist in the root filesystem). Example to mount 2 filesystems (one at /mnt and the other at /mnt2):
mounts:(
2b8750f4-07f2-2584-7dcc-892b3b52bd07:/mnt
f6f1d240-6b80-2f01-3a87-186b64b7caa6:/mnt2
)
The UUID is assigned to a given filesystem when the filesystem is created by the mkfs tool, and its value is displayed in the terminal output by this tool (as well as by the dump …
=> Storage: add support for multiple filesystem mounts

platform/pc/service.c, src/runtime/format.c, src/unix/unix.c, src/unix/unix.h
If the DUMP_MEM_STATS preprocessor define is present, just before shutting down the VM the kernel dumps on the serial terminal a usage summary for the kernel and Unix heaps.
Closes #272.
=> vm_exit(): optionally dump kernel and Unix heap statistics

src/kernel/stage3.c, src/net/netsyscall.c, src/unix/aio.c, src/unix/eventfd.c, src/unix/exec.c, src/unix/filesystem.c, src/unix/io_uring.c, src/unix/mmap.c, src/unix/socket.h, src/unix/syscall.c, src/unix/system_structs.h, src/unix/unix_internal.h, test/runtime/aio.c, test/runtime/fallocate.c, test/runtime/fcntl.c, test/runtime/io_uring.c, test/runtime/mmap.c, test/runtime/mmap.manifest, test/runtime/readv.c, test/runtime/sendfile.c, test/runtime/write.c, test/runtime/write.manifest, test/runtime/writev.c
This PR implements an "exec protection" feature that, if enabled, prevents the kernel from executing any code outside the main program executable and other "trusted" files explicitly marked as executable. This feature is enabled by adding an "exec_protection" symbol to the root tuple in the manifest file; then, any files containing executable code that need to be executed by the application (usually, shared libraries) need to marked in the manifest file with an "exec" symbol. It is not necessary to add the "exec" symbol to the main program, since this is always considered as a "trusted" executable file.
Example of a manifest file with exec protection enabled and with one shared library:
(
children:(
my_app:(contents:(host:bin/my_app)) …
=> Implement protection against arbitrary code execution

src/kernel/kernel.c, src/kernel/kernel.h, src/kernel/schedule.c, src/unix/exec.c, src/unix/signal.c, src/unix/syscall.c, src/unix/thread.c, src/unix/unix.c, src/unix/unix.h, src/unix/unix_internal.h, src/x86_64/frame.h
This branch addresses the leaky unix stuff described in #1254. It cleans up the handling of 'current' in the scheduler and unix code by changing current_thread to a generic thread struct with generic methods (like pause). Additionally, some problematic usage of current has been cleaned up (now that current_thread is invalidated on runloop entry).
=> Refactor pause code in the scheduler

platform/pc/Makefile, platform/pc/service.c, src/drivers/ata-pci.c, src/drivers/ata-pci.h, src/drivers/storage.c, src/drivers/storage.h, src/kernel/xen_platform.h, src/vmware/pvscsi.c, src/xen/public/io/blkif.h, src/xen/public/io/protocols.h, src/xen/xen.c, src/xen/xen_internal.h, src/xen/xenblk.c, src/xen/xennet.c
For AWS instances, multi-volume support is being added by using the Xen paravirtualized block device driver instead of the ATA PCI driver.
For the ESXi platform, the PVSCSI driver has been enhanced to support more than one disk.
=> Multi-volume support for AWS and ESXi

src/kernel/pagecache.c, src/kernel/pagecache.h, src/unix/filesystem.c, src/unix/filesystem.h, src/unix/mmap.c, src/unix/syscall.c, src/unix/unix_internal.h
The new pagecache_node_fetch_pages() function populates the page cache with the supplied byte range from the supplied node. This function is called to implement a read-ahead functionality, both when a user-space read request is received, and when a page fault requiring I/O from disk occurs.
The default read-ahead size is 128 kB (same as Linux). The fadvise64() syscall can be used to change the default read-ahead
behavior following userspace read requests (POSIX_FADV_RANDOM disables read-ahead, POSIX_FADV_SEQUENTIAL doubles the read-ahead size).
Simple benchmark results when read-ahead is used:
- a sequence of file reads with 4KB chunks on a multi-MB file is around 2 times faster
- sequential access to file-backed memory (accessing 1 byte every 4KB) with a multi-MB file is around 2.5 times …
=> File I/O: add read-ahead functionality

src/unix/mmap.c
During my testing for the eviction changes while I was looping the mmap test, I discovered that the mincore portion of the mmap test would fail infrequently. After some debugging I discovered that this happened when mincore was called on an address offset inside a fat page. The code handling the population of the mincore vector data didn't handle that case properly, so this change fixes that.
=> Fixed mincore handling of offsets into fat pages

src/kernel/pagecache.c, src/kernel/pagecache_internal.h
This change addresses issue #1253 by moving evicted pages to a free list when no longer used, but leaving their meta in the node's tree. When the page is accessed again, memory is reallocated. This change also fixes a missing reserve_refcount in map_pages.
=> Refactor pagecache evict

src/net/netsyscall.c, src/unix/aio.c, src/unix/eventfd.c, src/unix/filesystem.c, src/unix/futex.c, src/unix/io_uring.c, src/unix/pipe.c, src/unix/poll.c, src/unix/signal.c, src/unix/socket.c, src/unix/syscall.c, src/unix/system_structs.h, src/unix/thread.c, src/unix/timer.c, src/unix/unix_clock.c, src/unix/unix_internal.h, test/runtime/aio.c, test/runtime/signal.c
When this flag is specified in a signal action, if the signal is raised while the recipient thread is blocked in a restartable syscall, the syscall is restarted internally by the kernel instead of returning -EINTR to userspace.
Restartable syscalls are those that don't have timeout values in their argument list.
Closes #930.
=> sigaction: add support for SA_RESTART flag

src/unix/special.c, src/x86_64/ap.s, src/x86_64/crt0.s, src/x86_64/lock.h, src/x86_64/mp.c, src/x86_64/segment.inc
Since the kernel lives at the top of the 64-bit address space, the GDT address used at runtime does not fit in 32 bits, so a "temporary" GDT is needed in the AP boot page for secondary CPUs to use when switching to 64-bit mode.
Handling of the /sys/devices/system/cpu/online special file has been updated to report the correct number of available CPUs (its
events callback has been changed so that the EPOLLIN flag is always returned, which is the correct behavior for files that do not block when read).
=> Misc fixes in preparation for enabling SMP support

src/kernel/kernel.h, src/unix/thread.c
Ftrace enabled builds on mac would overflow the ftrace call record
with runloop on Xen. This does not happen on Linux builds, but adding
NOTRACE to runloop fixes the problem.
The other change reverts a change from the current_thread cleanup
that was required for dispatch_signals to work when current was
invalidated. Since we aren't doing the invalidation now, the line is
unnecessary, and was breaking ftrace thread switch analysis.
=> Fixed two ftrace problems

src/xen/xennet.c
I found that the xennet driver was sending out corrupted/incomplete
packets in the case where the packet consists of multiple pages.
There were two problems: first, the end flag was incorrectly set for
each tx page. Second, xen wants the length of the first tx descriptor
for the packet to be the length of the entire packet.
=> Fixed xennet driver handling of multipage packets

platform/pc/Makefile, src/hyperv/include/vmbus.h, src/hyperv/netvsc/hv_net_vsc.c, src/hyperv/storvsc/storvsc.c, src/hyperv/utilities/vmbus_ic.c, src/hyperv/vmbus/vmbus.c, src/hyperv/vmbus/vmbus_chan.c, src/hyperv/vmbus/vmbus_chanvar.h, src/kernel/pagecache.c, src/kernel/schedule.c, src/unix/syscall.c, src/virtio/virtio.c, src/virtio/virtio_internal.h, src/virtio/virtio_mmio.c, src/virtio/virtio_mmio.h, src/virtio/virtio_net.c, src/virtio/virtio_pci.c, src/virtio/virtio_pci.h, src/virtio/virtio_scsi.c, src/virtio/virtio_storage.c, src/virtio/virtqueue.c, src/vmware/vmxnet3_net.c, src/x86_64/lock.h, src/x86_64/page.c, src/x86_64/page.h, src/xen/xennet.c
These changes move bhqueue service outside of the locked region in runloop_internal, necessary for storage completions to execute while a syscall continuation, holding the kernel lock, awaits a file-backed page to be faulted in. This divides the various I/O completions around the system between those that queue to bhqueue (storage completions) - which run without the kernel lock held - and ones that queue to runqueue (e.g. net / lwIP processing) and execute with the kernel lock held.
Also:
- spin locks on a non-SMP build are changed from nops to sanity checks
- address a deadlock issue when attempting to deallocate a physical page in pagecache_unmap_page_nodelocked
=> runloop: service the bhqueue before taking kernel lock

test/go/go_test.go
https://github.com/nanovms/ops/pull/637 modified Ops so that it automatically adds NANOS_VERSION and OPS_VERSION environment variables to an image being created. The Go runtime test for environment variables was not prepared to find variables other than those specified when building the image.
This commit changes the runtime test so that it only checks for the existence and correctness of the specified variables, and doesn't fail if other variables are found.
Closes #1295.
=> Go runtime tests: do not fail if unknown env vars are found

src/xen/xenblk.c
I ran across this testing on AWS. The lock was getting reacquired causing an assertion failure. The lock is unnecessary here, as it is already acquired in the grandparent caller.
=> Remove unnecessary lock in xenblk_get_rreq

platform/pc/service.c, src/kernel/storage.c, src/runtime/buffer.h, src/runtime/storage.h, src/runtime/text.h, src/tfs/tfs.c, src/tfs/tfs.h, src/tfs/tfs_internal.h, src/tfs/tlog.c, tools/dump.c, tools/mkfs.c
In volume mount directives included in a manifest file, it is now possible to specify a volume by its filesystem label (alternatively
to using the filesystem UUID). This allows to easily change volumes to be mounted by a VM instance without re-creating the image for the instance.
Example of a mount directive using a label: `mounts:(my_label:/mnt)`.
The mkfs tool has an additional command line option (-l) that allows to specify a label (if not specified, the default label is an emtpy
string), and the dump tool displays the label retrieved from an existing filesystem.
Example to create an empty filesystem with label "my_label": `mkfs -l my_label -e volume.raw`.
=> Volume mounting: add support for volumes identified by a label

platform/pc/service.c, src/kernel/kernel.c, src/kernel/kernel.h, src/kernel/pagecache.c, src/kernel/pagecache.h, src/kernel/pagecache_internal.h, src/kernel/schedule.c, src/unix/mmap.c, src/unix/signal.c, src/unix/syscall.c, src/unix/thread.c, src/virtio/virtqueue.c
- remove sloppy uses of ci->have_kernel_lock on lock acquisition; flag should instead be used for debug assertions
- explicitly release kernel lock on calls to runloop (aside from kernel page fault)
- clear ci->have_kernel_lock before suspending kernel context on page fault, reset on context resume
- allow pagecache I/O completions to be served on either bhqueue or runqueue depending on origin of request
- change vq_interrupt to enqueue to vq->sched_queue instead of bhqueue
- fix invalid dereference of current in syscall_schedule
While stability issues remain when running with SMP (see #1302 for known issues), webg and other tests progress much further now.
=> more smp fixes

Makefile, platform/pc/Makefile, rules.mk, src/runtime/files.mk, test/runtime/Makefile, test/unit/Makefile, tools/Makefile
- fix parallel build breakage on fresh tree caused by redundant tools build
- maintain runtime source files in a single list (from https://github.com/convolvatron/nanos)
=> build fixes

src/xen/xen.c, src/xen/xenblk.c, src/xen/xennet.c
By using the xen event upcall mask we can eliminate the unmask hypercalls
in each interrupt handler, improving performance and latency. This changeset
continues to set the second level mask for spurious interrupts so those will
only interrupt once. My tests with webg and ab show around a 7.5% improvement
in requests per second and request latency for Xen.
=> Use Xen event upcall mask vs individual hypercalls

src/aarch64/machine.h, src/unix/thread.c, src/unix/unix.c, src/unix/unix_internal.h, src/x86_64/machine.h, test/runtime/time.c
Commit 29c970f introduced a regression which caused CPU time for the threads of a process to be accounted twice in the CPU time of the process. This commit removes the utime and stime members from struct process, which are not necessary because the times of the individual threads need to be summed anyway when the process CPU time is requested from userspace.
In addition, calling set_current_thread() directly from run_thread_frame() messes up time accounting, because when thread_enter_user() is called it sees that the provided thread is already the current thread. This is now fixed.
fetch_and_add_64() is now unused and is being removed; the existing fetch_and_add() for x86 is being changed to use the same implementation as fetch_and_add_64(), because, as noted in …
=> CPU time: fix thread and process time accounting, and fix runtime test

src/kernel/pci.c, src/virtio/virtio_pci.c, src/virtio/virtio_pci.h, src/vmware/pvscsi.c, src/vmware/vmxnet3_net.c, src/vmware/vmxnet3_net.h, src/x86_64/pci.h
With this change, the core PCI code allocates a struct pci_dev for each discovered device, and keeps track of whether a driver has
been attached to it; in this way, the probe function is not called more than once for the same device, while allowing a given driver
to control more than one device. This is needed to support multiple storage devices instantiated as separate PCI devices.
Since now each PCI device has an allocated structure in the core code, there is no need for drivers to keep a local struct pci_dev.
=> PCI: add support for a driver to operate more than one device

src/runtime/vector.h
Profiling revealed unusual amounts of time in vector ops doing memcpy.
Since vectors are used as arrays of pointers, it makes more sense to index
as an array of pointers rather than memcpy in and out. Doing so yields a
small performance gain in webg of around 1%. Not a lot, but the patch
is small. This does assume aligned memory access for best performance.
=> Refactor vector get/set to use array indexing

src/config.h, src/kernel/kernel.h, src/kernel/schedule.c, test/runtime/thread_test.c
This change fixes #1314 by increasing the thread_queue length. When enough threads are 
scheduled (as can be in thread_test), the enqueue in schedule_frame was silently failing
causing the thread never to be run again. I have also added an assert for that enqueue
so that it will panic if too many threads are scheduled.
I also cleaned up thread_test so that it can take an argument of the number of threads to test and now
calculates the expected sum instead of using the hard coded values.
=> Fix thread hang

src/kernel/kernel.c, src/kernel/kernel.h, src/kernel/schedule.c, src/unix/syscall.c, src/unix/thread.c, src/x86_64/apic.h, src/x86_64/machine.h, src/x86_64/mp.c
This PR makes some changes to the scheduler in order to improve performance on SMP systems.
The major changes are:
- the introduction of per-CPU thread queues (as opposed to a single global thread queue)
- changes in the scheduler policy for waking up idle CPUs, in order to minimize IPIs
- on a syscall entry, the CPU handling the syscall now waits unconditionally to acquire the kernel lock (instead of calling `kern_try_lock()`), in order to minimize the chance that the CPU goes to sleep and then needs to be woken up again
=> Scheduler: SMP performance improvements

src/net/netsyscall.c
A socket opened as AF_INET6 but with the any address accepts IPv4 and
IPv6 connections (dual-stack) but the address is always stored in IPv6
format. An IPv4-mapped address in a dual-stack configuration
implies using IPv4 for transport. LwIP doesn't convert for UDP, so this
patch will convert the IPv4-mapped address into an IPv4 address before
passing it along to LwIP so that it will use IPv4 for transport.
=> Convert IPv4-mapped IPv6 addresses to IPv4 for LwIP

Makefile, klib/Makefile, klib/klib.h, klib/test.c, platform/pc/Makefile, platform/pc/boot/Makefile, platform/pc/linker_script, platform/pc/service.c, rules.mk, src/kernel/elf64.h, src/kernel/kernel.h, src/kernel/klib.c, src/kernel/klib.h, src/kernel/stage3.c, src/kernel/symtab.c, src/kernel/symtab.h, src/runtime/memops.c, src/runtime/runtime.h, src/runtime/storage.h, src/runtime/table.c, src/unix/exec.c, src/unix/unix.c, src/x86_64/elf64.c, src/x86_64/kernel_machine.h, src/x86_64/klib.lds, test/runtime/Makefile, test/runtime/klibs.c, test/runtime/klibs.manifest, test/runtime/write.manifest
These changes introduce dynamically-loadable library modules ("klibs") into the kernel. Klibs are statically-built, PIE ELF binaries located in either the root or boot filesystems (specified in manifest) and may be loaded (and unloaded) on demand.
The loading process does not perform explicit dynamic linking into the kernel, instead favoring a dlopen-style interface for resolving symbols by name. Symbols exported from the kernel (using the KLIB_EXPORT macro) are resolved in the klib by name using a "get_sym" method passed as an argument to the module init function. An "add_sym" method is used to export symbols from the klib. These are resolved within the kernel using klib_sym().
This interface is designed to allow the loading of optional components, e.g. crypto libraries, without needing …
=> in-kernel loadable module support

platform/pc/service.c, src/unix/signal.c, src/unix/unix_internal.h, src/x86_64/apic.c, src/x86_64/mp.c
This PR contains fixes for two issues I found while making ftrace SMP safe. The first issue was that there was concurrent access to the sigstate lists and pending field that would cause a crash. That just needed a spinlock to protect those fields. I did not protect the mask field because I'm not convinced it's needed, but could use a second opinion. 
The second issue is that on ESXi the APIC ID for additional cpus is incremented by two and not by one, so the cpuinfo array would have holes in it since the APIC ID is used as cpu id. ESXi uses an x2APIC unlike QEMU, which may be the explanation. In any case, I made the two IDs independent: cpu id is now generated in ap_start with the new stack, and a separate array is used to map cpu id to APIC ID. IPIs are called with cpu id which get …
=> Separate APIC id from cpu id and make sigstate SMP safe

platform/pc/linker_script
The GNU ld linker aligns to 16 bytes the address of global struct variables large 16 bytes or more, even if none of the struct members requires this alignment. For this reason, the start address of the klib_symtab linker section must be aligned to 16 bytes, otherwise the address of klib_syms_start may not match the address of the first (16-byte-sized) struct export_sym.
=> Klib symbol table: align linker section start address to 16 bytes

src/x86_64/machine.h
Provide an alternate conditional implementation
of atomic_test_and_*_bit functions for compilers
that don't support asm flag outputs
=> atomic test alternate asm implementations

klib/Makefile
Just a little fix to get 'make clean' working with the new klib stuff.
=> Added klib vendor directories to CLEANDIRS

src/hyperv/vmbus/vmbus_chan.c, src/kernel/kernel.h, src/kernel/pagecache.c, src/net/netsyscall.c, src/unix/mmap.c, src/unix/signal.c, src/unix/syscall.c, src/virtio/virtio_scsi.c, src/vmware/pvscsi.c
The queue type that we use to implement scheduling queues allows for lock-free access between concurrent enqueues and dequeues. However, an enqueue that occurs in interrupt level could potentially hang if an enqueue to the same scheduling queue was interrupted. Thus any non-interrupt-level enqueues that could compete with an interrupt-level enqueue must be placed within a critical section / irq disable.
This isn't likely to be a source of failures at the moment given that most of our kernel processing occurs with interrupts disabled. But, in keeping with the precedent of not assuming that this will always be the case, irq-safe wrappers to the queue methods have been added here, and enqueues to the bhqueue or runqueue that aren't exclusively from within an interrupt handler have been …
=> use irq-safe enqueue when scheduling to bhqueue and runqueue

Makefile
Kernel libraries are placed in the klibs subfolder of the release artifact.
Closes #1339.
=> Makefile: add kernel libraries to releases

.circleci/config.yml
This change adds the klibs to the nightly tarballs.
Closes #1339.
=> Nightly builds: add kernel libraries

klib/Makefile, klib/cloud_azure.c, klib/cloud_init.c, klib/cloud_init.h, platform/pc/Makefile, platform/pc/service.c, src/drivers/dmi.c, src/drivers/dmi.h, src/http/http.c, src/kernel/kernel.h, src/kernel/klib.c, src/runtime/buffer.c, src/runtime/buffer.h, src/runtime/runtime_init.c, src/runtime/tuple.c, test/unit/buffer_test.c
At the first boot of the kernel for a given image, this library detects (by reading the DMI tables) the cloud platform on which the kernel is running, and executes a cloud-specific initialization. The only cloud platform currently supported is Azure.
Closes #1319.
=> Klibs: add cloud_init klib

platform/pc/service.c, src/kernel/vdso.c, src/unix/syscall.c, src/unix/unix.c
This PR fixes syscall setup for SMP by guaranteeing set_syscall_handler is run on the first processor. It also implements the getcpu syscall for userspace programs that want to know which cpu they're running on.
=> Fix syscall setup and implement getcpu syscall

platform/pc/service.c, src/kernel/pagecache.c, src/unix/signal.c
some minor fixes:
- kernel_shutdown* funcs assumed the kernel lock was held. Change to checking if it is held on the local cpu before calling storage_sync and releasing the lock. If it isn't, schedule a thunk on the runqueue to run storage_sync.
- A pagecache write should only add to runqueue completions for pages in reading state, not bhqueue. Also close out merge on alloc failure.
- Improve reporting of unhandled signals with a terminal disposition and add thread logs for signal dispatch.
=> miscellaneous fixes

test/e2e/go/config.json, test/e2e/nginx_1.15.6/config.json, test/e2e/node_v11.5.0/config.json, test/e2e/php_7.3.5/config.json, test/e2e/python_3.6.7/config.json, test/e2e/ruby_2.5.1/config.json, test/e2e/rust/config.json, test/go/go_test.go
This is needed to comply with a change in the Ops repository to support configuration of port ranges.
https://github.com/nanovms/ops/commit/d8f0a5c043d1d964071ba11acca09808bc47eeb8
=> Go and e2e tests: use strings for port configuration

klib/radar.c, platform/pc/Makefile, platform/pc/boot/def32.h, platform/pc/boot/stage2.c, platform/pc/service.c, src/config.h, src/kernel/kvm_platform.c, src/kernel/log.c, src/kernel/log.h, src/kernel/region.h, src/kernel/symtab.c, src/net/lwip.h, src/net/lwipopts.h, src/net/net.c, src/runtime/buffer.c, src/runtime/buffer.h, src/runtime/heap/freelist.c, src/runtime/heap/mcache.c, src/runtime/runtime.h, src/runtime/runtime_init.c, src/runtime/storage.h, src/unix/exec.c, src/unix/unix.c, src/unix_process/unix_process_runtime.c, src/x86_64/hpet.c, src/x86_64/interrupt.c, src/x86_64/mp.c, src/x86_64/page.c, src/x86_64/xapic.c, tools/mkfs.c
Crash reporting to the radar server is enabled when the manifest file contains the RADAR_KEY environment variable.
A "crash" is defined as either a user application fatal error (e.g. anything that causes the application to terminate with a non-zero
exit code), or a kernel fatal error. When any of these happens, before shutting down the VM the kernel dumps on disk a trace of log messages (printed by both the user application and the kernel); at the next boot, the radar klib detects the log dump and sends it to the radar server as a crash report; the value of the "id" field of a crash report is the same as the "boot id" (sent right after each boot), so that a crash can be unequivocally associated to a boot.
The log dump is saved in a section of the disk that is being carved between stage2 …
=> Radar klib: add crash reporting functionality

platform/pc/service.c, src/hyperv/utilities/vmbus_shutdown.c, src/kernel/kernel.h, src/runtime/runtime.h, src/x86_64/acpi.c
If the platform on which the kernel is running has a defined procedure to stop an instance, this procedure should be used not only when the instance is stopped from the cloud platform but also when the program finishes executing (unless the reboot_on_exit
manifest flag is set).
This PR adds a vm_halt global closure that can be set by platform-specific code and is called by vm_exit().
=> vm_exit(): add support for platform-specific VM halt function

klib/radar.c, src/kernel/log.c, src/kernel/log.h
This adds functionality to the radar klib so that it retrieves from the kernel total memory usage every minute, and sends retrieved data to the server every 5 minutes.
Format of POST request data to /machine-stats server endpoint:
`{"bootID":<boot_id>,"memUsed":[<num_bytes1>,<num_bytes2>,<num_bytes3>,<num_bytes4>,<num_bytes5>]}`
=> Klibs_radar: add memory usage metric

src/unix/special.c
Glibc has code that uses the symlinked path from /proc/self/exe and
asserts that the path is absolute, i.e. starts with a slash. This patch
inserts a slash in front of the exe path if not already included.
=> Guarantee /proc/self/exe path is absolute

Makefile, src/unix/futex.c, src/unix/mmap.c, src/unix/syscall.c, src/unix/thread.c, src/unix/unix_internal.h, test/runtime/Makefile, test/runtime/futexrobust.c, test/runtime/futexrobust.manifest
This change implements the get_robust_list and set_robust_list syscalls
as well as adds support for handling locked mutices during thread exit
by marking the mutex and waking any waiters. The test program included
verifies basic robust mutex functionality. See #457 for more information.
=> Add support for robust futex syscalls and handling

Makefile, platform/pc/service.c, src/config.h, src/kernel/kernel.c, src/kernel/kernel.h, src/kernel/pagecache.c, src/kernel/pagecache.h, src/kernel/schedule.c, src/runtime/runtime.h, src/x86_64/flush.c, src/x86_64/lock.h, src/x86_64/machine.h, src/x86_64/page.c, src/x86_64/page.h, test/runtime/Makefile, test/runtime/tlbshootdown.c, test/runtime/tlbshootdown.manifest
This PR implements TLB shootdowns. The page invalidate interface has been modified
so that page invalidates are batched up using a new tracking structure called a
flush_entry. A finite number of flush_entry structs are created at startup so they can be
allocated without going through any heap allocators. The existing calls to page_invalidate
now take a pointer to a flush_entry, which is passed in to the page walkers. When all the
addresses have been added, a call to page_invalidate_sync is made which assigns a
generation number to the flush_entry and adds it to a central linked list. It then fires off
the flush ipi and processes the flush_entry list on the calling cpu. If there are more than
a certain number of addresses to invalidate then a full tlb flush (cr3 reload) is performed.
A …
=> TLB shootdowns

src/tfs/tlog.c, tools/mkfs.c
This PR fixes a couple of issues that are preventing creation of images with a large number of files, where the TFS log exceeds the size of one extension.
=> TFS log fixes

platform/pc/service.c, tools/dump.c
This PR adds a new switch to the dump tool to print out the contents of the klog from a raw disk image. Since
the klog size can be configurable, it searches backwards from the end of the log to find the beginning. It will
not print out any strings in the general klog area without a valid klog header magic, however.
Fixes #1357
=> Add ability to print out klog contents from disk image

platform/pc/boot/stage2.c, platform/pc/service.c, src/kernel/kernel.c, src/kernel/kernel.h, src/kernel/schedule.c, src/kernel/stage3.c, src/runtime/format.c, src/runtime/format.h, src/runtime/runtime_init.c, src/tfs/tfs.c, src/unix/mmap.c, src/unix/signal.c, src/unix/special.c, src/unix/syscall.c, src/unix/thread.c, src/unix/unix.c, src/unix/unix_internal.h, src/x86_64/interrupt.c, src/xen/xennet.c
This changeset adds support for outputting an 'strace -c' like list of syscall counts and times on
vm exit. The syscall tracking and summary output are controlled through a new manifest symbol
called 'syscall_summary'. New print formatting support for alignment, padding, and precision has
been added in order to make printing the report output simpler. The change also adds a list to 
track shutdown completions that are then run in kernel_shutdown. The existing fs sync is now added
to that list at shutdown time so it always runs last, and a merge is used to run the halt completion 
after the shutdown completions have finished.
=> Add syscall count summary

src/unix/syscall.c
Some compilers do not report the extra definition as a warning or error
=> Remove extraneous print_syscall_stats declaration

src/unix/syscall.c, src/unix/unix_internal.h
The symbol was defined in a header without extern which caused an error on certain linkers.
=> Really fix print_syscall_stats multiple definition linker error

platform/pc/service.c, src/kernel/kernel.c, src/kernel/kernel.h, src/kernel/vdso-now.c, src/kernel/vdso.c, src/kernel/vdso.h, src/x86_64/kernel_machine.h, src/x86_64/mp.c
current_cpu() cannot be called from userspace because:
1)  it accesses the GS register, whose contents in user mode are usually different from the contents in kernel mode
2) it is supposed to return a pointer to kernel data (cpuinfo) that is not mapped for userspace access
This commit fixes the VDSO getcpu() implementation by storing the CPU ID in the TSC_AUX MSR, and retrieving it via the RDTSCP instruction.
For future reference, below is a C code snippet that exercises the VDSO getcpu() implementation:
```
extern void *_dl_vdso_vsym(const char *n, void *);
int (*__vdso_getcpu)(unsigned *cpu, unsigned *node, void *tcache) =
_dl_vdso_vsym("__vdso_getcpu", NULL);
unsigned cpu;
__vdso_getcpu(&cpu, NULL, NULL);
```
Closes #1368.
=> VDSO: getcpu(): avoid calling current_cpu()

src/net/netsyscall.c, test/runtime/netsock.c
The second commit fixes handling of socket connections closed by the remote peer (both if a syscall is ongoing when the connection is closed, and if a syscall is invoked after connection closure).
The first commit fixes a memory corruption bug that surfaced when running the runtime test modified by the second commit.
=> Network socket fixes

platform/pc/Makefile, platform/pc/service.c, src/aws/aws.h, src/aws/ena/ena.c, src/aws/ena/ena.h, src/aws/ena/ena_com/ena_com.c, src/aws/ena/ena_com/ena_com.h, src/aws/ena/ena_com/ena_defs/ena_admin_defs.h, src/aws/ena/ena_com/ena_defs/ena_common_defs.h, src/aws/ena/ena_com/ena_defs/ena_eth_io_defs.h, src/aws/ena/ena_com/ena_defs/ena_includes.h, src/aws/ena/ena_com/ena_defs/ena_regs_defs.h, src/aws/ena/ena_com/ena_eth_com.c, src/aws/ena/ena_com/ena_eth_com.h, src/aws/ena/ena_com/ena_plat.h, src/aws/ena/ena_datapath.c, src/aws/ena/ena_datapath.h, src/drivers/nvme.c, src/drivers/nvme.h, src/drivers/storage.c, src/kernel/pci.c, src/x86_64/io.h, src/x86_64/pci.h
This PR adds support for running Nanos on AWS instances based on the Nitro hypervisor. Tested on t3, t3a, c4, c5, c5a, c5d and c5n instances.
Closes #1316, closes #1233.
=> Add support for AWS Nitro instances

src/gdb/gdbstub.c, src/runtime/list.h, src/runtime/runtime.h, src/unix/futex.c, src/unix/signal.c, src/unix/syscall.c, src/unix/thread.c, src/unix/unix.c, src/unix/unix_internal.h
Previously, a process keeps a list of thread pointers in a vector, indexed
by thread id. This means that as each new thread is created and the id
gets incremented, this vector grows unbounded, even if threads are
deleted, which eventually leads to a failed memory allocation to
grow the vector.
This change puts thread pointers in an rbtree instead, with thread id as
the key. While this makes simple iteration over the thread list more
complicated, it still allows the tid to be incremented for new threads,
avoiding problems with tid reuse and old thread references in the user
program while maintaining a fast lookup by id.
=> Convert process threads vector to rbtree

src/net/netsyscall.c
If data has been received from a TCP socket and is buffered in the kernel, the application should be able to read this data even after the remote peer closes the connection (the read() syscall should return 0 only after all buffered data has been read).
The existing code was making read() return 0 unconditionally for a socket whose TCP connection has been closed by the remote peer, even if there is buffered data to be read. This PR fixes the issue.
=> TCP sockets: allow reading from socket after connection closure

src/unix/syscall.c, src/unix/thread.c, src/unix/unix.c, src/unix/unix_internal.h, src/x86_64/page.c
This PR implements a couple of optimizations in an effort to decrease the number of calls to table_find() and kern_pointer_from_pteaddr(), which show up in ftrace logs as taking a significant amount of time when running heavy disk I/O workloads.
=> Miscellaneous optimizations

platform/pc/boot/stage2.c, platform/pc/service.c, src/kernel/backed_heap.c, src/kernel/kernel.h, src/runtime/kernel_heaps.h, src/virtio/virtio_internal.h, src/virtio/virtio_mmio.c, src/virtio/virtio_mmio.h, src/virtio/virtio_net.c, src/virtio/virtio_pci.c, src/virtio/virtio_pci.h, src/virtio/virtio_scsi.c, src/virtio/virtio_storage.c, src/virtio/virtqueue.c
alloc_map() allocates memory from both the virtual and the physical heap, and returns to the caller both the virtual and the physical address; dealloc_unmap() takes as arguments both the virtual and the physical address to deallocate.
These new functions can be used as alternatives to alloc() and dealloc() when the caller wants to use the physical address, and allow avoiding calls to physical_from_virtual() (both when passing a physical address to a device, and when deallocating memory), which show up in ftrace logs as taking a significant amount of time when running heavy I/O workloads.
In addition, the backed heap now implements internal locking, which can be enabled when a heap is created, so that both locking and non-locking versions can be used.
In the virtIO code, vqmsg_push() now …
=> Backed heap: add alloc_map() and dealloc_unmap() functions

src/tfs/tlog.c
When a filesystem being created by mkfs contains a large number of files, the first call to log_write() or log_write_eav() can extend the log tuple staging buffer beyond the size of a log extension. If this happens, log_flush() is called (by log_set_dirty()) when the `dirty` member of struct log is still set to false; as a result, the log is not flushed, and the next calls to log_write() or log_write_eav() return error; this causes filesystem creation to fail.
This PR fixes the issue by setting `dirty` to true at the beginning of log_set_dirty(), so that if log_flush() is called the log is actually flushed.
=> TFS log: fix flushing of tuple staging buffer in mkfs

src/tfs/tlog.c
The first log_ext in the log stores the uuid and label of the fs.
Currently these fields are pushed on the header in log_create, but
this means that when the log_ext is rewritten as in an fs rebuild, these
fields are then missing which are not detected until reboot. This change
moves adding these fields to the header into log_extend_link which makes
sure they are pushed every time, as log_extend_link is always called
on creation as well as when the log needs to be rewritten.
=> Fix missing uuid and label during log_extend_link

src/kernel/schedule.c, src/tfs/tlog.c
There is a race condition where if log_flush starts a compaction and then the system shuts down, 
the log_flush from the sync operation will return immediately and not let the compaction (and
storage i/o) to finish. This change fixes that problem by checking for compaction in log_flush and
adding the completion to the flush_completions vector, which is now also run after compaction
is finished.
There is an additional small fix related to the situation where shutting down is waiting on i/o to complete
and the cpu enters runloop again and would crash because all threads are invalid.
=> Fix log flush compaction blocking

platform/pc/boot/stage1.s
The stage1 code keeps the current count of sectors to load in AX, which
is currently always small and completely stored in the lower byte (AL). The
BIOS extended read sectors 13h AH=42h interrupt should store the return
code in AH. However, some hypervisor BIOS (e.g. Hyper-V) appear to set
the whole word (AX) as return code, clearing the count held in AL, causing
the loading code to return after a single read. This commit moves
the total sector count to BX, which is not used by the BIOS interrupt.
=> Fix counting of sectors to load in stage1 for weird BIOS

platform/pc/boot/stage1.s
For some reason, issuing more than one INT 13H call in stage1 when running on Xen locks up the VM (the BIOS never returns from the second INT 13H call).
This change minimizes the number of INT 13H calls needed to load stage2, by setting the dap.offset field to 0 and adjusting dap.segment to align with the beginning of stage2: in this way, stage1 can issue INT 13H calls with a sector count up to 0x80 even if the destination buffer is not aligned to a multiple of 0x10000, while still satisfying the constraint that the buffer fits in a single segment.
This change allows booting Nanos on AWS t2 instances, on the condition that the stage2 size does not grow beyond 64 kB.
=> stage1: minimize number of INT 13H BIOS calls to load stage2

platform/pc/Makefile, platform/pc/service.c, src/drivers/console.c, src/drivers/console.h, src/drivers/netconsole.c, src/drivers/netconsole.h, src/drivers/vga.c
This change adds a new console driver that outputs console messages
via UDP to a specific IP address and port. It also adds support for
enabling or disabling console drivers via the manifest. The vga and serial
consoles remain enabled by default, while the new net console is
disabled by default. There is also a new console driver function, config,
that is called for each driver once the manifest is available for parsing.
The new manifest option "consoles" takes an array of the names of the
console drivers preceded by '+' or '-' to enable or disable, respectively.
The default IP 10.0.2.2 is for qemu and default port 4444. The user can
use netcat or similar to receive the packets on the host. The destination
can be changed with "netconsole_ip" and "netconsole_port" fields in the
manifest.
=> Add udp network console option

src/net/netsyscall.c
As discussed in #1381, a pbuf_free is required after a pbuf_alloc and udp_send or udp_sendto or else the the pbuf gets leaked. I also verified this with sending enough data to udploop that it would eventually crash nanos without the fix, and likewise does not crash with the fix.
=> Add pbuf_free after udp sends

klib/mbedtls.c, platform/pc/service.c, src/config.h, src/net/lwip.h, src/net/net.c, src/runtime/heap/mcache.c
The mcache previously only allowed allocations up to 2^max_order in size. With this change, allocations of larger sizes are served directly from the mcache parent heap. Such fallback allocations cannot be deallocated with a size parameter of -1ull (which is allowed for compatibility with vendor code that expects a malloc/free allocator interface). Assertions have been added to these malloc-type wrappers to make sure that the 2^max_order limit is not exceeded.
Now that the mcache can serve arbitrarily large allocations, the max_order for general mcaches in the kernel has been lowered from 1MB to 64kB; allocations larger than 64kB occur rarely in the kernel (only a few on program load), and larger objcache sizes lead to significant waste of memory (objcache meta stored within parent page …
=> mcache: serve large allocations from parent heap

klib/Makefile, klib/ntp.c, platform/pc/service.c, src/kernel/kernel.h, src/kernel/klib.c, src/kernel/schedule.c, src/kernel/vdso-now.c, src/kernel/vdso.h, src/net/net.c, src/runtime/clock.h, src/runtime/pqueue.c, src/runtime/pqueue.h, src/runtime/random.c, src/runtime/timer.c, src/runtime/timer.h, src/tfs/tlog.c, src/unix/blockq.c, src/unix/ftrace.c, src/unix/mktime.c, src/unix/syscall.c, src/unix/thread.c, src/unix/unix.c, src/unix/unix_internal.h, src/x86_64/clock.c, src/x86_64/rtc.c, test/unit/pqueue_test.c
This change adds a new klib that periodically retrieves the time from an NTP server and synchronizes the kernel clock.
Clock synchronization is done gradually (by applying calibration parameters set via clock_adjust()) so as not to create any discontinuity in the wall clock time. The CLOCK_ID_MONOTONIC clock is now different from CLOCK_ID_MONOTONIC_RAW, and is calculated by applying calibration values obtained when comparing the local time with the time retrieved via NTP. Since retrieving the monotonic time is now slightly less efficient because of the calibration step, various pieces of code in the kernel have been converted to use CLOCK_ID_MONOTONIC_RAW instead.
When the local time is adjusted via clock_adjust(), the kernel timer queue is re-ordered so that any changes in timer expiry …
=> Kernel clock: add NTP synchronization

klib/radar.c, src/net/lwip.h, src/net/net.c
The /api/v1 prefix is needed to match the current Radar server configuration.
The "privateIP" attribute is a string representation of the IP address assigned to the default network interface.
The "imageName" attribute is sent if a "RADAR_IMAGE_NAME" environment variable is present.
=> Radar: add /api/v1 prefix to server URL endpoints; add imageName and privateIP attributes in JSON messages

platform/pc/boot/longmode.inc, platform/pc/boot/service32.s, platform/pc/service.c, rules.mk, src/x86_64/ap.s
This change fixes several problems related to SMP startup. The long mode
assembly has been unified between the bootstrap and other processors so
a consistent set of flags is set on cr4 and cr0. This fixes UD2 exceptions
happening because XSAVE was enabled only on the APs. Moving the assembly
to a separate file also necessitated a change to the Makefiles so that
include dependencies were used for assembly files. Also, a workaround
was added to initialize the MXCSR register, since HVM did not always do
this properly for SMP which could result in SIMD exceptions.
=> Fix SMP startup-related problems

klib/ntp.c, src/runtime/runtime.h, src/runtime/timer.h
The first commit fixes a bug that showed up when executing runtime tests with NTP enabled.
The second commit changes the NTP klib so that the poll interval is adjusted dynamically between a minimum and a maximum value, based on the measured jitter of offset values between the local time and the NTP time, using an algorithm similar to that of the NTP reference implementation, whose purpose is to maximize clock precision while minimizing network traffic overhead.
The minimum and maximum poll interval values are expressed as bit order of the number of seconds, and are set by default to 6 (i.e. 64 seconds) and 10 (i.e. 1024 seconds) respectively. These values are configurable via the "ntp_poll_min" and "ntp_poll_max" manifest options, respectively, whose allowed values range from 4 (i.e. 16 …
=> NTP: add dynamic adjustment and configurability of poll interval

platform/pc/boot/longmode.inc, src/x86_64/kernel_machine.h, src/x86_64/mp.c
When the kernel ELF file is loaded directly by the hypervisor in long mode, the boot process does not go through stage1 and stage2. Thus, appropriate settings for the CR4 and CR0 registers of the bootstrap processor must be enforced in the kernel code. This change moves initialization of CR4 and CR0 from the PREPARE_LONG_MODE and ENTER_LONG_MODE assembly macros to the cpu_init() function. Now the assembly macros only do what is strictly necessary to enter long mode.
This fixes UD2 exceptions being triggered when running under AWS Firecracker.
=> pc: init_service(): set CR4 and CR0 when booting without stage2

test/go/common.go, test/go/go_test.go, test/go/node_test.go
With https://github.com/nanovms/ops/pull/887, Ops no longer uses the mkfs tool to create image files, and for this reason the lepton.Config struct no longer contains the Mkfs field.
In addition, when creating an image whose program needs to write to the filesystem, a base volume size has to be configured, otherwise there is no free space in the filesystem to create new files.
=> Go tests: remove references to Mkfs and set base volume size

test/go/common.go, test/go/go_test.go, test/go/node_test.go
The lepton package in ops has been refactored into different packages now to accommodate different hypervisors which broke test's common.go file and some go tests. This change updates these files with the new packages.
=> Update test go files for lepton refactoring

platform/pc/linker_script, platform/virt/linker_script
I discovered that the linker seems to discard the .vvar section where __vdso_vdso_dat lives, causing this symbol to point inside the following section, rodata, so that changes made to the vdso_dat object would overwrite strings. I modified the linker_script to advance the location counter by a page to guarantee the space is reserved.
=> Reserve space in linker_script for vdso data

klib/radar.c, src/kernel/init.c, src/kernel/storage.c, src/runtime/extra_prints.c, src/runtime/heap/id.c, src/runtime/storage.h, src/tfs/tfs.c, src/tfs/tfs.h
Disk space usage data are sent to the same server endpoint (/api/v1/machine-stats) as used for memory usage data, and with the same periodicity (i.e. 5 minutes). The JSON string sent to the endpoint now contains an additional "diskUsage" attribute, whose value is an array of JSON objects (one for each disk mounted by the instance); each array element contains 3 attributes:
- "volume": a string that identifies the volume; for the root volume, the string value is "root"; for any additional volumes, the string value is the volume label if present, or the volume UUID if the label is not present
- "used": the number of bytes used by the filesystem (file contents and meta-data) in the volume
- "total": the total number of bytes in the storage space of the volume, i.e. the upper limit for the …
=> Klibs: radar: add sending of disk space utilization metrics 

platform/pc/service.c, platform/virt/service.c, src/drivers/acpi.h, src/kernel/kernel.c, src/kernel/kernel.h, src/x86_64/acpi.c, src/x86_64/apic.c, src/x86_64/apic.h, src/x86_64/interrupt.c, src/x86_64/kernel_machine.h, src/x86_64/mp.c
This PR adds support for finding and mapping in the ACPI tables and then using the MADT to discover APIC information including the number of processors in the system (stored in present_processors) and how they map to LAPIC IDs. Each ACPI table is mapped individually as they may not be laid out in a contiguous fashion. AP startup has also changed to use the information from the MADT so now the APs are started one at a time with a unicast IPI instead of broadcast. There are some other minor fixes such as unmapping the apboot memory (which is at virtual address of 0) after AP startup so that null pointer derefs will page fault properly, updating the deallocate_stack function to take the same pointer as returned by allocate_stack, and fixing one of the wait times in AP startup to match the MP …
=> Discover and map ACPI tables and use MADT for SMP startup

Makefile, platform/pc/Makefile, platform/virt/Makefile, src/aws/ena/ena.c, src/hyperv/netvsc/netvsc.c, src/net/lwip.h, src/net/lwipopts.h, src/net/net.c, src/net/net_system_structs.h, src/net/netsyscall.c, src/runtime/heap/id.c, src/unix/netlink.c, src/unix/socket.h, src/virtio/virtio_net.c, src/vmware/vmxnet3_net.c, src/xen/xennet.c, test/runtime/Makefile, test/runtime/netlink.c, test/runtime/netlink.manifest, test/unit/id_heap_test.c
Netlink sockets allow userspace to retrieve from the kernel the list of network interfaces and IP addresses, and to be notified of events such as network interfaces being added or removed, link status changes, and IP address changes.
Closes #453.
=> Sockets: add netlink support

src/aarch64/interrupt.c, src/kernel/kernel.h, src/kernel/schedule.c, src/unix/syscall.c, src/x86_64/interrupt.c
In SMP, user threads may still be running on cpus other than the one calling
exit_group. A boolean, shutting_down, is used by runloop and interrupt
handlers to know to skip any user thread scheduling steps. This now gets set
in exit_group, followed by a no-op interrupt to send the cpus back into
runloop where they can no longer schedule user threads and will idle while
shutdown completes.
=> Stop and prevent user threads from running on exit 

klib/ntp.c, rules.mk, src/hyperv/vmbus/vmbus_reg.h, src/unix/mmap.c, src/vmware/pvscsi.c, test/runtime/signal.c
Rather than specify -Wno-address-of-packed-member to gcc, use runtime_memcpy to make safe accesses of possibly unaligned data. Remove the packed attribute for structs where 32 and 64-bit fields are already aligned.
Also, specify -Wno-unknown-warning-option to gcc to avoid warnings about possibly truncated string output.
=> fix build under gcc 10

test/go/common.go, test/go/go_test.go, test/go/node_test.go
The "config" package has been renamed to "types" in ops.
=> Go tests: replace ops/config package import with ops/types

src/aarch64/kernel_machine.c, src/kernel/init.c, src/x86_64/kernel_machine.c
If kernel_shutdown() is called from interrupt context, it should exit this context before calling runloop(), otherwise if a shutdown handler needs interrupts to work (e.g. for flushing filesystem data to disk), the handler will never complete because pending interrupts will not be processed.
This change implements interrupt_exit() for both x86_64 and aarch64, and adds a call to interrupt_exit() from kernel_shutdown().
=> kernel_shutdown(): fix stall when called from interrupt context

platform/pc/pci.c, src/drivers/ata.c, src/kernel/kernel.h, src/kernel/pci.h, src/runtime/closure.h, src/virtio/virtio_internal.h, src/virtio/virtio_net.c, src/virtio/virtio_pci.c, src/x86_64/acpi.c, src/x86_64/apic.c, src/x86_64/apic.h, src/x86_64/interrupt.c, src/x86_64/kernel_machine.h
To create a virtual hard disk file (vdi file format) for VirtualBox from a raw image, the following command can be used:
```
vboxmanage convertdd disk.raw disk.vdi
```
When creating a virtual machine from the VirtualBox GUI:
- select "Other" as OS type, and "Other/Unknown (64-bit)" as OS version
- specify at least 256 MB as memory size
- select the vdi file created above as hard disk image
After creating the virtual machine, modify the following settings:
- System -> Acceleration -> Paravirtualization Interface: select "KVM"
- Network -> Adapter 1 -> Advanced -> Adapter Type: select "Paravirtualized Network (virtio-net)"
Tested with VirtualBox version 6.1.18.
Closes #1400.
=> Add support for Oracle VM Virtualbox

src/unix/exec.c, test/runtime/mmap.c
In Linux it is permissible to call mprotect() on an address mapped from a program's ELF sections. In particular, mprotect() can be used to change a code section to be writable.
The .NET runtime, as of version 5.0.102, relies on this feature, and errors out with `Failed to create CoreCLR, HRESULT: 0x80004005` if unable to change the access protections of a mapping (https://github.com/nanovms/ops-examples/issues/47).
This commit changes exec_elf() to allow read, write and exec access to all the program sections loaded from the ELF file, unless the exec_protection manifest flag is present.
A new test case has been added to the mmap test suite, to check that write access cannot be enabled on the code section of a program when the exec_protection manifest option is present.
=> exec_elf(): allow changing access protections for program sections

src/kernel/schedule.c, src/x86_64/page.c
The old code only invalidated pages if the PAGE_PRESENT flag was set in the
PTE, but if the current cpu hasn't processed the tlb shootdown from
another cpu clearing the present flag, the old incorrect translation could
still be in the TLB. This change unconditionally sets invalidate to guarantee
the current cpu does not have any stale entries in the TLB. A second small
change is to move the page_invalidate_flush to the top of runloop to catch
a cpu coming from an interrupt handler that may not have processed a
shootdown yet.
=> Always invalidate pages on pagetable additions

src/tfs/tfs.c, src/tfs/tfs.h, src/unix/syscall.c, test/runtime/write.c
st_blocks contains the number of 512-byte blocks allocated for a file, while st_blocksize contains the "preferred" block size for efficient filesystem I/O.
=> Syscalls: stat(): set st_blocks and st_blksize for regular files

platform/pc/service.c, src/x86_64/clock.c, src/x86_64/hpet.c
This allows the kernel to run on hypervisors that don't expose a known paravirtualization interface and don't implement the HPET.
The HPET is now used only as a last resort, if the calibrated TSC cannot be used.
The "failed to initialize HPET; invalid femtoperiod" error message, which would appear when probing a non-existing HPET, is being removed because it may no longer be a fatal error.
=> x86_64: implement TSC calibration using PIT

src/tfs/tfs.c, src/tfs/tfs_internal.h, src/tfs/tlog.c
Tfs (and tlog) reserve, allocate, and free from the id heap for the sector
map with a few different operations: allocate_u64/deallocate_u64 and
id_heap_set_area, depending on the situation. This can be a problem if
deallocate_u64 is used on a part of the bitmap set by id_heap_set_area
as they might have different alignment requirements. This change adds
a couple new operations for managing the sector heap to go with
filesystem_reserve_storage for allocation and freeing. The free function
uses id_heap_set_area instead of deallocate to note free sectors so
there are no alignment requirements.
=> Unify and abstract tfs sector map operations

src/runtime/heap/mem_debug.c
Some things use the heap pagesize in calculations so a zero pagesize causes a problem. Use the parent's pagesize for wrapper's pagesize.
=> Fix mem_debug pagesize

src/kernel/schedule.c, src/unix/thread.c
The scheduler was setting the cpu state in run_thunk before calling the
thunk, but this can be a problem if something in the thunk causes a state
change (such as a page fault). This change refactors the state assignment
into the thunks themselves. This means that now the cpu state is set to
user right before the frame return, rather than before performing other
operations such as signal handling. Thunks from the bh and run queue
should be kernel state, which is set by the scheduler upon entry, so the
only thunk update required are the two that will run user code.
=> Refactor cpu state assignment locations

src/virtio/virtio_pci.c
The allocation of config resources requires knowing whether or not MSI is
supported in order to initialize with the correct offset.
Fixes nanovms/ops#945
=> Configure MSI before allocating resources in attach_vtpci

platform/pc/Makefile
The rdtscp instruction currently causes a crash running in hvf on mac
even though the host cpu supports it. This disables the instruction as a
workaround. According to https://bugs.launchpad.net/qemu/+bug/1894836 
this is a problem with hvf not being able to deal with the instruction, but
qemu still reports it as available in cpuid.
Fixes #1427
=> Darwin rdtscp workaround

platform/pc/Makefile, platform/pc/boot/def32.h, platform/pc/boot/stage2.c, platform/virt/Makefile, src/aarch64/kernel_machine.h, src/config.h, src/kernel/elf.c, src/kernel/elf64.h, src/kernel/klib.c, src/unix/exec.c, src/x86_64/def64.h
These changes are aimed at lowering the minimum memory requirements to run a Nanos instance. The kernel image file is stripped of debug info (while retaining symbols), reducing the size of the pc kernel image from 7.9M to 1M, or ~87%. Reducing the image size also speeds up the image boot time, as the kernel load in stage2 consumes a significant portion of this time.
Also, the stage2 working heap size has been reduced to 4MB, which is sufficient for loading a boot filesystem of at least 2M in size. With these changes, a webg instance can run in a qemu VM with 128MB of memory. Further optimizations, such as more judicious use of 2M size pages (such as in the mcache), could further lower this minimum requirement.
This also resolves a bug where a section of an ELF file (.strtab in the found …
=> reduce kernel image size and footprint

src/runtime/heap/id.c, test/unit/id_heap_test.c
The id heap now defaults to first-fit allocation. Previously, the id heap
would default to starting the allocation search from the location of a
previous allocation or deallocation. This behavior was leading to excessive
fragmentation of resources, as could be easily demonstrated by making
alternating requests of 2M and 4K-sized pages from the physical heap. After a
4K allocation, a subsequent 2M allocation would start at the next 2M
boundary (to satisfy the id heap alignment property), and the preceding unused
space would not be considered for allocation unless the allocation search
wrapped within the id range or the next_bit was explicitly reset using
id_heap_set_next.
Next-fit behavior may still be induced by the calling code with use of
id_heap_set_next.
=> revert id heap default allocation behavior to first-fit

src/tfs/tlog.c
There is a scenario in which a fileystem rebuild creates a number of new log
extensions and multiple flush_log_extensions calls and a eventually a
log_extend_link which will call flush_log_extension again to close one of the
new log extensions before it has finished its first flush_log_extension
and thus a use-after-free that leads to a crash.
The change bumps the refcount on the extension for a flush_log_extension.
=> Reserve extension during flush_log_extension

src/runtime/extra_prints.c
Simple fix to avoid crashing when passing a null pointer to format_tuple.  I discovered this when I had a manifest with an incorrect program filename and nanos crashed trying to print out the error that the program was not found.
=> Handle null tuple pointer in format_tuple

src/unix/unix.c
Currently the page fault handler calls halt to try to perform an orderly
shutdown and save crash dump information to disk on panic, but this is often
a problem if a bad page fault occurs in certain kernel code paths, such as
the page cache, where spinlocks are held. Since the spinlocks aren't
cleaned up, the shutdown code accessing the pagecache will generate
an assertion failure (with lock debugging) or deadlock. This change
performs an immediate shutdown to prevent a deadlock or assertion
panic loop. However, this precludes saving crash dump information
for page faults.
We would need an alternative, polling, storage driver in order to bypass the
pagecache and work with interrupts off to save the crash dump.
=> Perform immediate shutdown after page fault panics

doc/virtio-balloon.txt, platform/pc/Makefile, platform/pc/pci.c, platform/pc/service.c, platform/virt/Makefile, platform/virt/pci.c, platform/virt/service.c, src/config.h, src/kernel/init.c, src/kernel/kernel.c, src/kernel/kernel.h, src/kernel/pagecache.c, src/kernel/pagecache.h, src/kernel/pci.h, src/kernel/stage3.c, src/runtime/heap/heap.h, src/unix/mmap.c, src/virtio/virtio.c, src/virtio/virtio.h, src/virtio/virtio_balloon.c, src/virtio/virtio_internal.h, src/virtio/virtio_pci.c, src/virtio/virtio_pci.h
This adds a driver for the virtio-balloon device, allowing the monitor to manage the memory footprint of a Nanos instance by inflating and deflating balloon pages. The driver responds to changes applied to the balloon device's PCI config space, which is managed by registration of a handler via a newly-added vtpci_register_config_change_handler interface. An interface has also been added to allow mm_service() to deflate balloon pages when memory resources are at a minimum.
To accommodate config change interrupts for non-MSIX platforms, the non-MSIX vtpci interrupt handler is now registered only once per device and, upon invocation, dispatches queue and config change handlers based on pending bits in the ISR status register.
This driver supports the "statsq," if offered by the device, which …
=> virtio-balloon driver

src/vmware/pvscsi.c
This trivial fix was found through inspection.
=> pvscsi: take queue_lock before enqueueing to hcb_queue

src/x86_64/mp.c, src/x86_64/page.h, src/x86_64/unix_machine.c
This enables write protection while running at CPL 0. Any attempts to write to
a read-only page at kernel level will cause a fault. To comply with this
restriction, map_and_zero() and init_vsyscall() have been updated to first map
read-only pages as writable, initialize the page data and then update the map
flags to remove the writable flag.
=> enable C0_WP in cpu_init

src/kernel/pci.c, src/vmware/pvscsi.c, src/vmware/pvscsi.h
This change restores use of the pvscsi device under qemu. Add "STORAGE=pvscsi" to the make command line to enable the pvscsi device.
=> pvscsi: add support for non-MSI interrupts

src/runtime/heap/heap.h, src/runtime/heap/mem_debug.c, src/runtime/heap/objcache.c, src/unix/mmap.c
This PR adds support for the objcache to the mem debug heap wrapper since the objcache was not
previously compatible with it. The objcache implementation had to change slightly since a pointer to
the objcache is cached in each page, bypassing the wrapper. The footer can now store either the
objcache pointer or the wrapper pointer depending on how the objcache is created.
By applying the debug wrapper to the objcaches in the mcache, I discovered a use-after-free problem
in vmap_remove_intersection where the node match could be deallocated before it gets used for 
unmapping.
Since I had to touch objcache.c, I updated it to spaces only in order to eliminate the mixture of tabs
and spaces. It makes the diff very noisy however, so I suggest viewing that file with leading/trailing whitespace …
=> Add objcache-compatible heap debug

platform/pc/service.c
The PC platform code that handles a VM exit should reference the root_fs global variable (defined in kernel/init.c), which holds a
pointer to the root filesystem, instead of a static variable that is never set.
=> PC platform vm_exit(): fix handling of reboot_on_exit flag

klib/radar.c, src/runtime/symbol.c, src/x86_64/machine.h
The radar klib now checks the server response to crash reports, and retries sending a crash report if the response is not received or does not contain an OK status code.
A retry mechanism is implemented for boot reports as well, so that a boot report is resent if no valid boot ID has been received.
Finally, a retry is triggered if connection to the server fails when sending either a crash or a boot report.
=> Radar: add more robust retry mechanisms

test/e2e/go.mod, test/go/go.mod, test/go/go_test.go
This fixes the overwriting existing files error in go_test.go, updates the go.mod for go_test, and creates a go.mod for e2e which is now required for newer versions of go.
=> Fix go test problems

platform/pc/Makefile, platform/virt/Makefile, src/net/lwip.h, src/net/net.c
This PR makes IPv6 networking fully functional by adding automatic creation of a link-local IPv6 address and servicing the lwIP timers that are needed for proper IPv6 operation.
In addition, manual configuration of a global IPv6 address is now supported, via the "ip6addr" manifest attribute, which takes the
string representation of an IPv6 address, for example: `ip6addr: 1234:2345:3456:4567:5678:6789:7890:890a`
At startup, the kernel now prints on the serial output the IPv6 address(es) being set up, in addition to the IPv4 address. Example output without a global IPv6 address:
```
en1: assigned 10.0.2.15
en1: assigned FE80::5054:FF:FE12:3456
```
In the above output, FE80::5054:FF:FE12:3456 is the link-local IPv6 address created automatically by the kernel.
Example output with a global …
=> Net: add IPv6 address configuration

klib/ntp.c
This got accidentally messed up when fixing some of the compiler warnings around alignment.
=> Fix the setting of origin time in ntp query packet

src/unix/signal.c
According to sigaltstack(2):
"To disable an existing stack, specify ss.ss_flags as SS_DISABLE.  In this case, the kernel ignores any other flags in ss.ss_flags and the remaining fields in ss."
The nanos implementation, however, was calling validate_user_memory on ss->ss_sp regardless of the presence of SS_DISABLE, which was causing an -EFAULT return on valid arguments. With this fix, sigaltstack only validates ss->ss_sp if SS_DISABLE is not set.
=> sigaltstack: do not validate ss->ss_sp if SS_DISABLE is specified

src/unix/blockq.c, src/unix/poll.c
This change removes some unnecessary thread_resume calls in poll.c and
adds a thread_resume with the original thread in blockq_apply_bi_locked.
This is necessary because a call to wake from the blockq in a syscall would
switch current to the waking thread and any references to current in the
original syscall (such as to set the return value) would use the new thread
instead of the old one and thus return the wrong value from a syscall.
=> Resume original thread after running blockq action

klib/ntp.c, src/kernel/clock.c, src/runtime/clock.h, src/runtime/pqueue.c, src/runtime/pqueue.h, src/runtime/timer.c, src/runtime/timer.h
This PR adds the ability for the ntp klib to handle large errors in local vs ntp server time by resetting the 
rtc_offset, normally only set at boot, to an offset from the new time value. A large time reset will also
reset any current in-progress time adjustments. This change does not affect the monotonic time in
any way, so the only adjustments to existing timers is to update any based on the RTC with the difference
between the old and new offsets.  As a side effect of needing to adjust the timers, this also adds a way
to walk through the entries in a pqueue. Since ntp slewing is slow, the default threshold to reset the rtc
is any time difference greater than one minute.
=> Handle large error adjustments in ntp

klib/Makefile, platform/pc/Makefile, platform/pc/boot/Makefile, platform/pc/boot/service32.s, platform/virt/Makefile, rules.mk, test/runtime/Makefile, test/unit/Makefile, tools/Makefile
The stage2 build was previously being built with -O3, which could, on occasion, result in a stage2 image that exceeds 64kB. Sizes larger than 64kB are problematic for Xen-based VMs such as AWS t2 instances (for more detail on this issue, see #1383). Building the stage2 bootloader with -Os results in a much smaller executable (e.g. 46kB vs 64kB - a 27% reduction - on a Debian 9 / gcc 8.3.0 build).
Additionally, a bug is resolved in run64 (where stage2 transitions control to the 64-bit kernel) where %rsi, the second function argument in the ABI calling convention, which is used in init_service to detect parameters on direct loading (e.g. AWS firecracker), was not being zeroed.
=> optimize for space when building stage2 bootloader

platform/pc/Makefile, src/net/net.c
While multiple network interfaces are detected and enabled by Nanos, static and dynamic IP configuration have been limited to the first interface. This adds support for configuration of any interface by moving its configuration into a root-level tuple under the interface name. For example, `en2:(ipaddr:192.168.43.2 netmask:255.255.255.0 gateway:192.168.43.1)` gives static configuration for the second virtio-net interface. Other supported attributes in the interface tuple are 'mtu', used to specify the interface MTU size, and 'default', for selecting an interface as the default egress interface when no route is found.
DHCP is run on detected interfaces that don't have static IP configuration.
To ease transition for ops and existing installations, interface configuration for en1 may still …
=> support static configuration and DHCP on multiple network interfaces

Makefile, platform/pc/Makefile, platform/virt/Makefile, src/net/lwip.h, src/net/lwipopts.h, src/net/net.c
The DHCPv6 client is enabled on a given network interface if no static IPv6 address is provided for that interface in the manifest.
Depends on https://github.com/nanovms/lwip/pull/1, which adds stateful DHCPv6 support to lwIP.
=> Network: add support for DHCPv6

src/net/lwipopts.h
This is needed to correctly handle reassembly of fragmented IPv6 packets in 64-bit platforms. Bug spotted by an assertion failure at lwip/src/core/ipv6/ip6_frag.c:118.
=> lwIP options: define IPV6_FRAG_COPYHEADER

.gdbinit, src/net/netsyscall.c, src/runtime/runtime.h, src/unix/unix.c
This change fixes several things: it points the gdbinit script to the full
symbol image, it updates outdated fields in msg_warn in netsyscall, it
changes the assertion message to a file:line format for better editor
compatibility, and adds virtual address to a message in the fault handler
=> Collection of debug fixes and enhancements

test/e2e/go/config.json, test/e2e/nginx_1.15.6/config.json, test/e2e/node_v11.5.0/config.json, test/e2e/php_7.3.5/config.json, test/e2e/python_3.6.7/config.json, test/e2e/ruby_2.5.1/config.json, test/e2e/rust/config.json
ops now handles mkfs on its own and does not recognize the Mkfs line anymore.
=> Remove unnecessary Mkfs line from e2e test config files

src/kernel/init.c
This change reverts wrapping the root tuple because tfs code will call
destroy on the wrapped tuple and thus the root tuple when switching to
a new log and cleaning up.
=> Temporarily revert wrapping the root tuple

Makefile, src/kernel/pagecache.c, src/kernel/pagecache.h, src/kernel/pagecache_internal.h, src/tfs/tfs.c, src/tfs/tfs_internal.h, src/tfs/tlog.c, test/e2e/nginx_1.15.6/config.json, test/runtime/Makefile, test/runtime/fs_full.c, test/runtime/fs_full.manifest
Nanos currently allocates new tfs extents in the second half of the pagecache write, after the write syscall has already
returned success. If the storage runs out of space, the volume is flagged with a write error and no further writes can
occur, including log writes necessary to free up storage space. This PR separates extent allocation from writing the
extent so that extents are now allocated in the first part of pagecache_write which allows it to return an error to the
write syscall and set ENOSPC which avoids flagging the volume with a write error. This is done by modifying the
pagecache interface to take a reservation function which is used in the first phase. Another side effect of doing 
storage reservations up front is that extents are now allocated to the size of the write, up to …
=> Allocate tfs file and log extents upfront

src/unix/eventfd.c, src/unix/poll.c, src/unix/unix_internal.h
Linux has different definitions for what constitutes an edge with EPOLLET in epoll,
which can vary by file descriptor type. This change allows each file type to implement
an optional handler to determine where edges are, otherwise the original edge tracking
code gets used. This change also implements a handler for eventfd, which has edges
for each read or write of an eventfd file, not just when the counter changes the
read or write ability.
=> Add epoll custom edge trigger handling and customize eventfd handling

src/unix/signal.c
The queued_signal struct may be allocated outside of the kernel lock and
needs to use the locked heap instead of general.
=> Use locked heap for queued_signal structs

src/virtio/virtio_storage.c
The "misaligned buf" error found in https://github.com/nanovms/nanos/issues/1473 results from a klog write of the klog.dump buffer (src/kernel/log.c) tripping an alignment check in virtio_storage.c:storage_rw_internal. This check and its comment seem dubious, however, and such an alignment requirement doesn't seem to be backed up by anything in the virtio spec. (Possibly the 16 byte virtqueue descriptor alignment was mistakenly interpreted as a buffer alignment.) Removing the check allows the write to continue with no apparent errors from qemu.
=> storage_rw_internal: remove gratuitous buffer alignment check

src/kernel/init.c, src/kernel/pagecache.c
Using the locked heap as storage medium for cache pages means that any pages evicted from the cache do not actually release physical memory, because the locked heap uses an underlying mcache, which does not deallocate memory from the parent heap. This PR changes the page cache initialization code to use the backed heap instead of the locked heap, so that evicted pages actually release physical memory.
Other fixes in this PR:
- the `evicted` struct member is now properly initialized when a page is allocated
- the unnecessary incrementing of the page refcount when reading an already allocated page is being removed
- the unnecessary allocation of a page after the end of the range in a write request is being fixed
=> Page cache fixes

src/config.h, src/runtime/format.c
The exception stack is being overflowed in the rprintf() function when executing an exception handler on x86, which means that when an unhandled fault occurs, the register dump and frame and stack traces that are supposed to be printed on the console are often replaced by those associated to this stack overflow, with a generic "frame xxxx already full" message that hides the original fault.
This commit increase the exception stack size from 32 KB to 64 KB, and in addition decreases the stack size requirements of the rprintf() function.
=> x86 exception stack: change size from 32 KB to 64 KB

src/virtio/virtqueue.c
When a new descriptor is added to the set of descriptors of a virtqueue message, the descriptor buffer should be updated so that its end pointer reflects the new buffer length, otherwise if a buffer extension is required the existing descriptors are not copied into the newly extended buffer, which results in random descriptor data being sent to the virtIO device.
=> Virtqueue messages: update buffer end when pushing a descriptor

src/net/netsyscall.c, test/runtime/netsock.c
When a high amount of TCP data is sent to the loopback interface, the TCP transmit window length may become zero, which blocks the transmitting thread. When later the receiving thread reads the incoming data from the interface, the transmit window length becomes non-zero again as a consequence of the receiving thread calling tcp_recved(), but in order for this to be detected by the transmitting thread, the loopback interface needs to be polled.
This PR adds a call to netsock_check_loop() in sock_read_bh_internal(), so that any thread blocked while transmitting to the loopback interfce can be unblocked.
The netsock runtime tests now include a new test that would block indefinitely if the above issue was not addressed.
=> TCP receive: poll loopback interface after calling tcp_recved()

platform/pc/boot/stage2.c, src/boot/uefi.c, src/drivers/ata-pci.c, src/drivers/nvme.c, src/hyperv/storvsc/storvsc.c, src/kernel/init.c, src/kernel/storage.c, src/runtime/runtime.h, src/runtime/storage.h, src/tfs/tfs.c, src/tfs/tfs.h, src/tfs/tfs_internal.h, src/virtio/scsi.h, src/virtio/virtio.c, src/virtio/virtio_internal.h, src/virtio/virtio_mmio.h, src/virtio/virtio_scsi.c, src/virtio/virtio_storage.c, src/vmware/pvscsi.c, src/xen/xenblk.c, tools/dump.c, tools/mkfs.c
This extends the block device interface to add a "flush" method. A flush is issued as a final step in the chain of operations initiated by filesystem_flush, used by the various paths that synchronize storage devices. Flush implementations are included for virtio-storage (which issues a VIRTIO_BLK_T_FLUSH command) and virtio-scsi (which issues a SYNCHRONIZE_CACHE SCSI command) drivers; other storage drivers will require flush implementations to be added later.
As part of the virtio-storage implementation, the VIRTIO_BLK_F_FLUSH and VIRTIO_BLK_F_CONFIG_WCE features are negotiated. A flush method is created and writeback cache mode is set depending on negotiation of respective features. This improves the virtio-storage performance drastically, which now out-performs the virtio-scsi driver in …
=> add flush method to storage interfaces with implementations for virtio_storage and virtio_scsi

src/kernel/init.c, src/kernel/kernel.h, src/runtime/buffer.h, src/unix/syscall.c, src/unix/unix.c, src/unix/unix_internal.h, test/unit/buffer_test.c
A manifest option 'missing_files' has been added that will keep a list of
filenames that are not found by open_internal and then print out the list
when nanos exits. This can be used to help find dynamic libraries or etc
files that need to be included in the filesystem for the application to
run properly. File names only (not path) are added to the list so that if
a file is opened later with a different path it gets removed from the missing
files list. This change also slightly refactors the way shutdown completions
are added as well as adds a couple of new buffer helper functions for fs
path processing.
=> Add option to print out names of files that are not found

src/net/netsyscall.c, test/runtime/netsock.c
This flag acts like the SOCK_NONBLOCK socket-wide option, but applies only to the send/recv syscalls where it is specified.
=> Network send/recv: add support for MSG_DONTWAIT flag

src/net/lwipopts.h
This PR changes a few lwIP configuration options, following the hints at https://www.nongnu.org/lwip/2_1_x/optimization.html.
The lwip_htons() and lwip_htonl() macros have been defined so that byte order inversion operations are executed inline instead of as function calls (in #1299, the lwip_htons() function shows up as taking a non-negligible share of CPU time).
Instead of the default checksum algorithm # 2, algorithm # 3 is now being used, because it is faster on 64-bit platforms (checksum calculation on 20-byte data is around 35% faster).
=> lwIP performance optimization

src/tfs/tfs.c, src/tfs/tfs_internal.h, src/tfs/tlog.c, tools/mkfs.c
Previously, log_write and log_write_eav would fail if the tuple_staging buffer
reached the log extension size. This could be problematic in transient
situations where a log extension flush completion was backlogged or otherwise
delayed. Instead, only return a failure if an unrecoverable log failure
occurred, such as an inability to reserve space for a log extension. To avoid
endless spooling of encoded log tuples, these functions will also fail if the
tuple_staging buffer reaches TFS_LOG_MAX_TUPLE_STAGING_BYTES.
Another issue in tlog was that a log extension failure could forego the
flushing of the existing log extension, leading to loss of data. This fixes
the issue by flushing a current extension regardless of whether an extension
could be allocated.
Additionally, some unnecessary …
=> improve error handling for tfs log; reserve space for log extension in mkfs

Makefile, klib/Makefile, klib/tun.c, src/kernel/init.c, src/kernel/kernel.h, src/kernel/klib.c, src/net/lwip.h, src/net/net.c, src/net/netsyscall.c, src/runtime/queue.c, src/unix/blockq.c, src/unix/filesystem.c, src/unix/filesystem.h, src/unix/socket.h, src/unix/special.c, src/unix/syscall.c, src/unix/system_structs.h, src/unix/unix_internal.h, src/x86_64/kernel_machine.h, src/x86_64/lock.h, test/runtime/Makefile, test/runtime/tun.c, test/runtime/tun.manifest
The tun interface driver is implemented as a klib.
In order to allow adding a new type of special files and implementing blocking I/O on this file, I/O operations on special files have been refactored using custom fdesc closures, instead of relying on the fdesc closures used for regular files.
=> Add tun network interface implementation

src/tfs/tlog.c
Allocating the log_read_ingest_extent closure for each extent found in a given filesystem is not necessary and can lead to a stack
overflow when reading a filesystem with a large number of extents.
This PR moves the closure allocation outside the loop that is executed for each extent, and uses the closure_member() macro inside the loop to update the fsfile closure member.
=> TFS log_read_complete(): avoid multiple stack closure allocations

src/tfs/tfs.c, src/tfs/tfs.h, src/unix/exec.c, src/unix/filesystem.c, src/unix/filesystem.h, src/unix/syscall.c, test/runtime/mkdir.c, test/runtime/mkdir.manifest
The current working directory for an application may now be set by including a
path string under the "cwd" attribute in the program manifest. A test for this
feature is added to the mkdir runtime test. To allow parity testing with
Linux, the mkdir test has also been updated to use a test directory under
/tmp (rather than the root directory) and create files with legitimate
permissions.
Resolves #1498
=> add "cwd" manifest option for setting current working directory

Makefile, klib/Makefile, klib/syslog.c, src/drivers/console.c, src/drivers/console.h, src/kernel/klib.c, src/net/net.c, src/runtime/buffer.h, src/runtime/sg.c, src/tfs/tfs.c, src/unix/filesystem.c, src/unix/filesystem.h, src/unix/syscall.c, test/runtime/Makefile, test/runtime/syslog.c, test/runtime/syslog.manifest
This klib implements a console driver, which can be configured via the manifest to output console messages to a file (with a simple log rotation algorithm) and/or to an UDP syslog server.
The `syslog` manifest tuple is used to configure syslog behavior.
Supported configuration options:
- file: if present, syslog output is written to a file (whose path is indicated by the value of this option)
- file_max_size: file size at which log rotation occurs (default value: 8 MB); its value contains a byte count, optionally followed by a multiplier suffix ('k' or 'K' for KB, 'm' or 'M' for MB, 'g or 'G' for GB)
- file_rotate: number of rotated files to keep in the filesystem (default value: 1); if 0, old logs are deleted instead of being rotated
- server: if present, syslog output is sent to an UDP …
=> Add syslog klib

platform/pc/service.c, src/x86_64/crt0.s, src/x86_64/kernel_machine.c, src/x86_64/kernel_machine.h, src/x86_64/mp.c
This change enables AVX instructions in XCR0 if available, which also requires using
xsave for saving the newly enabled registers in context switches. If xsave is not
available then it will continue to use fxsave instead.
=> Add support for xsave and enable AVX instructions

Makefile, src/unix/socket.c, test/runtime/unixsocket.c
This change fixes a number of bugs in the AF_UNIX family of sockets and in
general brings unix socket behavior more in lin with Linux behavior. The
biggest part of the change fixes the handling of SOCK_DGRAM unix
sockets: the source address is now carried in the sharedbuf struct so
that sendto and recvfrom could be implemented, listen/accept were updated
to not support datagrams, connect was updated to only stash the destination
and return for datagram type, and a SOCK_DGRAM socket can now have
datagrams from multiple other sockets. Other fixes include matching event
notifications to more closely imitate Linux, update some errno returns
to more closely imitate Linux, no overwriting existing flags on accept
and check valid flags on accept, and fix the handling of the connecting
state which …
=> Fix various unix socket bugs and behaviors

platform/virt/service.c, src/kernel/kvm_platform.c
The existing code was failing to set the buffer length, which could cause a `(b->start + offset <= b->length)` assertion failure when printing the string to the console.
=> halt(): fix setting up of string format buffer

src/net/netsyscall.c, src/unix/eventfd.c, src/unix/netlink.c, src/unix/socket.c, src/unix/system_structs.h
This fixes some small event notification related bugs: EPOLLEXCLUSIVE was defined incorrectly. eventfd
edge notifications were fixed so that reads or writes are an edge for both reads and writes. Finally, tcp sockets
weren't reporting EPOLLHUP before listen/connect.
=> Fix miscellaneous event behavior to match Linux

src/net/net_system_structs.h, src/net/netsyscall.c, src/runtime/queue.h, test/runtime/netsock.c
This flag causes a receive operation to return data from the beginning of the receive queue without removing that data from the queue. Thus, a subsequent receive call will return the same data.
A new test case is being added to the netsock runtime test to exercise this feature.
=> Network socket recv(): add support for MSG_PEEK flag

src/virtio/virtio_internal.h, src/virtio/virtio_scsi.c, src/virtio/virtqueue.c
The maximum number of pending virtIO SCSI requests was set to 1 for Google Cloud Platform because otherwise the SCSI device would return an "Overlapped commands attempted" error. This error was caused by the fact that the virtIO SCSI driver was failing to set the command identifier (corresponding to the "task tag" in the SCSI standard) in its requests.
The SCSI standard (SAM-3, section 5.9.3) states that "an overlapped command occurs when a task manager detects the use of a duplicate tag in a command before a task holding that tag completes its task lifetime. A task manager that detects an overlapped command shall abort all tasks for the faulted initiator port in the task set and the device server shall return CHECK CONDITION status for that command. The sense key shall be set to ABORTED …
=> virtIO SCSI: remove maximum queue size setting for GCP

release.sh
The release.sh script now takes an optional command line argument, which if present specifies a command to be executed before publishing the release artifacts.
Currently, the only supported command is `smoke-test`, which triggers execution of smoke tests on different cloud providers (currently, gcp and aws). A smoke test consists of creating a cloud image with the webg program, starting an instance from this image, sending 1000 HTTP requests to this instance, and checking that it responds correctly; if any of these steps fails, the release artifacts are not published. The created instance and image are then deleted as a final cleanup step.
The location of config.json files for Ops can be specified via environment variables:
- OPS_CONF_GCP specifies the location of the config file for gcp …
=> Release script: add optional smoke tests on cloud providers

src/x86_64/flush.c, src/x86_64/interrupt.c, src/x86_64/kernel_machine.c, src/x86_64/mp.c
The Intel software developer's manual (volume 3A, chapter 10 "Advanced Programmable Interrupt Controller", section 10.6.1 "Interrupt Command Register") states that the "Level" field of the ICR must be set to 1 for all IPI delivery modes (except INIT level de-assert).
This commit sets the ICR_ASSERT flag in calls to apic_ipi(), according to the above requirement. This fixes an issue observed on Hyper-V multi-processor instances where the kernel fails to start secondary cores.
=> x86 IPIs: set ASSERT bit in ICR flags

src/x86_64/mp.c
The FXSAVE and FXRSTOR instructions manage both the x87 state and the SSE state; in order to provide equivalent functionality when using XSAVE/XRSTOR, bit 1 of XCR0 must be set to 1, otherwise the SSE state is not managed.
As noted in the Intel Architecture SDM (volume 1, chapter 13 "Managing state using the xsave feature set", section 13.2 "Enabling the xsave feature set and xsave-enabled features"), every processor that supports the XSAVE feature set allows software to set XCR0[1].
This fixes unwanted SEGV signals being triggered by multi-threaded programs using SSE instructions on CPUs that support the xsave features but not the AVX instructions.
Example output when running `ops pkg load node_v14.2.0 -a hi.js`:
```
en1: assigned 10.0.2.15
en1: assigned FE80::CCDC:27FF:FEF2:9DB3
signal …
```
=> x86 init_cpu_features(): enable SSE state in XCR0 when using XSAVE

src/kernel/kernel.h
In an SMP situation, if a thread was running on a cpu and the kernel calls
schedule_frame for that same thread before going back into runloop then
if another cpu grabs and runs that thread then these two cpus will have the
same thread assigned to current. If the new cpu exits and disposes of the
thread then the original cpu has an invalid reference and can crash if it
accesses it. This change calls the pause function on the nanos_thread
associated with the frame during schedule_frame with the idea that if the
thread is being put on the scheduling queue then it should no longer have
a reference on the current cpu. If the cpu's current thread is not the one being
scheduled, then it's a no-op as the pause implementation only performs the
action if the current thread is the one being paused.
=> Pause thread when scheduling frame

tools/mkfs.c
=> Defaults `mkfs` command to usage when no no arg given

src/unix/syscall.c, src/unix/system_structs.h, src/x86_64/unix_machine.h, test/runtime/write.c
Linux does not allow normal read or write to directory file descriptors,
so open should return EISDIR for any write access and read should return
EISDIR if the descriptor is a directory. The write runtime test has been
updated to verify this behavior. This change also defines O_DIRECTORY
which should return ENOTDIR if the specified file is not a directory.
See open(2) and read(2) for further description of these behaviors.
Fixes #1533
=> Check for directory type on open and read syscalls

src/aarch64/interrupt.c, src/aarch64/kernel_machine.h, src/aarch64/page.c, src/aarch64/page.h, src/kernel/init.c, src/kernel/kernel.c, src/kernel/kernel.h, src/kernel/pagecache.c, src/kernel/pagecache.h, src/kernel/schedule.c, src/tfs/tfs.c, src/unix/mmap.c, src/unix/syscall.c, src/unix/thread.c, src/unix/unix_internal.h, src/x86_64/flush.c, src/x86_64/interrupt.c, src/x86_64/kernel_machine.h, src/x86_64/page.c, src/x86_64/page.h, test/runtime/Makefile, test/runtime/mmap.c, test/runtime/mmap.manifest
The existing demand paging fault mechanism was not properly handling the case when a fault for a page occurred while another fault for the same page was being processed. The effects of such races were being masked by the fact that the x86 page table code tacitly allows mappings to be overwritten (this is fixed in #1507). As a result, a mapping set up by one page fault could be displaced by a new mapping set up by a subsequent fault. To remedy this, a "pending_fault" entry is now created for each virtual page address of a demand page fault. When a pending_fault exists for a page that caused a fault, the faulting thread (or kernel context) is added to the pending_fault as a dependent waiter. On completion of the page table flush (tlb shootdown) associated with the mapping created, any …
=> support for concurrent pagefaults

tools/dump.c
The first commit fixes the change to the terminal foreground color made by dump when displaying filesystem contents in tree format (with the `-t` command line option).
The second commit changes the dump output to display filesystem metadata only when the user does not select the tree format option.
=> Dump tool output changes

.gdbinit, tools/nanos_gdb.py
This adds some python-based printing helpers for the buffer and table structs to aid
in examining memory.
=> Add gdb printing helpers for nanos structs

platform/pc/service.c, platform/virt/service.c, src/config.h, src/kernel/init.c, src/kernel/kernel.c, src/kernel/kernel.h, src/kernel/schedule.c, src/runtime/bitmap.c, src/runtime/bitmap.h, src/unix/ftrace.c, src/unix/syscall.c, src/unix/thread.c, src/unix/unix.c, src/unix/unix_internal.h, src/x86_64/apic.c, src/x86_64/apic.h, src/x86_64/crt0.s, src/x86_64/flush.c, src/x86_64/interrupt.c, src/x86_64/kernel_machine.c, src/x86_64/kernel_machine.h, src/x86_64/lock.h, src/x86_64/mp.c, src/x86_64/x2apic.c, src/x86_64/xapic.c, test/runtime/thread_test.c, test/unit/bitmap_test.c
This PR removes the MAX_CPUS limit and replaces the cpuinfos static array with a dynamically allocated vector.
The 64-bit idle CPU mask in the scheduler is replaced by a bitmap, which is initialized in the newly defined function init_scheduler_cpus(); since the idle CPU mask is accessed by interrupt handlers and runloop code, init_scheduler_cpus() is called before probing any devices (such as disks and network interfaces) which could generate interrupts. The call to init_secondary_cores(), where the total number of CPUs is determined, is being moved to just before the call to init_scheduler_cpus().
init_cpuinfo() is being modified in order to allocate dynamically what previously was in a static array.
The fixed-size cpu_set_t type, used in the thread affinity mask and the …
=> SMP: add support for an arbitrary number of vCPUs

src/aarch64/page_machine.h, src/unix/mmap.c, src/unix/syscall.c, src/unix/unix_internal.h, src/x86_64/page_machine.h
The map_and_zero function, used by both demand_anonymous_page and brk to set up new user mappings with zeroed contents, allowed for a race condition whereby a mapping could be set up on one processor (typically as a result of a page fault, not an mmap itself) and then be used by a thread running on another processor before the function had completed zeroing the memory. With webg running in an SMP configuration and a large number of concurrent connections, a range of errors could occur as a result of some memory being zeroed after having been written to. In one such failure mode within the go runtime, a queueing function that used cas would loop indefinitely as the target value, having been zeroed, would never reach the expected value.
This solution takes advantage of the new …
=> fix race condition when setting up new user pages

src/virtio/virtqueue.c
buffer_extend() takes as length value the number of bytes that the caller wants to append to the buffer, not the number of total bytes in the buffer after appending.
This fix prevents an unnecessary buffer extension in all cases where VQMSG_DEFAULT_SIZE (currently 3) descriptors are associated to a virtqueue message, which happens at each I/O request made by virtio-block and virtio-scsi drivers.
=> virtio: vqmsg_push(): fix length value passed to buffer_extend()

src/kernel/kernel.h, src/unix/mmap.c, src/unix/syscall.c
The process heap may consist of non-contiguous chunks of physical memory, thus when the heap is being shrunk the page table needs to be walked to retrieve the physical pages to be deallocated.
=> brk(): fix deallocation of physical memory

src/runtime/buffer.h, test/unit/buffer_test.c
When less than `len` bytes are available after the end of the current contents, buffer_extend() calculates empirically a new capacity value based on the length of the current contents and the `len` value.
If the buffer has been at least partially consumed from, the calculated capacity value may be less than or equal to the current capacity. If it is equal, then buffer_set_capacity() does not do anything, which leaves the buffer in a state not suitable for appending `len` bytes; if it is less, then the buffer memory area is reallocated with a smaller size, which is not necessary.
This PR fixes the above issues by modifying buffer_extend() so that buffer_set_capacity() is called only if the current capacity value has to be increased, otherwise the current buffer contents are moved to the …
=> buffer_extend(): fix handling of consumed buffers

src/net/lwipopts.h, src/net/netsyscall.c, src/unix/system_structs.h
This implements the setsockopt to set the option or flags for the SO_REUSEADDR
and TCP_NODELAY options on sockets by setting their appropriate flags in
the lwip pcbs and enabling reuse address support in lwipopts.
=> Add support for SO_REUSEADDR and TCP_NODELAY

src/aarch64/interrupt.c, src/x86_64/interrupt.c
The external interrupt dispatch routines were re-enqueueing the interrupted
user thread before setting the FRAME_FULL flag and calling interrupt
handlers. This could cause a "frame already full" fault to occur if such a
thread were to be migrated to another CPU and executed before the FRAME_FULL
set occurred in interrupt dispatch. The migrated thread would run and take an
interrupt or issue a syscall, at which point the FRAME_FULL flag would have
been set by the original interrupt dispatch, causing a terminal fault.
This fix simply moves the call to schedule_frame to follow setting of the
FRAME_FULL flag. Even if the thread is migrated to another CPU prior to
runloop service on the originating CPU, the set flag will be cleared upon
return to the user frame.
=> interrupt handlers: move thread enqueue to follow interrupt processing

src/kernel/pagecache.c, src/tfs/tfs.c, src/tfs/tfs.h, src/unix/filesystem.c, src/unix/filesystem.h, src/unix/syscall.c, src/unix/unix_internal.h, test/runtime/fallocate.c, test/runtime/write.c, tools/tfs-fuse.c
When a file is not linked to the filesystem (e.g. as a result of an unlink or rename syscall), its metadata and extent tuples can potentially be destroyed at any time when the TFS log is compacted. Thus, they should not be accessed, even if the file may still exist due to open file descriptors.
This PR modifies the code that handles tuples associated to a file so that it accesses these tuples only if the `md` member of struct fsfile is non-zero (which indicates that the file is linked to the filesystem). filesystem_alloc() and filesystem_dealloc() now take an fsfile argument instead of a tuple, because they can be called for files without an associated metadata tuple.
filesystem_creat_unnamed() no longer creates a tuple (because files opened with O_TMPFILE are not linked to the …
=> TFS: fix handling of files not linked to the filesystem

src/unix/poll.c
If the user events array passed in epoll_wait hasn't been paged in and the
epoll_wait_notify is triggered without a thread then the page fault
for that user memory will fail without the thread context.
=> Set current thread to access user's epoll events array

klib/tun.c, src/net/net.c, src/net/netsyscall.c, src/runtime/list.h, src/unix/blockq.c, src/unix/notify.c, test/runtime/tun.c
This change adds support for the IFF_MULTI_QUEUE flag allowing multiple file
descriptors to point to the same tun interface and adds a simple runtime test of the
ioctls needed to control the queues to. It also adds new manifest options
for tun devices to have a statically assigned ip4 address and netmask as well
as bring the interface up. These changes required exporting several more
functions for klib use.
There is one small bug fix as well to use PBUF_LINK for allocating pbufs which
leaves room for ethernet header, required when forwarding some packets from the
tunnel out another interface.
Finally, the sockaddr_to_addrport was refactored to bring in the conversion of
and ipv4-mapped ipv6 address to ipv4. This covers the multiple
sockaddr_to_addrport uses where it's necessary to force …
=> Tun multi-queue support and static configuration

.circleci/config.yml, test/go/Makefile
With the new debian release the nightly builds began failing to update, and the docker image was a legacy
circleci image that hadn't been updated yet. I switched it over to the replacement convenience image, cimg/go 
that is based on ubuntu and has a slightly newer golang version. I also added 'go mod tidy' to the go Makefile
to try to avoid having an outdated go.mod break the test.
=> Update ci docker image to a newer convenience image

src/unix/eventfd.c, src/unix/poll.c, test/runtime/epoll.c
When epoll_wait() is called, the current event status is checked for all registered file descriptors by calling check_fdesc(), which notifies the current events to the epoll_wait_notify() handler. The events notified to the handler should reflect the current status of a file descriptor, regardless of the last events set on the epoll instance for that descriptor, because the handler uses the notified events to update (set and/or clear as appropriate) the last events. The existing code was removing the last events from the events reported to the handler, which causes the last events to toggle between successive invocations of epoll_wait() even if the status of the file descriptor does not change.
A new test case (test_edgetrigger() function) has been added to the epoll runtime tests to …
=> epoll: fix edge trigger behavior

src/net/netsyscall.c, test/runtime/netsock.c
When both TX and RX directions of a TCP socket are shut down, the `info.tcp.lw` netsock struct member is set to NULL, because the lwIP PCB structure can be deallocated at any time and should not be referenced anymore. If other syscalls are invoked on a shut down socket, they should deal properly with this state and avoid accessing a NULL pointer.
A few more test cases have been added to the netsock runtime tests to exercise handling of sockets after shutdown.
=> Network sockets: fix syscall handling for shut down TCP sockets

src/unix/netlink.c
The Netlink read() closure was applying the generic syscall I/O completion instead of the completion supplied as argument.
=> Netlink read(): apply proper I/O completion

src/unix/futex.c, test/runtime/futex.c
The existing code is storing the number of requeued threads in a local variable that is out of scope when the syscall return value is calculated.
The futex runtime tests have been amended to check for the return value from futex(FUTEX_CMP_REQUEUE).
=> futex(FUTEX_CMP_REQUEUE): fix return value

src/tfs/tfs.c, src/tfs/tfs.h, src/unix/filesystem.c, src/unix/filesystem.h, src/unix/socket.c
The trick currently being used in unixsock_bind() to prevent the address of a bound socket from being stored in the filesystem log is flawed, because if the filesystem is compacted the newly built log will contain the socket address, which can cause invalid memory accesses if the program tries to connect to the socket after a reboot.
This commit changes the format of the filesystem metadata that encodes the address of a bound socket, using sym(no_encode) to prevent the tuple containing the address from being written to the TFS log.
Direct access to filesystem metadata from the Unix socket code (which will be unsafe when the kernel lock is removed) is replaced by the filesystem_mk_socket(), filesystem_get_socket() and filesystem_clear_socket() functions.
The first commit prevents leaking …
=> Unix domain sockets: fix setting of filesystem metadata

klib/tun.c, src/net/netsyscall.c, src/unix/aio.c, src/unix/filesystem.c, src/unix/filesystem.h, src/unix/mmap.c, src/unix/netlink.c, src/unix/pipe.c, src/unix/poll.c, src/unix/signal.c, src/unix/socket.c, src/unix/socket.h, src/unix/syscall.c, src/unix/timer.c, src/unix/unix_internal.h, test/runtime/epoll.c, test/runtime/mkdir.c, test/runtime/sendfile.c, test/runtime/signal.c, test/runtime/unixsocket.c, test/runtime/write.c
Whenever an fdesc structure is retrieved from the list of open file descriptors, its reference count needs to be bumped until the structure is no longer used. This is to avoid accessing invalid memory if a file descriptor is closed while the underlying fdesc structure is still used (e.g. in the middle of a read or write).
This PR changes all file descriptor accesses to use fdesc_get() and fdesc_put(), which update the fdesc reference count appropriately. For all socket callbacks (e.g. sendto, recvfrom, etc.), the onus of calling fdesc_put() is on each implementation of a callback (because it may block and thus not return to the caller).
A couple of error return codes from syscalls have been fixed in the process, in order to match Linux kernel behavior. Some test cases have been added to …
=> Unix file descriptors: implement proper reference counting

src/unix/blockq.c, src/unix/signal.c, src/unix/thread.c, src/unix/unix_internal.h
To support syscall execution outside of the domain of the kernel lock, the
blockq code is revised to allow operations on a blockq to occur safely on
multiple processors. This essentially amounts to protecting the list of
waiting threads per blockq with a spinlock. Other improvements that have been
made include the embedding of the previous "blockq_item" struct directly into
the thread struct, which obviates the need to (de)allocate items on each
block, adding blockq_reserve() and blockq_release() calls to support safe
implementation of thread_attempt_interrupt(), and associating any
io_completions for a given blocking operation with each waiting thread instead
of with the blockq, thus allowing multiple waiting threads to have their own
io_completions, rather than only a single I/O …
=> Revise blockq with locking and other fixes

platform/virt/Makefile, src/aarch64/gdb_machine.h, src/gdb/gdb.h, src/gdb/gdb_internal.h, src/gdb/gdbstub.c, src/gdb/gdbutil.c, src/kernel/kernel.c, src/kernel/kernel.h, src/kernel/schedule.c, src/runtime/text.h, src/unix/exec.c, src/unix/thread.c, src/unix/unix.c, src/unix/unix_internal.h, src/x86_64/breakpoint.c, src/x86_64/frame.h, src/x86_64/gdb_machine.h, src/x86_64/kernel_machine.h
This change updates the in-kernel gdb stub to work again with multi-threaded
user programs running on multiple cpus. It breaks out the architecture
specific parts to allow for future ARM debugging support. This adds support
for thread commands, status, and id. The gdb exception handler was updated
to pass through certain exceptions like page faults, and the handler is
now installed for all frames of all threads on the user process.
Breakpoint handling has been updated allowing hardware breakpoints
to be installed on all cpus, and using the correct code of hardware
breakpoints. This allows the use of software breakpoints which are much
less limiting for line-by-line debugging. Software breaks are not
implemented directly, but deferred to gdb so it will manually insert
trap instructions. …
=> Bring gdb stub up-to-date for user programs

src/unix/aio.c, src/unix/blockq.c, src/unix/filesystem.c, src/unix/filesystem.h, src/unix/futex.c, src/unix/mmap.c, src/unix/poll.c, src/unix/signal.c, src/unix/syscall.c, src/unix/thread.c, src/unix/timer.c, src/unix/unix.c, src/unix/unix.h, src/unix/unix_internal.h
This change adds a spinlock to the thread and process structures, and uses this spinlock to protect structure members against concurrent access.
Also, thread_from_tid() now increments the thread reference count, to prevent a thread from being deallocated while it is being accessed; callers of thread_from_tid() need to call thread_release() when they are done with the thread.
The code that needs to retrieve the current working directory and its filesystem now calls process_get_cwd(), which retrieves this information atomically with respect to the chdir and fchdir syscalls.
For x86_64, the virtual32 heap has been switched from non-locking to locking.
=> Thread and process structures: protect against concurrent access

klib/radar.c, src/kernel/storage.c, src/runtime/buffer.h, src/runtime/storage.h, src/unix/filesystem.c, src/unix/special.c
This file contains the list of currently mounted filesystems, using same syntax as used in the Linux /proc/mounts file.
=> Unix special files: add /proc/mounts

src/tfs/tfs.c, src/tfs/tfs_internal.h
When a file extent that is marked as uninited is written to, all sectors
corresponding to the extent are written, including both the data from the
write request and any zeroed area(s) surrounding it. This presents a problem
when subsequent storage requests are issued on behalf of the extent. Such
requests may be made without first waiting for completion of the initializing
write. This property of the pagecache - that requests are issued without first
waiting for completions for prior requests - is typically not an issue, for
read data is cached and not re-read after a write, and writes are posted from
the same pagecache buffer, making the order of write completions
irrelevant. But the areas of an extent outside of the initial write request,
which are written with zeros, could be …
=> delay storage operations for an extent that is transitioning from uninited to initialized state

src/kernel/pagecache.c, src/kernel/pagecache_internal.h, src/kernel/storage.c, src/runtime/storage.h, src/tfs/tfs.c, src/tfs/tfs.h, src/tfs/tfs_internal.h, src/tfs/tlog.c, src/unix/filesystem.c, src/unix/filesystem.h, src/unix/mmap.c, src/unix/netlink.c, src/unix/syscall.c, src/unix/unix.c, src/unix/unix_internal.h, src/xen/xen.c, src/xen/xen_internal.h, src/xen/xenblk.c, test/runtime/mmap.c, test/runtime/unlink.c
The xen code now supports "watching" xenstore paths, which is the mechanism by which the hypervisor notifies to the guest events such has attachment and detachment of volumes in a running instance.
When a new volume is attached to an instance, the xen driver triggers a rescan of all attached devices, and invokes the probe closure of the xenblk driver: this allows a volume to be automatically mounted by the kernel when attached to a running instance.
The xenblk driver is now notified when a volume detach has been requested. When such notification arrives, the block device is removed from the list of volumes, and if there is a mounted filesystem, the filesystem is unmounted and its reference count is decremented, so that when any open files are closed and any file-backed memory mappings are …
=> Xen: add support for attaching and detaching volumes in a running instance

src/net/netsyscall.c
This is necessary when executing network socket syscalls without the global kernel lock.
=> Network sockets: replace non-locked heaps with locked heaps

src/net/netsyscall.c, src/unix/eventfd.c, src/unix/io_uring.c, src/unix/netlink.c, src/unix/pipe.c, src/unix/poll.c, src/unix/signal.c, src/unix/socket.c, src/unix/socket.h, src/unix/syscall.c, src/unix/timer.c
When allocate_fd() is called, the newly allocated file descriptor number can be accessed by userspace, thus the corresponding kernel structure must be fully initialized to properly handle any syscalls that may be invoked in the file descriptor.
This change makes file descriptor allocation the last step in the initialization sequence of various syscalls, to make it safe in SMP systems without the kernel lock. Most file descriptor allocation errors can now be handled by simply calling the close() function (which will properly clean up the just initialized data structure) and returning -EMFILE.
In the socket code, file descriptor allocation has been removed from socket_init(), and added to its callers after full initialization of socket data.
=> Unix file descriptors: allocate after full initialization

src/unix/signal.c, src/unix/unix_internal.h
In an SMP system, without the kernel lock multiple cores can call dequeue_signal() concurrently; since this function accesses the process signal state, it can happen that a signal initially selected among the pending signals cannot be dequeued because it has been dequeued by another core; in this case, instead of triggering an assertion failure, another attempt should be made at finding a signal to be dequeued; if a signal is successfully dequeued, the corresponding sigstate struct should be kept locked until no longer accessed.
In deliver_signal(), the sigstate struct should be kept locked during the entire sequence of instructions that access it; if the sigstate is unlocked after determining that a signal should be delivered but before setting the signal as pending, it could happen for …
=> Unix signals: make code safe to run without the kernel lock 

src/kernel/kernel.h, src/unix/futex.c
This will allow futex syscalls to be executed in parallel threads without the global kernel lock.
=> futex.c: make code safe to run without kernel lock

klib/radar.c, platform/pc/service.c, platform/virt/service.c, src/kernel/storage.c, src/runtime/storage.h, src/runtime/symbol.c, src/tfs/tfs.c, src/tfs/tfs.h, src/tfs/tfs_internal.h, src/tfs/tlog.c, src/unix/filesystem.c, src/unix/filesystem.h, src/unix/socket.c, src/unix/special.c, src/unix/syscall.c, src/unix/unix.c, src/unix/unix.h, src/unix/unix_internal.h, test/runtime/creat.c, test/runtime/rename.c, test/runtime/symlink.c, test/runtime/write.c, tools/tfs-fuse.c
This will allow filesystem-related syscalls and I/O completions to be run without the global kernel lock.
Syscalls that modify the filesystem and take a file path as argument have been changed so that file path resolution and handling of filesystem tuples is done inside the TFS code, where the filesystem is locked; in cases where reading of filesystem metadata is best done at the syscall level, the new filesystem_get_node() function is now called: this function resolves the supplied path to a tuple (possibly creating a new file in the filesystem) and returns that tuple (as well as an fsfile pointer, if applicable), which can be safely accessed from external code until filesystem_put_node() is called.
To correctly handle cases where a filesystem tuple reference held by a file descriptor …
=> TFS: add protection against concurrent execution

src/kernel/pagecache.c, src/kernel/pagecache_internal.h
Now that the filesystem code is multithread-safe, there is no need to use the runqueue protected by the global kernel lock, and the bhqueue can be used for all I/O completions.
=> Page cache: remove runqueue usage for I/O completions

klib/cloud_init.c, klib/ntp.c, klib/radar.c, src/net/direct.c
A few changes have been made in net/direct.c to allow TCP clients implemented in the klibs to operate correctly:
- connection establishment and shutdown events are processed by the receive service routine instead of being processed directly by the respective lwIP callbacks
- the receive service routine dequeues all pbufs found in a given queue, instead of just the first one
- direct_conn structures created as a result of a client connection being accepted are added to the connection list of the direct structure, so that they are properly serviced
In addition, a missing call to pbuf_free() in the receive service routine has been added.
The radar, ntp  and cloud_init klibs have been fixed to avoid calling lwip_lock() from within the DNS callback, where the lock is already held.
=> Klibs: fix handling of lwIP lock

src/kernel/storage.c
The fist commit fixes a deadlock that would happen if a filesystem creation completion is invoked synchronously (e.g. if an error is encountered).
The second commit fixes a memory leak when a filesystem associated to a volume cannot be mounted.
=> Volumes: fix filesystem leak on error condition

src/unix/filesystem.c
A file path supplied to fsfile_open_or_create() can consist of a simple file name not prefixed by a directory path; in this case, filesystem_mkdirpath() should not be called.
This PR fixes an issue where fsfile_open_or_create() called with a simple fine name would create a directory with the supplied name, instead of creating a file.
=> fsfile_open_or_create(): fix handling of file paths

src/x86_64/crt0.s, src/x86_64/interrupt.c
This change allows nanos to use the full range of interrupt vectors on x86. The idtr is now loaded
from the stack so that the IDT can use the entire page to fit 256 entries.
=> Use 256 max interrupts on x86

src/runtime/bitmap.h, src/unix/io_uring.c, src/unix/notify.c, src/unix/notify.h, src/unix/poll.c, src/unix/signal.c, src/unix/unix.c, src/unix/unix_internal.h
This change primarily adds spinlocks to the polling family of syscalls to enable concurrent execution. To make the
change easier, the polling event handlers were consolidated from three separate functions to a single event handler
that calls polling-type specific code for handling event data and the call to notify_dispatch was removed and replaced
by a function that does the same thing without the notify code. The notify code also adds a spinlock to protect the
notify entries list in the set. The notify event handlers are called with this lock held. The event handler signature
is modified to return a boolean to allow the notify code to remove a notify entry from the list when the event handler
returns true which replaces the need to call notify_remove from the event handler which would …
=> Add locking to polling syscalls and notify set

src/aarch64/machine.h, src/x86_64/machine.h
When the compiler does not support setting the carry flag value directly into
a variable for the atomic test bit functions, it uses a second instruction, setc,
to set the variable. This instruction doesn't appear to set the variable when
the carry flag is zero, although the intel manual suggests otherwise. Therefore
the variable must be initialized to zero since it's on the stack to let the
function return the correct value when the bit being checked is zero.
=> Initialize atomic_test_*_bit variable for older compilers

klib/tun.c, src/kernel/storage.c, src/runtime/storage.h, src/unix/filesystem.c, src/unix/special.c, src/unix/syscall.c, src/unix/unix_internal.h
The /proc/mounts file has special behavior where a change to the file
from a mount or unmount causes poll to return POLLPRI and POLLERR. This
can be used to monitor the mount status of the system. This change
implements this feature by adding a generation number to track changes
to mounts and calling a list of registered handlers whenever a mount
changes. The /proc/mounts special file registers a handler that checks
to see if the generation number has changed and calls notify_dispatch
to send the event to waiters on the file. In order to track the special
file state, a new pointer field is added to the fdesc struct for holding
arbitrary data.
There are also some small fixes to the mounts_handler that generates
the /proc/mounts contents.
=> Allow /proc/mounts to notify pollers of mount change

.circleci/config.yml
This change adds a few steps to the "build-pc" CircleCI job, to upload build artifacts to Google Cloud after a successful run of the test suite. These steps are only executed if the GCLOUD_SERVICE_KEY environment variable is set, so that the job will not fail when triggered by pull requests from forked repositories.
The mkfs and dump tools are not being included in the uploaded artifacts, because Ops provides similar functionalities to create and read image files; this means that the uploaded tarballs for Linux and Mac are identical (we still need separate tarballs because Ops uses the operating system name when downloading Nanos releases from the cloud bucket).
The uploaded tarballs have the "Custom-Time" metadata set, so that it's possible to delete them automatically from the bucket by …
=> CircleCI: upload build artifacts to Google Cloud bucket

src/aarch64/crt0.S, src/aarch64/frame.h, src/aarch64/kernel_machine.h, src/aarch64/unix_machine.c, src/aarch64/unix_machine.h, src/gdb/gdbstub.c, src/unix/blockq.c, src/unix/exec.c, src/unix/io_uring.c, src/unix/signal.c, src/unix/syscall.c, src/unix/thread.c, src/unix/unix_internal.h, src/x86_64/frame.h, src/x86_64/gdb_machine.h, src/x86_64/interrupt.c, src/x86_64/kernel_machine.h, src/x86_64/unix_machine.c, src/x86_64/unix_machine.h, test/runtime/signal.c
The previous signal handling construction required switching to an alternate frame (the "sighandler_frame") when dispatching a signal handler. As such, any signal handling pattern which bypasses rt_sigreturn (such as the use of siglongjmp) will not work, as doing so would prevent signal state stored in the thread struct from being reverted, and threads execution would continue on the sighandler_frame rather than reverting to running on to the default_frame. For the same reasons, nested signal handling was also not supported.
This behavior is corrected by moving all thread execution to a single frame (which, incidentally, is also needed for pending context-switching work) and making use of the sigcontext stored on the thread stack to save and restore program state. Special state held for …
=> fix numerous signal handling issues, use a single context frame per thread

platform/pc/service.c, platform/virt/service.c, src/kernel/init.c, src/kernel/kernel.h, src/kernel/schedule.c, src/xen/xen.c
The existing timer is unreliable when running with multiple cpus and the
recent timer changes. The timer would not fire predictably on all cpus. The
xen interrupt handler was also assuming the interrupt would run only on cpu
0, which was not guaranteed even before the timer change. CPU initialization
has been refactored out to run for every cpu and the timer is now set by
set_singleshot_timer which is configured to fire on the cpu that set it.
This PR also moves idle_cpu_mask allocation to before the APs get started up,
using the present_processors value which is also now calculated before AP
startup. Otherwise if an AP wakes out of sleep and proceeds to runloop it will
try to access the unallocated mask.
=> Update xen timers to per-cpu one-shot for better smp support

src/unix/signal.c, src/unix/thread.c
Running the fst runtime test with MEMDEBUG=mcache revealed that the
signal_stack_length field in the thread struct was being used without being
initialized in thread_is_on_altstack(). This could cause sigaltstack() to fail
with an -EPERM error for a thread that was not running on an alternate signal
stack. The fix here is to make thread_is_on_altsigstack() first check if
t->signal_stack is set before testing if the thread stack pointer is on the
signal stack.
=> fix altsigstack(2) failure due to an uninitialized variable

src/unix/thread.c, src/x86_64/crt0.s, src/x86_64/frame.h, src/x86_64/unix_machine.c
In x86 arch, a user context can return to user mode by either iret or sysret,
with the latter having less state to reload. Therefore, the user frame must
track whether or not it entered the kernel from a syscall or not. There was a
field in the context struct to track this state, but properly updating when
changing the frame, such as with sighandling, is error prone. If the sysret
path is taken instead of iret, some user frame register values may be
incorrect causing crashes or other bad behavior.
This commit removes the field from the context struct and instead tracks
syscall state through the CPL portion of the CS register. This way the syscall
state moves with the registers through context switches or sighandling
frames. The syscall entry point clears bit 0 of the CPL in the saved …
=> Track frame syscall status via CS register instead of context field

src/kernel/init.c, src/xen/xenblk.c
Some storage drivers require alignment for the buffer but the mbr was being
allocated from the general heap which makes no alignment guarantees. This
change allocates the mbr as a page from the backed heap to force a page
alignment.
An assert is also added to the xenblk driver which requires buffers to have
at least 512-byte sector alignment as per xen requirements.
=> Allocate init mbr from backed heap for alignment

Makefile, platform/pc/Makefile, platform/virt/Makefile, rules.mk
Generating the objdump output, kernel.dis, can be a significant portion of time
for incremental compiles and is not necessary for running images. This change
makes a new target to generate the kernel.dis and has the image target generate
only the kernel binary. However, if the variable BUILD_KERNEL_DIS is set then
it will use the old behavior, forcing generation of kernel.dis even if it's not
specified as a make argument. In any case, whenever a new kernel binary is
generated, any existing kernel.dis file is moved to kernel.dis.old so there is no
confusion as to whether or not the disassembly reflects the current binary.
=> Make kernel.dis objdump output a separate Makefile target

src/virtio/virtio_scsi.c
Virtio scsi uses the event queue to pass asynchronous information about
volumes added or removed. This change implements handling of these events.
Virtio scsi disks for a scsi device are now stored in a vector for lookup
by the event handler. The rescan event sends an inquiry to the lun specified
in the event, unless than lun is zero, which triggers a report luns for
the target, as indicated by the specification. LUNs that are detected in this
rescan are not re-added if they already exist in the disk list.
I had implemented handling of unit attention sense codes but I could not trigger
them on GCP, so I left it out of this PR as I was unable to test it and that handling
is more complicated.
=> Add volume event handling to virtio scsi driver

klib/Makefile, rules.mk
Updating the symbol list in klib-syms.lds after a given klib binary is built does not work well when make is run with multiple parallel jobs, because different klib binaries can be built in parallel and thus the symbol list file can be updated concurrently by multiple jobs, which can lead to inconsistencies in the final contents of the file and ultimately cause klib loading to fail due to missing kernel symbols.
This PR changes the make target for generating the symbol list so that this target has the klib binaries as dependencies, and thus is executed only after all binaries have been built. In addition, the following improvements have been made:
- the symbol list is cleared before being re-built: this eliminates symbols that were used in previous versions of klibs but are no longer used …
=> Klibs: fix make dependencies to generate symbol list

klib/cloud_azure.c, klib/cloud_init.c, klib/radar.c, src/http/http.c, src/unix_process/socket_user.c
This change set enhances the HTTP parser and network socket implementation so that the C web server (as run with e.g. `make run TARGET=webs`) does not leak memory when handling client requests.
=> C web server: fix memory leaks

src/aarch64/page_machine.h, src/gdb/gdbstub.c, src/gdb/gdbtcp.c, src/gdb/gdbutil.c, src/kernel/page.c, src/runtime/runtime.h, src/x86_64/page_machine.h
This change deletes the incorrect attempt to acquire the lwIP lock in gdb_send
and removes unnecessary setting of the current thread during memory transfers,
instead relying on validate_virtual() (and the newly-added
validate_virtual_writable()) to insure that memory accesses won't fault. Some
extraneous console output during memory access failures has been removed as
well.
=> restore gdbstub operation; add validate_virtual_writable()

src/net/netsyscall.c, src/unix/netlink.c, src/unix/socket.c, src/unix/socket.h, src/unix/unix.c, src/unix/unix_internal.h, test/runtime/netsock.c, test/runtime/netsock.manifest
This PR changes the socket implementation (for network sockets, Unix domain sockets, and netlink sockets) so that the total length (in bytes) of the input data buffered in a given socket does not exceed the value of the so_rcvbuf parameter (that is configurable via a "so_rcvbuf" attribute in the manifest). The existing limit on the maximum number of packets given by the size of the input queues is kept in place.
In addition, any UDP packets that are discarded due the length of a socket receive buffer being exceeded are now properly deallocated.
getsockopt() has been amended so that it returns the correct value for the SO_SNDBUF and SO_RCVBUF socket options.
The network socket runtime test has been amended to exercise these new features.
The first commit fixes a bug in which a netlink …
=> Sockets: add management of receive buffer size

platform/pc/service.c
The low memory address range from 0 to 1MB is used for things like starting secondary CPUs, so it should not be used for the bootstrap heap and should not be available for general memory allocation, otherwise when a secondary CPU is being started the trampoline code that is copied to low memory could overwrite data used for other purposes.
=> PC physical ID heap: do not use low memory area

src/unix/unix.c, src/unix/unix_internal.h
The definition of the fdesc_io_complete closure in the unix_internal.h header file causes the closure function and the symbols it references to be included in the VDSO shared library, which bloats the VDSO with unneeded code and relocations.
This has a noticeable performance impact and is causing intermittent failures in the Jenkins job that measures web server performance.
This change moves the fdesc_io_complete and fdesc_init function definitions to unix.c, so that the VDSO library does not have unneeded code; for uniformity, the fdesc_release function is also being moved to unix.c.
=> init_fdesc/release_fdesc: change from inline to regular functions

src/unix/unix.c, src/x86_64/kernel_machine.h, src/x86_64/mp.c
Supervisor Memory Execute Protection (SMEP) is a security feature that generates a page fault exception if the kernel tries to execute an instruction from a memory address accessible by the user program. If this exception occurs, the kernel dumps the current execution context to the console and halts.
User-Mode Instruction Prevention (UMIP) is a security feature that generates a general protection exception if the user program tries to execute one of the the SGDT, SIDT, SLDT, SMSW, and STR instructions. If this exception occurs, the kernel sends a SEGV signal to the program. Tested on Google Cloud N2 instance with Intel Ice Lake CPU.
=> x86_64 cpu: add support for SMEP and UMIP

src/unix/syscall.c
filesystem_put_node() should be called only if the previous call to filesystem_get_node() was successful, otherwise the filesystem reference count is wrongly decremented (and the filesystem lock is wrongly released if held by another thread).
=> syscalls: truncate: fix call to filesystem_put_node()

klib/cloud_azure.c, klib/cloud_init.c, klib/mbedtls.c, klib/radar.c, src/http/http.c, src/hyperv/vmbus/vmbus_et.c, src/net/direct.c, src/runtime/runtime.h
The first commit adds a schedule_timer_service() call to the VMbus interrupt handler, which fixes an issue causing sporadic failures in IP address assignment on Azure instances.
The second commit modifies the net/direct.c code to ensure that the data structures for handling a network connection are not accessed after the connection has been closed; this fixes a crash occurring on Azure instances when the cloud_init klib reports the instance status to the wire server.
=> Microsoft Azure fixes

src/unix/pipe.c, test/runtime/pipe.c
The Unix pipe implementation is incorrectly reporting both EPOLLIN and EPOLLHUP events on a pipe reader file descriptor after closing the writer file descriptor. This is causing `Null check operator used on a null value` unhandled exceptions when running a Dart program without AOT compilation.
This change fixes the above issue by only reporting EPOLLIN if data is available in the pipe buffer. A test case is being added to the pipe runtime test to check that the correct poll events are reported after closing the write side of a pipe.
=> Unix pipe: only report EPOLLIN event when data is available to read

src/net/netsyscall.c, src/unix/system_structs.h
This adds support in getsockopt for reading the values of SO_REUSEADDR,
SO_REUSEPORT, and TCP_NODELAY. SO_REUSEPORT is not currently
supported so it always returns 0 and setting it is a no-op. This also fixes
setting TCP_NODELAY in setsockopt which was setting the opposite value
requested.
=> Add getsockopt support for reuseport/addr and tcp_nodelay

platform/pc/Makefile, platform/pc/service.c, platform/virt/Makefile, tools/mkfs.c
With the introduction of acpica and the default installation of the
acpi_powerdown vm_halt method on the PC platform, runtime CI tests have not
been passing the test exit codes back to the shell. This results in "make
runtime-tests" passing even if tests have failed with a non-zero exit code.
This adds a "debug_exit" manifest flag to indicate that vm_exit() should
return to qemu via the QEMU_HALT() function regardless of whether the platform
has installed a vm_halt method. An option has been added to mkfs to allow the
amending of manifest root tuples from the command line. Runtime tests are now
built with "debug_exit:t" added to the root tuples by default.
=> restore correct detection of runtime test errors by defaulting to qemu debug exit

platform/pc/Makefile, platform/virt/Makefile, src/aarch64/crt0.S, src/aarch64/kernel_machine.c, src/aarch64/kernel_machine.h, src/aarch64/machine.h, src/kernel/kernel.c, src/kernel/mutex.c, src/kernel/mutex.h, src/net/lwip.h, src/net/net.c, src/net/netsyscall.c, src/runtime/context.h, src/x86_64/crt0.s, src/x86_64/kernel_machine.c, src/x86_64/kernel_machine.h, src/x86_64/machine.h
Building off of the context switching work, this change implements a two-phase
mutex lock which will first spin for some number of iterations (specified on mutex
allocation) before finally suspending the running context if the mutex could
not be acquired. Suspended contexts are queued and processed in a FIFO
fashion, with the unlock function dequeueing and directly scheduling the next
context waiting on the mutex, if any. This is useful for preventing cores from being
excessively tied up with spinning while there is resource contention. The spin
factor argument given on instantiation may be adjusted according to the needs
of the workload; a value of 0 indicates no spinning is desired - in which case
a context will suspend whenever the mutex cannot be immediately acquired - but
may also be …
=> mutex implementation

.gdbinit, src/unix/unix.c, tools/nanos_gdb.py
This change adds a new python gdb command, print_tree, to print the pointers of
rbnodes of an rbtree in order. If a second argument, containing type, is passed
the script will print the pointers to the containing struct instead of the
rbnode. Also added are helper macros offsetof() and container_of() which can
be used in gdb expressions.
Also added is a new array called 'processes' containing the pointers to the two
process structs in order to facilitate easier process debugging.
Example usage:
```
(gdb) print_tree processes[1]->threads thread
(struct thread *)0xffffc00000e03000
(struct thread *)0xffffc00000e04000
(struct thread *)0xffffc00000e05000
(struct thread *)0xffffc00000e06000
(gdb) 
```
=> Add print_tree command to gdb script to print rbtree

src/aarch64/kernel_machine.c, src/kernel/kernel.h, src/x86_64/kernel_machine.c
This fixes missing initialization of the context's next_waiter field and moves
init_context() to kernel.h. Per-architecture context initialization now occurs
in init_context_machine().
#1661
=> fix uninitialized variable in init_context(), refactor

src/drivers/netconsole.c, src/kernel/mutex.h
This PR fixes a couple of bugs in the netconsole code:
1) in netconsole_config(), the wrong character buffer was being used to create a NULL-terminated string
2) in netconsole_write(), lwip_lock() was being called unconditionally, which could lead to a fatal error if the lwIP lock is already held by the current context
Closes #1665.
=> Netconsole fixes

src/tfs/tlog.c
run_flush_completions() in tfs/tlog.c is called with the TFS lock held. In the kernel code, one of the flush completions can trigger the following sequence of function calls: pagecache_sync_volume -> pagecache_scan -> pagecache_commit_dirty_pages -> filesystem_storage_write; the last function in this sequence tries to acquire the TFS lock, which results in a deadlock.
This change solves the above issue by invoking the TFS log flush completions asynchronously.
=> TFS: run flush completions asynchronously in kernel code

.circleci/config.yml, rules.mk, src/kernel/init.c, src/kernel/kernel.h, src/runtime/heap/mcache.c, src/runtime/heap/mem_debug.c, test/e2e/e2e.go
This change adds new convenience compile options to add a mem_debug wrapper to the linear
backed heap with MEMDEBUG=backed or MEMDEBUG=all. However, the linear backed heap uses
2MB pages, which would require 4MB additional memory for padding on each allocation. For
a non-trivial program this consumes too much memory, so mem_debug_backed has been
modified with a nohdr flag that does not allocate padding, forgoing allocation metadata and
overrun checks, leaving only the initialized and freed patterns checks since they require no
additional memory. The CI script has been modified to use MEMDEBUG=all.
The e2e.go program has also been modified to pass the number of host cpus to ops in
order to have smp testing for the e2e tests.
=> Add new mem_debug compile options and nohdr flag for mem_debug_backed; smp for e2e tests

src/runtime/vector.h, src/unix/syscall.c
With this change, the string placed in the `nodename` field of the struct passed to the uname syscall is derived from the contents of the /etc/hostname file, if present in the root filesystem, or from the IP address of the default network interface.
Using the IP address allows different instances created from the same image to have different host names, similarly to what happens with Linux instances in AWS or GCP.
=> uname(2): derive nodename from either /etc/hostname or IP address

platform/pc/Makefile
The BSD/OS X implementation of getopt stops processing at the first non-option
argument. The mkfs command had the debug_exit option specified after the image
and so that option was not getting processed by getopt, causing test failures on OS X
not to be registered. This change moves the debug_exit argument with the others
so that it will be processed.
=> Reorder mkfs debug_exit argument before image argument

klib/syslog.c
This PR contains miscellaneous improvements to the syslog klib:
- in case of failure to resolve the syslog server name, the backoff delay for retrying DNS resolution is limited to 1 minute, to prevent long delays before logs start to be shipped after a previously unresolvable server becomes resolvable
- the dns_gethostbyname() function is now called before sending syslog packets, even after the server name has been
successfully resolved, so that when the cached DNS entry expires a new DNS request will be sent and any changes to the server IP address will be observed
- if the IMAGE_NAME environment variable is present, it is used to populate the APP_NAME field in syslog messages, while
the program name is used as a fallback
=> Klibs: syslog improvements

src/config.h, src/kernel/kernel.c, src/kernel/kernel.h, src/kernel/mutex.c, src/kernel/mutex.h, src/net/net.c, src/runtime/context.h, src/runtime/list.h, src/unix/syscall.c
This updates the two-phase mutex to use a cancelable MCS (Mellor-Crummey and
Scott) lock, which allows only one spin waiter to contend for the mutex at a
time. As before, a mutex lock operation will spin for only m->spin_iterations
before reverting to suspending the context. Before suspending, the cpuinfo is
removed from the MCS list, and the corresponding context is added to the
mutex's queue of waiters. (The waiters list is now a standard doubly-linked
list, protected by a spinlock within the mutex.) If the MCS lock was acquired
while spinning, the mutex itself is then taken and the MCS lock is released,
passing ownership to the next queued spinner, if there is one.
On an unlock, the mutex is released by zeroing m->turn. This may allow the
current holder of the MCS lock, which is …
=> use an MCS lock for mutex spinwaiters

src/hyperv/utilities/vmbus_ic.c, test/runtime/thread_test.c
New versions of gcc cause two new static analysis warnings which cause build
failures. One is an error in allocation size and the other is an uninitialized
variable.
=> Miscellaneous changes to silence new gcc warnings

klib/Makefile
This requires a few more files from the mbedtls library to be built and included in the tls klib.
Depends on https://github.com/nanovms/mbedtls/pull/1.
In order to update the mbedtls code, remove the vendor/mbedtls/.vendored file and rebuild the kernel.
=> klibs: tls: upgrade mbedtls to v2.28.0

Makefile, platform/pc/service.c, platform/riscv-virt/service.c, platform/virt/service.c, src/aarch64/interrupt.c, src/aarch64/kernel_machine.h, src/aarch64/unix_machine.c, src/boot/uefi.c, src/kernel/kvm_platform.c, src/riscv64/kernel_machine.h, src/riscv64/unix_machine.c, src/runtime/runtime.h, src/unix/exec.c, src/unix/signal.c, src/unix/system_structs.h, src/unix/thread.c, src/unix/unix.c, src/unix/unix.h, src/unix/unix_internal.h, src/unix_process/unix_process_runtime.c, src/x86_64/interrupt.c, src/x86_64/kernel_machine.h, src/x86_64/unix_machine.c, test/runtime/Makefile, test/runtime/signal.c, test/runtime/sigoverflow.c, test/runtime/sigoverflow.manifest
This PR adds detection and handling for signal frame overflow and also corrects tid handling, which should
share the same namespace as pids. The first thread in a process should have its id match the pid.
This also adds support for the SIGILL and SIGTRAP signals which can be used in exception handling
in user programs. Runtime tests have also been added for the new signals and for the signal frame
overflow.
=> Add support for SIGILL and SIGTRAP; correct tid handling and sigframe overflow

src/kernel/init.c
After the mbr was read from additional volumes vm, the allocated mbr buffer was being deallocated to the mcache
but is allocated from the backed heap. This resulted in a nanos warning message.
=> Deallocate additional volume mbr buffer from correct heap

tools/dump.c, tools/mkfs.c, tools/tfs-fuse.c
Some versions of OS X and BSD do not have support for preadv and pwritev, so
use lseek and readv/writev instead for the tools.
=> Use readv/writev in tools for broader compatibility

src/aarch64/uefi.c, src/kernel/kernel.h, src/kernel/page.c, src/kernel/page.h, src/unix/mmap.c, src/x86_64/flush.c, src/x86_64/lock.h
This PR contains a few changes to improve kernel performance when running on instances with a high vCPU count:
- avoid repeated execution of atomic instructions
- avoid unneeded TLB shootdowns
=> SMP optimization

src/runtime/heap/id.c, src/runtime/heap/id.h, test/unit/id_heap_test.c
Using a first-fit allocation policy in the id heap does not scale well with heap size, because after a substantial amount of allocations, for each subsequent allocation a large number of heap locations needs to be scanned (especially for small-sized allocations) before a free location is found.
Yet, a simple next-fit allocation policy leads to excessive memory fragmentation when allocations of different sizes are interleaved, because a large gap is formed when a large allocation follows a small allocation (to satisfy the id heap alignment property).
This commit implements a more advanced next-fit allocation policy where different next-fit locations are stored for different allocation sizes: this prevents a large allocation from affecting the next-fit pointer for smaller allocations and …
=> id heap: implement next-fit search based on allocation size

src/hyperv/storvsc/storvsc.c, src/virtio/scsi.h, src/virtio/virtio_scsi.c
This change adds detection of a volume attachment point in the virtio SCSI and HyperV storage drivers.
With these changes, it is possible for GCP and Azure images to mount volumes by using mount directives that reference an attachment point alternatively to a volume name (see also https://github.com/nanovms/ops/pull/1301).
=> Virtio SCSI / HyperV: add detection of volume attachment point

platform/riscv-virt/Makefile, rules.mk, src/aarch64/clock.c, src/riscv64/clock.c, test/runtime/Makefile
This PR adds a number of improvements for building alternate architectures, including:
* generate error if RISC-V compiler is too old to support current RISC-V ISA
* add -mno-outline-atomics to ARM builds if the compiler supports it to eliminate linking errors
* use more appropriate flags for specifying system includes and libraries for runtime tests
* fix clock type bug for ARM and RISC-V
=> ARM and RISC-V build improvements

src/net/netsyscall.c, src/unix/system_structs.h, test/runtime/netsock.c
This adds support for SO_KEEPALIVE and SO_BROADCAST socket options under the
SOL_SOCKET protocol level. The netsock test has been modified to check that
these options, if set on a listening socket, are inherited by accepted
sockets.
Also, the netsock test was previously failing under Linux, with the write() in
netsock_test_basic() failing with the errno EDESTADDRREQ (89). This was a
result of a missing connect() on the datagram socket, a condition that was
silently being ignored by Nanos. socket_write_udp() has been updated to report
this error when attempting to send to an unconnected udp socket, and a test
for this condition, as well as the required call to connect(), have been added
to the netsock test.
=> support SO_KEEPALIVE and SO_BROADCAST sockopts, socket_write_udp(): fail on sending to an unconnected socket

src/unix/unix.c
When the fault handler is invoked, the CPU state is the same as the state when the interrupt was triggered. Therefore, it is not necessary for the fault handler to set the state when returning the current context; in fact, this causes a wrong state to be set when a user thread generates a page fault that is resolved without blocking, which may cause any subsequent exception generated by the thread to be handled as if it was generated by the kernel.
=> Unix fault handler: do not change CPU state

src/aarch64/interrupt.c, src/aarch64/kernel_machine.h, src/riscv64/interrupt.c, src/riscv64/kernel_machine.h, src/riscv64/page.c, src/unix/signal.c, src/unix/thread.c, src/unix/unix.c, src/unix/unix_internal.h, src/x86_64/interrupt.c, src/x86_64/kernel_machine.h, test/runtime/signal.c
This addresses a common problem whereby the kernel can panic on a user page
fault that occurs within a syscall context. Such faults are usually caused by
the user program supplying an invalid buffer address, and as such should be
treated as segmentation violations. This handles such cases by marking the
relevant thread's current syscall as having been "abandoned," thereafter
delivering SIGSEGV to the violating process - just as if the fault had
occurred from within user mode. The abandoned syscall is "cleaned up" in
thread_return() before returning control to the program (albeit not
completely; see the comment in that function).
This also addresses a few cosmetic issues with output that occurs after
terminal signal delivery. To aid the debugging of such violations, frames of
the the …
=> unix_fault_handler: deliver SIGSEGV on user page faults from syscall context

src/runtime/heap/id.c
An id heap deallocation would unconditionally update the next bit for a given
allocation size. This behavior would unnecessarily waste space in the heap if
the next bit was being replaced by a larger value. This effect materialized in
one case where file descriptors were continually increasing through many
cycles of opening and closing files, eventually exhausting the fd_set size
limit (FD_SETSIZE) being used for select(2).
This change prevents such behavior by only updating the next bit for an
allocation size with one of a lesser value.
=> id_heap dealloc_from_range(): only update next bit to a lower value

src/unix/poll.c, test/runtime/signal.c
Our select implementation incorrectly assumed that a call with zero nfds
specified and an indefinite timeout should return immediately. Such a call may
legitimately be used to wait for signal reception, though, so
select_internal() has been changed here to enter an indefinite, interruptible
block whenever a NULL timeout is specified, regardless of the value of
nfds. The signal test now checks that such a call to select behaves in the
same manner as pause(2).
=> select(2): allow blocking indefinitely with zero nfds

doc/lock-profiling.txt, platform/pc/Makefile, src/aarch64/interrupt.c, src/aarch64/kernel_machine.h, src/kernel/kernel.c, src/kernel/kernel.h, src/kernel/lockstats.c, src/kernel/lockstats.h, src/kernel/lockstats_struct.h, src/kernel/mutex.c, src/kernel/mutex.h, src/riscv64/interrupt.c, src/riscv64/kernel_machine.h, src/runtime/heap/heap.h, src/runtime/heap/objcache.c, src/runtime/range.c, src/runtime/range.h, src/runtime/table.c, src/runtime/table.h, src/unix/blockq.c, src/unix/unix.c, src/x86_64/interrupt.c, src/x86_64/kernel_machine.h, src/x86_64/lock.h, src/x86_64/machine.h, test/unit/Makefile, test/unit/objcache_test.c, test/unit/table_test.c, tools/lockstat.py
This PR introduces optional lock profiling support to be built into the kernel. Lock profiling is controlled
by a simple http interface allowing you to turn it on, off, or download the statistics. The statistics gathered
are for acquisition/contended acquisition counts and times for each backtrace accessing a lock. Statistics
are gathered per cpu and collated together when fetching the output. A new python script is added to help
with analysis of the lock output and show which backtraces access the same lock.
Gathering these lock statistics required some supporting changes including generating a frame trace
and adding versions of the objcache and table data structures that can be preallocated to avoid
any runtime allocations and deadlocks when accessing the shared heap.
=> Add lock profiling support

src/unix/syscall.c
The syscall handler must resume the syscall context installed on low-level
entry, completing the context switch. syscall_handler() was previously exiting
on shutdown or an invalid syscall without performing this restore, causing an
assertion failure when the pause method for the context is called on the next
context switch. This materialized when the clone() wrapper in glibc 2.34
attempted to invoke the unimplemented clone3(2) syscall. With this fix, glibc
safely handles the -ENOSYS from the invalid syscall and falls back to using
clone(2).
https://github.com/nanovms/ops/issues/1321
=> syscall_handler: do not bypass syscall context resume

src/runtime/buffer.h, src/unix/special.c
In the current implementation, the following info is returned: MemTotal, MemFree, MemAvailable (whose value is approximated as the sum of free memory and page pache occupancy) and Cached.
=> Unix special files: add /proc/meminfo

src/drivers/acpi.c, src/drivers/acpica.mk
This change implements a handler for the ACPI sleep button event, which is triggered in a GCP instance during a VM suspend operation. This handler communicates with the ACPI firmware to put the system in the ACPI S3 state, at which point the VM is suspended; then, when a VM resume operation is requested, guest execution resumes from where it was suspended (at the call to AcpiEnterSleepState()), after which the sleep button handler indicates to the ACPI firmware that wakeup has completed and the VM resumes normal operation.
=> ACPI: add support for entering S3 sleeping state (VM suspend)

src/net/netsyscall.c
A socket generated by an accept syscall from a listening socket should inherit
the tcp flags at the time of the accept syscall, not when the connection is
initiated at the network stack. This way, any changes to the listener's tcp flags
between the initiation of the connection and the accept syscall are appropriately
reflected in the child.
=> Copy flags from listening socket at accept syscall

src/unix/syscall.c
Thousands of failed write syscalls can eventually exhaust memory if the status tuple is not freed.
=> Free status tuple when file write fails

src/x86_64/x2apic.c, src/x86_64/xapic.c
This resolves errors in the macOS build.
=> x2apic_ipi, xapic_ipi: target comparison requires explicit cast

.circleci/config.yml, rules.mk, src/aarch64/clock.c, src/aarch64/machine.h, src/kernel/init.c, src/kernel/vdso-now.c, src/kernel/vdso.h, src/riscv64/clock.c, src/riscv64/machine.h, src/riscv64/serial.c, src/runtime/bitmap.c, src/runtime/clock.h, src/unix/io_uring.c, src/unix/syscall.c, src/virtio/virtio_net.c, src/x86_64/apic.c, src/x86_64/clock.c, src/x86_64/kernel_machine.h, src/x86_64/machine.h, src/x86_64/mp.c
This change allows specifying an `UBSAN` Makefile variable that enables instrumenting the compiler-generated code with instructions to catch bugs that can result in undefined behavior. When UBSan detects an error, it generates a software trap (on x86-64, an "invalid opcode (UD2)" exception; on aarch64, a "brk" exception that results in an ESR value of 0xf20003e8; on risc-v, a breakpoint exception), which triggers a crash dump in the kernel.
UBSan checks for unaligned accesses and null pointers are being disabled because the kernel contains legitimate uses of unaligned accesses (mainly in third-party code such as acpica and lwIP) and null pointers (in the x86-64 code for secondary CPU bringup).
`UBSAN=1` is being added to the make command line in the build-pc-memdebug CircleCI job (now …
=> Add support for UBSan (undefined behavior sanitizer)

src/unix/exec.c, src/unix/system_structs.h, src/x86_64/kernel_machine.h, src/x86_64/mp.c, src/x86_64/unix_machine.h, test/runtime/thread_test.c
The FSGSBASE instructions allow reading and writing the FS and GS registers with dedicated CPU instructions, avoiding the need for the arch_prctl syscall and therefore providing performance benefits.
This change adds detection of the FSGSBASE capability from the CPU; if this capability is detected, the FSGSBASE instructions are enabled and their support is reported to userspace in the auxiliary vector.
=> x86: add support for FSGSBASE instructions

src/unix/exec.c, src/unix/syscall.c, src/unix/unix_internal.h
An elf binary can ask for loading of a program segment above the current limit (1GB) causing a panic. The current
limit appears arbitrary, so it has been adjusted to 3GB, and the user stack allocation has been moved to just under
4GB so that it will not conflict with program segments.
Additionally, the exit syscall was not triggering a shutdown if called by the last thread of a program (in lieu of exit_group).
This has also been fixed.
=> Fix load program limits and exit syscall

src/unix/unix_clock.c, test/runtime/time.c
The current code returns a 1-nanosecond resolution (which is the highest resolution value that can be expressed by a struct timespec) for all supported clock types.
Closes #1209
=> Syscalls: add clock_getres() implementation

platform/virt/service.c, src/kernel/elf.c, src/kernel/klib.c, src/kernel/linear_backed_heap.c, src/kernel/pagecache.c, src/kernel/symtab.c, src/runtime/heap/id.c, src/runtime/range.c, src/runtime/range.h, src/tfs/tfs.c, src/tfs/tlog.c, src/unix/exec.c, src/unix/mmap.c, src/unix/system_structs.h, src/unix/unix.c, src/unix/unix_internal.h, src/x86_64/uefi.c, test/runtime/mmap.c, test/runtime/mmap.manifest, test/unit/range_test.c
This merge covers a range of bug fixes and new features in the mmap code, as
summarized below:
- The mmap(2) implementation was insufficiently checking the flags parameter,
selecting for implemented flags and ignoring all others. This change
explicitly checks for known options and validates that unknown options are
not blindly accepted.
- This fixes a flaw in the mmap(2) implementation whereby a vmap would be
allocated for a new mapping, only to be immediately removed and replaced
with an identical one.
- The p->virtual32 heap has been removed in place of making range allocations
of address space, which is made possible by the rangemap-based allocation of
vmaps.
- Since moving away from using an id heap to allocate process address space,
"vareas" no longer serve a useful function. They …
=> fixes and new features for mmap(2) and mremap(2)

src/kernel/stage3.c, src/kernel/storage.c, src/tfs/tfs.c, src/tfs/tfs.h, src/unix/filesystem.c, src/unix/syscall.c
Support mounting tfs volumes read-only by checking for a string ":ro" appended
to the path of a volume in the mounts tuple. While tfs already supported a flag
for a read-only filesystem, support had to be added for checking the flag and
returning an appropriate error that could be translated into EROFS for syscalls.
Additionally, the filesystem_creat_unnamed function needed to change to support
returning errors.
=> Support mounting volumes read-only

platform/pc/Makefile, platform/pc/service.c, platform/riscv-virt/Makefile, platform/riscv-virt/service.c, platform/virt/Makefile, platform/virt/service.c, src/kernel/init.c, src/runtime/random.c, src/runtime/runtime.h, src/unix/syscall.c, src/unix_process/unix_process_runtime.c, src/virtio/virtio.h, src/virtio/virtio_rng.c, test/runtime/getrandom.c
This introduces support for the virtio entropy device. When available, this
device will serve as the main source of entropy for the random number
generator. A hardware entropy source (e.g. rdseed and rdrand on x86-64) serves
as a fallback option when a virtio entropy device is not found.
Entropy data is stored in a double-buffered fashion with the intent to keep
entropy available for randomize functions without the need to block. Should an
underrun in entropy data occur, the aforementioned fallback option is used to
fulfill the request.
Other changes include adding a mutex to guard chacha20 usage and splitting
large getrandom(2) requests into smaller chunks to avoid starving other work.
Resolves #1440
=> virtio-rng support

src/unix/thread.c
The existing clone(2) syscall implementation was detecting whether the user program is trying to create a new process by checking the child_stack argument against a null value. This logic is based on the fact that the glibc fork() wrapper that is provided as part of the NPTL threading implementation invokes clone(2) with child_stack set to 0. However, it is possible to create a new process even if child_stack is non-zero: notably, the posix_spawn() implementation in glibc invokes clone() with a valid stack pointer, which is later unmapped by the parent process after the child starts executing the newly created process. The correct way for clone(2) to detect an attempt to create a new process is by checking for the CLONE_THREAD flag.
=> clone(2): fix check for attempts to create new process

src/unix/special.c
The readonly status added in https://github.com/nanovms/nanos/pull/1728 should be shown in /proc/mounts:
```
root / tfs ro 0 0
testvol /test tfs rw 0 0
testvolro /testro tfs ro 0 0
```
=> Reflect a volume's readonly status in /proc/mounts

platform/pc/Makefile, platform/pc/boot/stage2.c, platform/pc/linker_script, platform/pc/service.c, src/drivers/acpi.c, src/drivers/acpi.h, src/kernel/region.h, src/virtio/virtio.h, src/virtio/virtio_mmio.c, src/x86_64/crt0.s, src/x86_64/page.c, src/x86_64/uefi.c
With this change set, the kernel supports booting via the HVM direct boot protocol and running on the microvm Qemu
machine type.
The first 2 commits are fixes for issues in the initialization code run when the kernel is not loaded by the stage2 bootloader.
`make run KERNEL_BOOT=1` runs an image with direct kernel boot (while using the default q35 Qemu machine type); direct kernel boot results in faster boot times compared to bootloader boot.
`make run MICROVM=1` runs an image by using the microvm Qemu machine type; this setting automatically enables direct kernel boot; using microvm results in faster boot times and less memory consumption compared to using the q35 machine type (either with or without direct kernel boot).
=> x86: add support for microvm Qemu machine type

src/unix/syscall.c, src/unix/unix_internal.h
This changeset fixes two issues found in the code that computes syscall execution statistics:
- the syscall_time field of the thread struct was not being initialized at syscall entry
- the count_syscall_save() function was not handling properly multiple consecutive calls without count_syscall_resume() being called in-between
=> Syscall stat fixes

src/aarch64/unix_machine.c, src/kernel/clock.c, src/riscv64/unix_machine.c, src/runtime/timer.c, src/runtime/timer.h, src/unix/timer.c, src/unix/unix_clock.c, src/x86_64/unix_machine.c, test/runtime/time.c, test/runtime/time.manifest
These syscalls allow changing the system (wall clock) time.
In addition, a few fixes are being applied to the existing timer code:
- use the monotonic clock in all itimer types
- implement proper locking in order to safely change the real-time clock from multiple sources, such as syscalls and NTP, and safely access the timerqueue during a real-time clock change in SMP systems
- move resetting of RTC offset value in the VDSO structure so that timer reordering uses the updated offset
- properly adjust expiry time for absolute timers based on real-time clock
The TFD_TIMER_CANCEL_ON_SET option is now implemented.
A set of test cases is being added to the runtime tests to exercise the new syscalls and test the behavior of active timers when the real-time clock undergoes a discontinuous change.
=> Syscalls: add timer_settime and settimeofday

klib/ntp.c, src/kernel/clock.c, src/kernel/vdso-now.c, src/kernel/vdso.h, src/runtime/clock.h, src/runtime/extra_prints.c, src/runtime/timer.h
Instead of using a single rate to correct both frequency and offset errors,
these changes use a least squares linear regression to estimate the values
separately using a relatively large number of data points, where the slope
represents the frequency error and the intercept equals the offset. With this
method of calculating frequency error, it the ntp klib can now track
the reference clock with sub-millisecond per second accuracy. The frequency
error gets applied to all clocks except for MONOTONIC_RAW (by definition).
The slewing adjustments are applied only to the realtime clock. With the
separation of error components, the offset error can be much more
aggressively slewed away, correcting offsets of over a second within a single
query interval. Older samples are adjusted for offset …
=> Improve ntp klib accuracy and correction rate

src/unix/syscall.c, src/unix/system_structs.h, test/runtime/aio.c, test/runtime/fallocate.c, test/runtime/fs_full.c, test/runtime/ftrace.c, test/runtime/futexrobust.c, test/runtime/io_uring.c, test/runtime/mkdir.c, test/runtime/mmap.c, test/runtime/netsock.c, test/runtime/nullpage.c, test/runtime/paging.c, test/runtime/signal.c, test/runtime/sigoverflow.c, test/runtime/symlink.c, test/runtime/time.c, test/runtime/tlbshootdown.c, test/runtime/unixsocket.c, test/runtime/vsyscall.c, test/runtime/write.c
Describing stdout as a pseudo-tty makes glibc apply line buffering (instead of full buffering) when the process writes to stdout. This removes the need for calling `setbuf(stdout, NULL)` in the runtime test programs.
On x86, tested with glibc version 2.23, 2.24, 2.27, 2.28, 2.31, and 2.34; musl libc does not apply full buffering (tested with version 1.2.2), with or without this change.
On ARM, tested with glibc version 2.28.
On risc-v, tested with glibc version 2.32.
=> Unix stdout: describe file descriptor as a pseudo-tty

src/kernel/pagecache.c, src/kernel/pagecache_internal.h
This lock protects from concurrent access to the list of page cache volumes.
=> Page cache: add global lock

platform/pc/service.c, platform/riscv-virt/service.c, platform/virt/service.c, src/aarch64/gic.c, src/aarch64/kernel_machine.c, src/aarch64/kernel_machine.h, src/kernel/init.c, src/riscv64/kernel_machine.h, src/runtime/runtime.h, src/x86_64/interrupt.c
This change introduces a new option, called "idle_on_exit", which when specified in the manifest keeps a VM running (with all VCPUs halted) after the user program exits successfully.
The implementation of the machine_halt() function for aarch64 and risc-v is being fixed so that it actually halts the CPU and does not return.
Generation of the broadcast shutdown IPI (which is only needed when the idle_on_exit option takes effect) is being removed from where it is not needed.
Handing of the reboot_on_exit option is being modified so that this option only takes effect if the exit code is not the expected one (i.e. if either the application terminates with error, or the kernel crashes), because this was the original intent behind this feature, and rebooting unconditionally makes it impossible …
=> vm_exit(): add idle_on_exit option

src/runtime/range.c
If (for e.g.) the new heap range requested by brk was previously
mapped by mmap then rangemap_insert will fail. When this happens we
want to leave the rangemap how we found it. Otherwise it effectively
unmaps the heap.
So this reinserts the original range if the new one fails. Other
callsites of rangemap_reinsert all assert that it passes. So this
change should not effect them.
This should fix #1751 and with #1735 allow nodejs 18.x to run.
=> rangemap_reinsert: roll back to old range and reinsert on failure

src/kernel/pagecache.c, src/kernel/pagecache_internal.h, src/runtime/sg.c, src/runtime/sg.h
The first commit fixes handling of concurrent page writes and reads.
The second commit makes page refcounting race-free with regard to the pagecache drain functionality, fixes a missing refcount release after a write completion, and fixes a 'refcount_release: invalid count 0' error occurring when a node with evicted pages is deallocated.
The third commit fixes a memory leak occurring when pages belonging to a deallocated node are released, and properly removes these pages from the global free page list.
=> Pagecache: fix page refcounting and races with page eviction

src/aarch64/unix_machine.c, src/kernel/kernel.h, src/net/net_system_structs.h, src/net/netsyscall.c, src/riscv64/unix_machine.c, src/runtime/closure.h, src/unix/netlink.c, src/unix/socket.c, src/unix/socket.h, src/unix/syscall.c, src/x86_64/unix_machine.c, test/runtime/netsock.c
This Linux-specific syscall allows receiving multiple messages from a socket. The timeout feature (which even in Linux does not work as intended) is not implemented.
In addition, the functionality of the existing sendmmsg syscall has been expanded to cover not only network sockets, but any type of socket that implements the sendmsg callback.
For network sockets, the code that handles data transmission and reception has been refactored to use iovec structures instead of a single contiguous buffer; this allows avoiding the additional buffer allocation and copying that was done for sendmsg, sendmmsg, and recvmsg.
For datagram sockets, the MSG_TRUNC option is now implemented (both as an input flag specified by the user process in a syscall, and as an output flags set by the kernel).
=> Syscalls: add recvmmsg implementation

src/config.h, src/drivers/acpi.c, src/hyperv/netvsc/hv_net_vsc.h, src/hyperv/netvsc/netvsc.c, src/hyperv/storvsc/storvsc.c, src/kernel/init.c, src/kernel/kernel.h, src/kernel/pagecache.c, src/net/netsyscall.c, src/runtime/heap/heap.h, src/runtime/heap/mcache.c, src/runtime/heap/mem_debug.c, src/runtime/heap/objcache.c, src/unix/pipe.c, src/unix/unix.c, src/unix/unix_internal.h, src/virtio/virtio_balloon.c, src/virtio/virtio_net.c, src/vmware/pvscsi.c, src/vmware/vmxnet3_net.c, test/unit/objcache_test.c
In the pagecache code, allocating 4KB pages directly from the linear backed heap creates excessive fragmentation, which in
low-memory conditions may cause other allocations in the kernel (which typically use objcaches with a 2MB page size) to fail even when pagecache drain requests are fully executed.
This changeset addresses the fragmentation issue by changing the pagecache code to use an objcache (with a 2MB page size, and with the linear backed heap as parent heap) as page heap; this allows a pagecache drain to release memory in large chunks that are then available for other allocation requests throughout the kernel.
As part of this changeset, a generic memory cleaner interface is being implemented, which allows various parts of the kernel to register a closure to be invoked to release …
=> Pagecache: use an objcache as page heap

.circleci/config.yml
The currently used Xcode version 12.2.0 is no longer supported by CircleCI, which prevents building the nightly releases for MacOS. This change updates the XCode version to the latest supported version 14.0.0.
In addition, the Google Cloud SDK version is being updated, since the currently used version does not install correctly on Xcode 14.0.0.
=> CircleCI Mac build: update Xcode version

src/kernel/storage.c, src/tfs/tfs.c, src/tfs/tfs.h, src/tfs/tfs_internal.h, src/unix/filesystem.c, src/unix/syscall.c, src/unix/system_structs.h, src/unix/unix.h, src/virtio/virtio_scsi.c, src/virtio/virtio_storage.c, test/runtime/symlink.c, test/runtime/write.c
The first commit changes the implementation of fsync and fdatasync to avoid flushing the TFS log when not needed. The filesystem_sync() function has been removed in favor of using filesystem_flush(), because there was duplicated code between these functions, and each filesystem_sync() call was triggering two calls to pagecache_sync_volume(). Similarly, filesystem_sync_node() (which was triggering an unnecessary call to pagecache_sync_volume) is being replaced by fsfile_flush(). In order to ensure that the completion of an fync/fdatasync syscall runs in the appropriate syscall context, calls to apply() have been replaced by calls to async_apply_status_handler() in the TFS code and the storage drivers that implement the flush operation.
The second commit adds support for the O_SYNC and …
=> Syscalls: improve support for file data and metadata synchronization to the storage device

src/aarch64/interrupt.c, src/kernel/kernel.c, src/kernel/kernel.h, src/kernel/schedule.c, src/riscv64/interrupt.c, src/runtime/pqueue.c, src/runtime/pqueue.h, src/unix/thread.c, src/unix/unix.c, src/unix/unix_internal.h, src/x86_64/interrupt.c, test/runtime/thread_test.c
This change introduces a new scheduling algorithm that assigns CPU resources to a task based on how much CPU time the task used in the past. It uses a priority queue where tasks are ordered based on their CPU time: when a task is enqueued, it is positioned according to the time it has been running since it was last scheduled; when a task is dequeued, its CPU time is subtracted from the CPU time of any other tasks in the queue, so that their priority in the queue is increased; this is implemented by storing a reference CPU time in the queue (min_runtime struct member), which prevents long-running tasks from being starved by newly created tasks.
This algorithm is applied for scheduling user threads, so that CPU time is distributed fairly between all runnable threads.
The first commit is a …
=> Scheduler: implement fair scheduling between user threads

src/net/lwipopts.h, src/net/netsyscall.c, src/virtio/virtio_internal.h, src/virtio/virtio_net.c, src/virtio/virtqueue.c, test/runtime/netsock.manifest
This change set improves performance of network transfers over the virtio-net network interface. As an example, the Warp (https://github.com/minio/warp) mixed benchamrk (run with `./warp mixed --autoterm --objects 40 --duration 1m`) against a minIO server showed a change in results from `Cluster Total: 59.45 MiB/s, 9.88 obj/s over 53s` to `Cluster Total: 83.11 MiB/s, 13.88 obj/s over 50s`.
The first commit increases the TCP send buffer size and TCP window size (since lwIP implements TCP window scaling, the window size is not limited to a maximum of 65535).
The second commit adds support for the VIRTIO_F_RING_EVENT_IDX feature, which allows a virtIO driver to indicate to the device when it wants to be notified of an update to used buffers, and similarly allows a virtIO device to indicate …
=> virtio-net performance improvements

.gdbinit-riscv64, platform/riscv-virt/Makefile, platform/riscv-virt/kernel_platform.h, platform/riscv-virt/sbi_ecall_interface.h, platform/riscv-virt/service.c, src/kernel/kernel.h, src/kernel/mutex.c, src/kernel/page.c, src/kernel/page.h, src/kernel/schedule.c, src/riscv64/clock.c, src/riscv64/crt0.S, src/riscv64/interrupt.c, src/riscv64/kernel_machine.c, src/riscv64/kernel_machine.h, src/riscv64/machine.h, src/riscv64/page.c, src/riscv64/page_machine.h, src/riscv64/plic.c, src/riscv64/plic.h, src/runtime/symbol.c, src/runtime/timer.h, src/unix/mmap.c, src/virtio/virtio_rng.c
This introduces SMP support for the riscv-virt platform. The first two commits correct a bug in mutex_lock() and remove the symbol code's dependence on random_u64() (and thus the chacha mutex), respectively.
=> SMP support for RISC-V

src/virtio/scsi.h, src/virtio/virtio_scsi.c
A virtio SCSI disk may have a limit on the number of blocks that can be requested in a single I/O transfer; the value of this limit can be found in the block limits Vital Product Data (VPD) page.
This change adds retrieval of the maximum transfer length for a SCSI disk when the disk is probed, and ensures that this limit is not exceeded when executing STORAGE_OP_READSG and STORAGE_OP_WRITESG requests.
This fixes booting in GCP, where the boot disk has a maximum transfer length of 512 blocks (256 KB), which is less than the size of a TFS log extension.
=> virtio_scsi: honor maximum transfer length limit

src/kernel/pagecache.c, src/tfs/tfs.c, src/tfs/tfs.h
This change set aims at minimizing the number of I/O requests and scatter-gather buffers used to transfer a given amount of data to/from disk, which helps parallelizing I/O (especially when the I/O ring queue depth is limited) and minimizes the memory allocation needs for an I/O transfer.
The first commit implements merging of contiguous pagecache pages that have their backing memory areas adjacent (which happens frequently if the cache for a node is filled sequentially starting from offset 0) into a single scatter-gather buffer before doing a filesystem storage operation (both when reading and writing a page cache node).
The second commit implements extension of existing file extents to cover additional storage space beyond the initially allocated space, and removes the 1MB maximum …
=> Disk I/O optimization

klib/radar.c, src/kernel/init.c, src/kernel/kernel.h, src/kernel/log.c, src/kernel/log.h, src/kernel/stage3.c, src/net/net.c, src/unix/exec.c, src/unix/syscall.c, src/unix/thread.c, src/unix/unix.c, src/unix/unix_internal.h
This change set adds support for specifying trace flags (i.e. a comma-delimited set of trace message types) in the "trace" symbol of the root tuple. A given trace message is output only if its message type is enabled in the trace flags. For backward
compatibility, any unknown trace flag results in the TRACE_OTHER bit being set, i.e. it enables all messages output via calls to thread_log(). Page-fault-related messages and messages output when returning to user threads are now classified in their own categories ("pf" and "threadrun", respectively), i.e. they need to be explicitly enabled in the trace flags.
If "all" is specified in the trace flags, all tracing messages are enabled.
Example: a "trace:pf,other" value in the manifest enables page-fault-related messages and messages classified …
=> Tracing: add support for selectively enabling trace message types

Makefile, doc/tracelog.txt, platform/pc/Makefile, platform/riscv-virt/Makefile, platform/virt/Makefile, rules.mk, src/kernel/tracelog.c, tools/mkfs.c
This adds an option to the tracelog facility for recording trace entries to a file on the root partition. If a 'file' attribute is found in the tracelog manifest tuple, a file with the name of the corresponding value is created in the root directory and file tracing is enabled. For ease of debugging, this attribute may be added to the manifest at build time by using the TRACELOG_FILE build option, e.g.:
$ make TARGET=hw TRACE=tracelog DEBUG=sched TRACELOG_FILE=foo run
The trace data from execution will be left in the file named 'foo' in the root disk image. The tracelog file may be copied out of the image using the 'copylog' make target, which will leave a copy of the file in the output directory.
Note that enabling the file writer will start a periodic timer to collate and flush trace …
=> tracelog file writer

src/kernel/pagecache.c
If pagecache_commit_dirty_node() is called on a node whose `dirty` rangemap is empty and when no committing is ongoing, it is incorrectly setting the `committing` flag to true. This prevents any future calls to this function on a given node from invoking their completion closure, which may cause syscalls such as fsync and fdatasync to fail to return to userspace.
This cange fixes the above issue (introduced by commit 68a8a3ca75ae0d7c5eead414dca2de994c6c4d30).
=> pagecache_commit_dirty_node(): fix setting of `committing` flag

src/kernel/pagecache.c
When the pagecache fetches a range and builds up an sg list, if it encounters an already-filled page then it will submit the existing sg_list and use a new sg_list for the rest of the range that is not filled. If sgb is not also reset to 0 then a pointer to the earlier submitted sg_list could be used instead.
=> pagecache_node_fetch_internal: reset sgb to 0 when submitting early

src/net/net.c
Several klibs (cloud_init, cloudwatch, ntp, radar, syslog) may need to resolve host names. If DHCP is not being used (such as when network interfaces are statically configured), no DNS server is configured in lwIP, which prevents dns_gethostbyname() from working.
This change sets a default DNS server when initializing network interfaces, so that host names can be resolved even if DNS servers are not configured via DHCP.
=> init_network_iface(): set default DNS server

src/kernel/schedule.c, src/runtime/timer.c, src/runtime/timer.h
The timerqueue is used mainly for tracking timers in the kernel, which checks the next_expiry field to determine when to set the machine timer. There is, however, ambiguity in checking that field when the expiry timestamp is in the past and the timerqueue is not updated. This could mean either the timerqueue was serviced and there are no more timers in the queue and thus the next_expiry field is stale since it is not updated when there are no timers, or it can mean that the timer has fired and queued the timer service routine but it has not been executed or is executing on a different cpu. This ambiguity creates a bug when the timer interrupt hasn't run yet but the next_expiry is in the past and the scheduler assumes it is empty and resets the timer interrupt to fire much later, …
=> Improve handling of empty timerqueues

src/kernel/kernel.c, src/kernel/klib.c, src/kernel/klib.h
When analyzing backtraces it can be useful to know if and where any klibs are loaded. This change adds a new call to print out a list of the loaded klib information including name, load address, and load size. This print will occur when frame_trace is called since it can be useful to know when looking at frame trace addresses and ensures it is printed out for common failures like panics or assertion failures.
=> Print out list of loaded klibs on panic or assert fail

src/runtime/clock.h
The now() function asserted that the frequency-adjusted timestamp is newer than the last_raw value as a guarantee that time does not go backwards. This change modifies the check to only assert the unmodified timestamp is greater or equal to the last_raw value and instead modifies the frequency-adjusted timestamp to last_raw if the calculation results in a older timestamp.
=> Update frequency adjust check in now()

src/kernel/schedule.c, src/runtime/timer.c, src/runtime/timer.h, src/unix/thread.c, src/unix/timer.c, src/unix/unix.c, src/unix/unix_internal.h, test/runtime/time.c
This changeset adds support for CLOCK_PROCESS_CPUTIME_ID and CLOCK_THREAD_CPUTIME_ID to the Unix timers created via the timer_create syscall; in addition, ITIMER_PROF is now supported by the getitimer and setitimer syscalls.
The timerqueue code has been enhanced so that it can be used with clock types (such as process and thread CPU time) that are not derived from the monotonic system clock. The Unix process struct now has its own timerqueue, which handles timers that track the total CPU time spent by a process. Analogously, the thread struct has a timerqueue that handles timers tracking CPU time spent by a single thread (the thread timerqueue is only instantiated if/when a timer that requires it is created).
The Unix timer code uses the appropriate timerqueue based on the type of clock …
=> Unix timers: add support for process and thread CPU time

platform/pc/Makefile, platform/virt/Makefile, src/aarch64/elf64.c, src/aarch64/gdb_machine.h, src/aarch64/kernel_machine.h, src/gdb/gdbstub.c, src/kernel/elf.c, src/kernel/elf64.h, src/kernel/ltrace.c, src/kernel/ltrace.h, src/riscv64/elf64.c, src/riscv64/gdb_machine.h, src/riscv64/kernel_machine.h, src/unix/exec.c, src/unix/signal.c, src/unix/unix.c, src/x86_64/elf64.c, src/x86_64/gdb_machine.h, src/x86_64/kernel_machine.h
This feature allows tracing calls made by the application binary to dynamic library functions. It is enabled by adding an 'ltrace' attribute to the root tuple, and prints on the serial console (similarly to the Linux ltrace tool) a line for each dynamic library function call (with the function name) and for each signal delivered to the process (with the signal number).
This feature is implemented for the x86 and aarch64 architectures (in riscv, CPU debug registers cannot be accessed from supervisor mode, and the SBI does not currently have the functionality to access debug registers via SBI calls).
The new functions elf_dyn_parse() and elf_plt_get() have been added to the generic ELF code and are used by ltrace to retrieve the information needed to be able to place software breakpoints …
=> Add ltrace functionality

src/net/netsyscall.c, src/unix/socket.c, src/unix/system_structs.h, test/runtime/netsock.c, test/runtime/unixsocket.c
This PR fixes several small issues related to sockets. First, it implements the getsockopt syscall for unix sockets,
which was previously not supported, however it only implements SO_TYPE. Second, it adds support for the
SO_PROTOCOL option for inet and inet6 sockets as well as adds some input checking for type and protocol when
creating sockets in these domains. Finally, it fixes an issue with udp sockets where calling shutdown on a udp
socket would not wake any blocked waiters on receive.
=> Unix socket and getsockopt improvements

src/net/netsyscall.c, test/runtime/netsock.c
These options are accepted when the `level` argument is SOL_TCP.
TCP_MAXSEG indicates the maximum segment size of a TCP connection.
TCP_FASTOPEN indicates the maximum number of pending TCP Fast Open (TFO) requests a listening socket allows before disabling TFO (the kernel currently does not support TFO, thus the returned value is always zero).
Closes https://github.com/nanovms/nanos/issues/1797.
=> netsock_getsockopt(): add support for TCP_MAXSEG and TCP_FASTOPEN

src/unix/syscall.c, test/runtime/symlink.c
When a file is opened, the fsf member of the file structure should be properly set to NULL for non-regular files; with this fix, fsync(2) works properly when invoked on a file descriptor corresponding to a directory, and read/write (and similar) syscalls properly return an error code when invoked on file descriptors corresponding to non-regular files.
=> File syscalls: initialize fsfile pointer and check for null value

src/unix/syscall.c, test/runtime/sendfile.c
When sendfile() is called on an output file descriptor corresponding to a regular file, it should write at the current file offset and update the offset according to the number of bytes written. The existing code is writing at offset zero and is not updating the offset.
This change fixes the above issue and amends the sendfile runtime test so that it would have failed without this fix.
=> sendfile(2): change file offset on output file

klib/cloud_init.c, klib/syslog.c, src/kernel/storage.c, src/tfs/tfs.c, src/tfs/tfs.h, src/unix/coredump.c, src/unix/filesystem.c, src/unix/filesystem.h, src/unix/inotify.c, src/unix/special.c, src/unix/syscall.c, test/runtime/write.c, tools/tfs-fuse.c
When this flag is specified in an open() or openat() syscall, if the file being opened already exists and is a regular file it is truncated to length 0.
To implement this feature, the filesystem_get_node() function has been amended to take an additional 'truncate' boolean argument; the fsfile_open_or_create() function (which calls filesystem_get_node) has also been amended to take an additional 'truncate' argument, and this allowed to remove calls to fsfile_truncate() in a few places.
Closes #1803.
=> open(2): add support for O_TRUNC flag

klib/cloud_init.c
resolves https://github.com/nanovms/nanos/issues/1806
---
---
- _Example_: adding `"auth": "Basic dXNlcjpwYXNzd2Q="` to **cloud_init.download** config
```json
"ManifestPassthrough": {
"cloud_init": {
"download": [
{
"src": "https://httpbin.org/hidden-basic-auth/user/passwd",
"dest": "/test.txt",
"overwrite": "t",
"auth": "Basic dXNlcjpwYXNzd2Q="
}
]
}
}
```
will result in `Authorization` header being added to the request
```ini
Authorization: Basic dXNlcjpwYXNzd2Q=
```
=> feat(klib): cloud_init - simple authorization support

src/runtime/clock.h
The vdso last_raw gets updated periodically, and if it were updated on one processor while another is running now(), there can be a race condition where the now() cpu fetches monotonic time, then the other cpu updates last_raw with a slightly later monotonic time, then the now() cpu fetches the saved last_raw but then fails the assertion check comparing the two timestamps.
This change fixes the problem by reading the last_raw value before fetching the current monotonic time.
=> Fix last_raw update race condition

klib/Makefile, klib/gcp.c, klib/mbedtls.c
This change set adds a klib implementing a console driver that sends console output to GCP logs.
Instance-specific information that needs to be known in order to interface with the GCP logging API is retrieved from the instance metadata server, which is reachable at address 169.254.169.254.
GCP logging is enabled by loading the gcp and tls klibs and adding to the root tuple a "gcp" tuple that contains a "logging" tuple.
The "logging" tuple may optionally contain a "log_id" attribute that specifies the [LOG_ID] string that is sent in the "logName" parameter (which is formatted as "projects/[PROJECT_ID]/logs/[LOG_ID]") associated to GCP log entries; if not present, the log ID is derived from the instance hostname as retrieved from the metadata server.
In order for the GCP klib to retrieve …
=> Klibs: add new library implementing GCP logging

src/tfs/tfs.c
When filesystem_check_or_reserve_extent() is called to reserve storage space before writing to a file, it can create new extents so that the needed storage space is marked as allocated. The initial file data associated to the new extents is zero and is not stored in the storage medium; for this reason, the extents should be marked as "uninited", so that any subsequent reads from these extents (for example during a RMW when writing a portion of a page cache node) return a zeroed block of data instead of retrieving the data from the storage medium.
This change fixes the above issue by modifying the fill_gap() function so that it creates "uninited" extents when there is no file data to be written to the storage medium; the issue has been discovered when running a modified "write" runtime …
=> TFS fill_gap(): fix extent initialization when reserving storage

src/kernel/stage3.c, src/net/net.c, src/net/net.h, src/net/netsyscall.c, src/unix/system_structs.h
Some user programs assume the network is ready to go when executing, but
if dhcp takes a long time then the user program may hit network errors
if an address and gateway isn't acquired yet. This change adds a new manifest
option 'exec_wait_for_ip4_secs', which will delay running the user program
until either an ip4 address is acquired or the timeout specified in the option
has elapsed. If a static address is set then the program is executed immediately.
Additionally, the translation of lwip to errno codes has been updated to more
accurately reflect the nature of the lwip errors.
=> Add option to run user program after getting ip4 address

test/go/go_test.go
The `Imagename` field has been renamed to `ImageName`.
=> Go runtime tests: update RunConfig struct field names

klib/aws.c, klib/cloud_init.c, klib/cloudwatch.c, klib/gcp.c, klib/ntp.c, klib/radar.c, klib/syslog.c, klib/tun.c, src/aws/ena/ena.c, src/aws/ena/ena_datapath.c, src/drivers/gve.c, src/drivers/netconsole.c, src/gdb/gdbtcp.c, src/hyperv/netvsc/netvsc.c, src/net/direct.c, src/net/lwip.h, src/net/lwipopts.h, src/net/net.c, src/net/netsyscall.c, src/unix/netlink.c, src/unix/syscall.c, src/virtio/virtio_net.c, src/vmware/vmxnet3_net.c, src/xen/xennet.c
This change set removes the global lwIP lock and adapts the networking code to the lwIP changes that allow concurrent invocation of lwIP raw API functions. The lwIP lightweight protection implementation (which does not provide protection from concurrent access in multi-core systems) is being disabled, and locking primitives (as well as atomic operations needed for reference counting) are being defined.
A spinlock is now used to protect the lwIP heap.
lwIP functions that inolve a tcp_pcb structure are now called with the PCB lock held (by calling `tcp_lock` and `tcp_unlock`).
tcp_ref() and tcp_unref() are used to properly reference-count tcp_pcb structures used in net/netsyscall.c and net/direct.c.
In net/netsyscall.c, the file descriptor lock is used (instead of the global lwIP lock) to …
=> lwIP: implement multithreaded operation

.circleci/config.yml
In the CircleCI Mac container, Python is not installed by default, thus the `brew upgrade python` command fails with "Error: python not installed".
This change removes the above command, which is not needed because the Google Cloud client installer (which is run in the following steps) automatically installs Python 3.7 (and would use this Python installation even if another Python version was already installed).
=> CircleCI: nightly-build-mac: remove `brew upgrade python` command

platform/pc/boot/stage2.c, src/drivers/ata-pci.c, src/drivers/ata.c, src/drivers/ata.h
In an ATA disk, the maximum number of sectors that can be submitted in a single I/O request depends on whether LBA48 addressing is supported. This change amends both the x86_64 bootloader and the kernel ATA PCI driver to split I/O requests sent to the ATA driver so that each request doesn't exceed the limit.
This fixes booting on vsphere VMs with IDE disk emulation.
=> ATA: honor maximum number of sectors in each I/O request

src/unix/futex.c
In get_robust_list, thread_from_tid is called if pid != 0, yet thread_release is called unconditionally, resulting in an incorrect thread reference count. This conditionalizes the release, as well as a check only necessary after the call to thread_from_tid, on pid != 0.
=> get_robust_list: fix misuse of thread_release

src/unix/syscall.c
A call to sched_getaffinity with a cpusetsize that would result in an -EINVAL returned could mistakenly hold a thread reference. This moves the check for cpusetsize in advance of the call to lookup_thread.
=> sched_getaffinity: check cpusetsize prior to calling lookup_thread

src/http/http.c, src/http/http.h, src/kernel/lockstats.c, src/runtime/buffer.h, src/unix/ftrace.c, src/unix_process/socket_user.c, src/unix_process/socket_user.h, test/runtime/web.c, test/unit/buffer_test.c, test/unit/network_test.c
This PR makes several improvements for web.c performance and compatibility by
updating web.c to use the http listener for better http support and then updating
the http.c code to support proper connection persistence based on the http
version of the request. The http response fuctions now take an http_responder pointer
that keeps track of whether or not to close the connection after the response and
automatically adds an appropriate connection header if necessary. These changes
allow apache-bench to work web.c, where previously it was timing out.
Also, the user socket code has been updated to set TCP_NODELAY after accepting
a connection. This drastically improves performance in web.c, particularly in a bridged
network situation, where the client's acks would take 20-40ms causing …
=> Http and user socket improvements

klib/cloud_init.c, src/runtime/files.mk, src/runtime/json.c, src/runtime/runtime.h, test/unit/parser_test.c
This change adds to the cloud_init klib support for populating the environment of the user process with variables whose name and value are retrieved from an HTTP(S) server during startup.
The configuration syntax in the manifest to use this functionality is as in the following example:
```
download_env:[
(
src: "http://10.0.2.2:8200/v1/secret/data/hello"
auth: "Bearer hvs.6v6yY5yZf32uZzaa7HhiX6AZ"
path: "attr1/attr2"
)
]
```
The `download_env` attribute is an array where each element specifies a download source URL, an optional authentication header, and an optional attribute path.
For each element in the `download_env` attribute, the klib executes an HTTP request to the specified URL, and if the peer responds successfully, the response body is parsed as a JSON object, and from this …
=> Klibs: cloud_init: add support for environment variables

klib/Makefile, klib/firewall.c, src/net/lwip.h, src/net/lwipopts.h, src/net/net.c
This changeset adds a new klib that implements a network firewall. The firewall can drop IP packets received from any network interface, based on a set of rules defined in the manifest. Each rule is specified as a tuple located in the `rules` array of the `firewall` tuple in the manifest. Valid attributes for a firewall rule are the following:
- `ip`: matches IPv4 packets, and is a tuple that can have the following attributes:
- `src`: matches packets based on the source IP address, which is specified with the standard dotted notation aaa.bbb.ccc.ddd, can be prefixed by an optional `!` character which makes the rule match packets with an address different from the provided value, and can be suffixed with an optional netmask (with format `/<n>`, where `<n>` can have a value from 1 to 32) …
=> Klibs: add firewall klib

src/kernel/stage3.c, src/unix/exec.c, src/unix/unix.c, src/unix/unix.h, src/unix/unix_internal.h, test/runtime/write.manifest
With this change, the user application by default is not allowed to overwrite the program (and interpreter, if present) binary file.
This default behavior can be overridden by inserting a "program_overwrite" attribute in the root tuple of the manifest.
In the write runtime test, the "exec_protection" flag has been removed in order to test that the executable file by default cannot be overwritten even without exec protection.
File access permissions are implemented in a generic way so that it is possible to mark an arbitrary file as read-only by inserting a "readonly" attribute in the file tuple in the manifest.
In addition, when exec protection is enabled (which protects the program file from overwriting, independently of this new feature), the kernel disallows overwriting of the …
=> Disallow overwriting of program and interpreter files by default

src/tfs/tfs.c, src/unix/filesystem.c, src/unix/filesystem.h, src/unix/syscall.c
With this policy, when a file is accessed, the file access time is updated only if its current value is less than or equal to the file modification time (or if it is more than 1 day old). This is the default behavior on Linux, and makes file reads more efficient by avoiding frequent file metadata updates.
In addition, the file access time update is being removed from the filesystem_get_node() function, because the access time should be updated only when file contents are accessed (or, in the case of directories, when directory contents are listed).
=> Unix: implement RELATIME (relaxed update of file access time)

src/vmware/vmxnet3_net.c, src/vmware/vmxnet3_queue.c
The memory allocated for the rx queue completion ring was half the size required for the number of completion descriptors as set in the comp_ring_len field of the vmxnet3_rxq_shared struct. This was causing memory corruption as the vmxnet3 device would write past the memory range allocated for the completion ring.
In addition, this change set fixes the assert() statement in vmxnet3_receive() to check the rx queue ID.
Closes https://github.com/nanovms/ops/issues/1454
=> vmxnet3: fix allocation size for rx queue completion descriptors

src/vmware/vmxnet3_net.c
If the LRO feature is enabled, when the vmwnet3 device coalesces multiple input TCP packets into a single packet, it does not update the checksum in the TCP header of the large packet (because it can indicate that all the checksums are correct by setting the appropriate fields in the completion descriptor); therefore, when the packet is processed by the lwIP TCP stack, the checksum calculation fails, and the packet is discarded. This causes a high performance penalty, since the application needs to wait for the discarded packet to be re-transmitted by the remote peer. On the other hand, checksum calculation by lwIP should be kept enabled because lwIP does not support disabling the calculation on a per-packet basis, and it is not possible for the driver to know beforehand whether the …
=> vmxnet3: disable Large Receive Offload (LRO) feature

src/aarch64/kernel_machine.h, src/aarch64/page.c
Frameworks such as Node.js expect to be able to retrieve CPU cache characteristics such as cache line sizes, and execute cache maintenance operations (e.g. flushing the instruction cache). This change modifies the settings of the SCTLR_EL1 register so that cache access instructions from the user program do not generate exceptions.
=> Aarch64: enable CPU cache operation from user program

src/aarch64/page.c
With the implementation of new MMU features such as LPA and LPA2, the `Tgran4` field of the ID_AA64MMFR0_EL1 register can have a non-zero value and still indicate that the 4KB memory translation granule size is supported (e.g. a value of 1 indicates that this granule size is supported with 52-bit addresses). The only value of this field that indicates lack of support for 4KB granule size is 15.
This change fixes the init_mmu() function so that it works when running on Aarch64 machines that implement the LPA2 feature, such as the "virt" machine on Qemu version 8 and later with the `-cpu max` command line option.
=> Aarch64: init_mmu(): fix check for support of 4KB granule size

src/x86_64/crt0.s
The pvh_start32 assembly code is a 32-bit entry point for the kernel, used by hypervisors such as QEMU (with the microvm machine type) and cloud-hypervisor (https://github.com/cloud-hypervisor/cloud-hypervisor). The current code was missing the initialization of the stack, which prevents the kernel from booting under cloud-hypervisor.
This change adds the code to set the stack pointer register and to map the memory area to be used as initial stack during boot; this allows booting under cloud-hypervisor.
Closes #1838.
=> X86_64: PVH entry point: add stack memory configuration

src/aarch64/page.c, src/kernel/page.c, src/kernel/page.h
When a new mapping is set up via the map() function, the page table spinlock is acquired in order to protect the page tables from concurrent access. On aarch64, spinlock operations are implemented by using the Load-Exclusive/Store-Exclusive mechanism; the Arm architecture reference manual (version H.a, section B2.9.2 "Exclusive access instructions and Shareable memory locations") says that support for this mechanism when address translation is disabled is not an architectural requirement, and architecturally compliant software must not rely on using it.
The init_mmu() function sets up some mappings before enabling the MMU (i.e. when address translation is disabled); in order for this code to run on machines where exclusive access instructions don't work without address translation (such …
=> Aarch64 init_mmu(): call a non-locking version of map()

src/aarch64/vdso.lds, src/riscv64/vdso.lds
The vvar_page location in the VDSO linker script follows the .text section, after a 4KB alignment. However, the kernel maps the vvar page after the entire vdso.so ELF file contents, which means that in order for the user program to correctly access the VDSO variables (e.g. vdso_dat), the end of the .text section must be within the last 4 KB of the VDSO ELF file.
The above constraint is not being satisfied in the RISC-V CI builds, which causes VDSO functions that access VDSO variables to behave incorrectly.
This change adds the declaration of a few more sections for the text PT_LOAD segment in the VDSO linker script for aarch64 and risc-v, so that these sections are placed before the .text section, which is then placed at the end of the PT_LOAD segment; this decreases the likelihood of the …
=> VDSO linker script: move .text section to end of PT_LOAD segment

src/net/netsyscall.c
This allows all data submitted by the program via a writev() syscall to be sent at once (instead of in as many chunks as the number of iovec entries) to the network stack, which improves efficiency, especially when using TCP sockets with the TCP_NODELAY option enabled (which would otherwise cause a TCP packet to be sent for each iovec entry).
=> Network sockets: implement sg_write closure

platform/pc/service.c, src/drivers/acpi.h, src/kernel/region.h, src/tfs/tlog.c, src/vmware/vmxnet3_net.c, src/x86_64/acpi.c, src/x86_64/crt0.s, src/x86_64/uefi.c
This change set allows Nanos to run on ESXi instances configured to boot via UEFI instead of BIOS. Tested on ESXi v7.0.
Note: the VGA console does not work on UEFI instances, because the video device, although being VGA-compatible, is not configured in text mode by the UEFI firmware, and the the kernel VGA console driver supports text mode only. The serial console continues to work as before.
Credits go to @sanderssj for the GDT- and ACPI-related changes.
=> ESXi: add support for booting via UEFI

Makefile, klib/Makefile, klib/pledge.c, klib/sandbox.c, klib/sandbox.h, klib/unveil.c, platform/riscv-virt/Makefile, platform/virt/Makefile, rules.mk, src/net/net_system_structs.h, src/net/netsyscall.c, src/unix/socket.c, src/unix/socket.h, src/unix/syscall.c, src/unix/system_structs.h, src/unix/unix.c, src/unix/unix_internal.h, test/runtime/Makefile, test/runtime/sandbox.c, test/runtime/sandbox.manifest
This klib implements a sandboxing mechanism by which the capabilities of the running process can be restricted by overriding certain syscall handlers. The current implementation supports the OpenBSD pledge (https://man.openbsd.org/pledge.2) and unveil (https://man.openbsd.org/unveil.2) syscalls.
A pledge invocation forces the process into a restricted-service operating mode by limiting the set of syscalls (and in some cases the allowed values of syscall arguments) that can be invoked.
Syscalls that are present in both Nanos and OpenBSD are handled by following the pledge implementation in OpenBSD, except for syscalls that are not applicable to unikernels (e.g. those related to inter-process communication). Syscalls that are present (or could be implemented in the future) in Nanos but not …
=> Klibs: add sandbox klib

src/tfs/tfs.c
When a request to create an extent of a certain size cannot be fulfilled due to missing free contiguous storage space, and the extent is created with a smaller size than requested, the existing code is assigning the originally requested file range (instead of the range actually allocated) to the extent being created, which leads to filesystem corruption.
Regression introduced in commit 65434ad7 (#1765).
=> TFS create_extent(): fix assignment of file range

src/hyperv/netvsc/netvsc.c
The maximum payload length for a struct pbuf allocated when receiving a packet in the netvsc driver is given by the `rxbuflen` field of the hn_softc_t struct, without adding sizeof(struct xpbuf).
=> HyperV netvsc_m_append(): fix setup of pbuf length

.circleci/config.yml
In the build-virt CircleCI job, after a successful run of the test suite, build artifacts should be uploaded to Google Cloud only if the GCLOUD_SERVICE_KEY environment variable is set, otherwise the job fails when triggered by pull requests from forked repositories.
=> CircleCI build-virt: fix job failure when triggered from forks

platform/pc/linker_script
The PT_GNU_STACK header in the pc linker script is unused and benign, but its presence may cause confusion. This removes it.
=> remove unused GNU_STACK ELF program header

src/net/netsyscall.c, src/runtime/closure.h, src/unix/eventfd.c, src/unix/inotify.c, src/unix/io_uring.c, src/unix/socket.c, src/unix/unix_internal.h, test/runtime/netsock.c
This change set fixes memory leaks occurring when some types of file descriptors (network and Unix domain sockets and eventfd) are closed and when network packets are sent on a TCP socket.
New macros have been defined to allow attaching different functions to different instantiations of a closure, and some heap-allocated closures have been converted to closures (declared is in unix_internal.h but instantiated with file descriptor-specific functions) embedded in other structs.
=> Sockets/eventfd: fix memory leaks

src/aarch64/clock.c, src/hyperv/vmbus/hyperv.c, src/kernel/clock.c, src/kernel/kvm_platform.c, src/kernel/pvclock.c, src/kernel/pvclock.h, src/riscv64/clock.c, src/runtime/clock.h, src/x86_64/clock.c, src/x86_64/hpet.c, src/x86_64/rtc.c, src/xen/xen.c
Nanos can run on platforms where the RTC peripheral is read-only (e.g. riscv-virt), is not initialized with the system time from the host (e.g. cloud-hypervisor), or is not available at all (e.g. AWS Firecracker). This change set allows the system time to be retrieved during boot from an alternative source (e.g. the wall clock time made available by the paravirtualized clock), and allows changing the system time even when the RTC peripheral is unavailable (in this case, the time update will not persist across a VM reset).
The register_platform_clock_now() function now takes an additional parameter with the value of the offset between the system time and the monotonic time: if such offset is available (i.e. non-zero), it is used to initialize the rtc_offset field of the VDSO structure, …
=> Real-time clock: add support for running without an RTC peripheral

src/kernel/pagecache.c
This function is called by pagecache_sync_volume(), which is used to commit all dirty pages to disk before shutting down the kernel. If there are no pages to be committed, the completion is invoked immediately; when shutting down the kernel, this completion is the filesystem sync_handler closure, which needs to lock the filesystem; since the filesystem lock is now a mutex, it cannot be acquired in interrupt context, therefore the completion has to be run asynchronously; this prevents errors like "assertion !frame_is_full(ctx->frame) failed at /usr/src/nanos/src/kernel/mutex.c:109  in mutex_lock_internal()" when a kernel shutdown is triggered in interrupt context, such as if an assert failure happens in interrupt context, or if a VM instance is stopped via ACPI.
Closes #1874.
=> pagecache_finish_pending_writes(): apply completion asynchronously

src/unix/netlink.c
This changes the behavior of nl_rtm_getaddr6() to iterate through all IPv6 addresses on an interface and enqueue an RTM_NEWADDR entry for each valid one.
=> RTM_GETADDR: report multiple ipv6 addresses

src/net/netsyscall.c
This change fixes a regression introduced in 0e67b81ef8406d15d5eec0f6eafdda95d0f9cba8, which causes tcp_unref() to be called with an uninitialized argument if the `out_unlock` goto target is reached.
=> socket_write_tcp_bh(): fix use of uninitialized variable tcp_lw

src/fs/tfs.c
A directory entry corresponds to an attribute in the `children` tuple of the directory tuple, not in the directory tuple itself. This change fixes an error that causes a filesystem corruption when a file is renamed (this corruption is only detected after a reboot).
Regression introduced in a4afaa317f88e1406432f5dc691fb6b9e448b025
=> tfs_rename(): fix writing of metadata to TFS log

src/config.h, src/drivers/acpi.c, src/hyperv/utilities/vmbus_shutdown.c, src/unix/signal.c, src/unix/unix.c, src/unix/unix.h, src/xen/xen.c, src/xen/xen_internal.h
When an external shutdown notification is received, such as the acpi poweroff event, nanos
should signal the user program to exit before shutting down to allow it time to quiesce. This
PR implements this with a new unix_shutdown() function that sends a SIGTERM to the user
process. Programs that handle SIGTERM can perform shutdown tasks for up to 
UNIX_SHUTDOWN_TIMEOUT_SECS seconds, and programs without a SIGTERM handler will
be shut down immediately. The kernel_shutdown() is called when the user program exits or
when the timer expires.
Support has also been added to Xen for receiving shutdown notifications so the unix_shutdown
can be performed there as well.
=> Signal user program when receiving shutdown notification

klib/mbedtls.c, platform/pc/service.c, platform/riscv-virt/service.c, platform/virt/service.c, rules.mk, src/config.h, src/kernel/init.c, src/kernel/kernel.h, src/kernel/pagecache.c, src/net/lwip.h, src/net/net.c, src/runtime/heap/mcache.c, src/virtio/virtio_net.c, test/runtime/Makefile
This change reduces baseline memory requirements for various memory caches
under "low memory" conditions. If the function is_low_memory_machine() returns
true, then the following parameters are minimized:
- the pagecache will use PAGECACHE_LOWMEM_CONTIGUOUS_PAGESIZE (default 128KB)
as its objcache pagesize instead of PAGESIZE_2M
- the mcache high order is lowered to 11 (2KB), thus forcing PAGESIZE or
larger allocations to be made directly from the backing heap - and thus not
cached, nor available for situations that implement a malloc/free interface
- similiarly, allocations for lwIP are limited to a maximum size of 2KB
In addition:
- the runtime tests are stripped by default, saving the unstripped binaries
under the ".dbg" extension
- in virtio-net, the size of the backing page …
=> trim cache parameters for low memory operation

test/runtime/time.c
The time test may fail with a SIGSEGV if clock_gettime() is performed via VDSO with a faulting user address. The same failure occurs when running the test under Linux. To fix this, tests for EFAULT should directly invoke the syscall being tested, avoiding VDSO.
See #1888
=> time test: perform EFAULT tests through syscalls only

.circleci/config.yml, platform/pc/Makefile, src/drivers/netconsole.c, src/runtime/runtime.h, src/unix/signal.c, src/unix/syscall.c, src/unix/unix_internal.h, test/extended_tests.py, test/runtime/Makefile, test/runtime/aslr.c, test/runtime/aslr.manifest
Nanos has a number of behaviors that are only activated when explicitly configured in the manifest. Many of these are informational or related to debugging, so they are not exercised in normal testing. Sometimes major changes in nanos can break these features and without testing coverage the problem goes unnoticed.
This PR creates a python script that performs tests on some of these features, and fixes some bugs that were discovered by doing this testing:
- The syscall_defer option was found to be obsolete and no longer did anything.
- The syscall_summary option was panicking and needed a thread pointer check
- The coredump feature had an assert failure because the failing context's fault handler wasn't cleared while waiting for the coredump to be written out
- The netconsole feature had …
=> Additional tests for optional nanos features

rules.mk
Since the kernel code does not contain any floating point operations, it assumes the FPU is in a "clean" state when creating a context frame for a user thread. However, in the x86 architecture, MMX registers are aliases for the floating point registers, thus execution of any MMX instruction might modify the FPU state.
The gcc 12 compiler generates MMX instructions when compiling the AcpiUtInitGlobals() function in the acpica code; this is causing the FPU to enter a state that results in an invalid operation FPU exception and leads to wrong computation results when the user program executes floating point instructions.
This change adds the `-mno-mmx` flag to the compiler options for x86, so that generation of MMX instructions is avoided.
Closes #1884.
=> x86_64 compiler options: disable use of MMX instructions

src/aarch64/acpi.c, src/drivers/acpi.c, src/drivers/acpi.h, src/x86_64/acpi.c
This PR contains the following ACPI changes:
- GED interrupt handler registration has been fixed on x86_64
- probing of the power button device has been decoupled from probing of the _S5 object
- support for powering down the machine via the Sleep Control Register has been added
These changes allow the kernel to cleanly shut down (via the ACPI power button) a machine running on cloud-hypervisor.
=> ACPI: add support for clean VM shutdown on cloud-hypervisor

src/virtio/virtio_net.c
Commit 3eb8533b introduced a bug whereby large virtio-net queue sizes (e.g. 4096 on gce) would result in an objcache pagesize being greater than the maximum guaranteed alignment of the parent (linear backed) heap. This could result in an assertion failure in the objcache code when allocating a parent page that is not aligned to the objcache pagesize.
While the id heap aligns allocations to the rounded power-of-2 of the allocation size (a property that ought to be parameterized...), the physical id heap ranges themselves are only guaranteed to be aligned to 2M. Thus, allocations from the physical id heap or linear backed heap may also only be aligned up to a size of 2M.
The problem is avoided in this case by capping the objcache pagesize at PAGESIZE_2M when setting up the virtio-net …
=> virtio-net: cap objcache pagesizes at PAGESIZE_2M

klib/cloud_init.c
If no "path" property is found in a "download_env" tuple in the cloud_init klib configuration, the current code is failing to initialize the `attribute_path` field of the cloud_download_env structure, which may cause cloud_download_env_set() to access invalid memory.
=> Klibs: cloud_init: properly initialize attribute_path vector

src/unix/exec.c
In an ELF file, an ET_DYN type value in the ELF header indicates that the file has position-independent code, regardless of whether the file has to be executed directly or through an interpreter; hence, the file can be loaded at an arbitrary address, and the ASLR feature can be used to randomize the load address. This change adds ASLR support to programs built with gcc's `-static-pie` option. In addition, this allows running programs whose load range as derived from the PT_LOAD sections starts at 0 and whose glibc initialization code does mmap() operations on (parts of) the address range where the program has been loaded; for example, the initialization code in the binary release 0.24.0 of miniserve (https://github.com/svenstaro/miniserve) does an mmap() with the MAP_FIXED flag on the …
=> Unix exec_elf(): improve support for static PIE programs

src/fs/tfs.c, src/fs/tfs.h, src/kernel/init.c, tools/mkfs.c
When a TFS metadata tuple is written to the TFS log, if it refers to a directory entry it should be cleaned up (recursively if the entry is a directory itself) by temporarily removing references to parent directories, otherwise the log will contain useless entries. This is not being done in the current code by the tfs_rename() function, which is not doing the cleanup recursively, with the result that renaming a non-empty directory produces spurious TFS log entries. In addition, if a TFS log rebuild is triggered during the first call to log_write_eav() by filesystem_write_eav(), the filesystem_log_rebuild() function fixes up the entire filesystem tree, which may cause the second call to log_write_eav() to attempt a log write of a tuple with a reference to the parent.
This change fixes the …
=> TFS: fix directory cleanup when writing directory entries to log

src/unix/filesystem.h, test/runtime/mkdir.c, test/runtime/rename.c, test/runtime/symlink.c, test/runtime/unlink.c
Filesystem-related syscalls that take a directory file descriptor and a file path should return -ENOTDIR if the supplied file descriptor is an open descriptor but does not correspond to a directory. The current code is assuming that if the file descriptor can be resolved it refers to an open directory; this may cause access to invalid memory addresses if the above assumption does not hold.
This change adds a check for the file descriptor type in the resolve_dir() macro, which returns -ENOTDIR if the check fails. A few runtime tests have been amended with test cases that would cause the kernel to misbehave (e.g. try to access a filesystem struct through an invalid pointer) without this fix.
=> Unix resolve_dir(): fix handling of non-directory dirfd values

src/net/netsyscall.c, src/unix/system_structs.h
This socket option at the SOL_SOCKET level contains the socket domain value (e.g. AF_INET or AF_INET6).
=> getsockopt(): add support for SO_DOMAIN

test/go/Makefile
Running a 'make clean' on a clean tree, or a tree that hasn't executed the test/go tests, may result in an error such as:
go: github.com/nanovms/ops@v0.0.0-20210408190622-0dc76ec84cd2: missing go.sum entry; to add it:
go mod download github.com/nanovms/ops
To avoid this, the post-clean rule now runs 'go mod tidy' prior to 'go clean'.
[I'm not certain if this is the right fix; does anyone know if there's a simpler way to bypass the above error?]
=> test/go: run 'go mod tidy' in post-clean rule

src/unix/exec.c, src/unix/mmap.c, src/unix/syscall.c, src/unix/unix_internal.h
Up to now, Nanos would allocate and map an unnecessarily physically-contiguous
2MB chunk of memory for the userspace stack. This could be wasteful for
low-memory configurations both in terms of allocated but potentially unused
stack space as well as memory fragmentation created by the large, contiguous
allocation. Similarly, extensions of the process heap, made via a call to brk(2), would
also result in physically-contiguous allocations and mappings of the extended area.
With this change, only a single page (PROCESS_STACK_PREALLOC_SIZE) is
allocated for stack usage at first, allowing further stack pages to be faulted
in as needed. A new vmap flag, VMAP_FLAG_STACK, has been added to identify the
stack mapping, a fault on which is handled in the same way as an anonymous
mmap. Following in …
=> Fault in process stack and heap pages

src/http/http.c, src/kernel/pci.c, src/runtime/heap/heap.h, src/runtime/heap/id.c, src/runtime/heap/id.h, src/runtime/heap/reserve.c, src/unix/thread.c
This is a small collection of fixes and a couple of improvements from other work. The
clone_id_heap and reserve_backed_heap_wrapper are not currently used but will be useful
later, and the linker elides them from the final binary for now so they don't affect code size.
=> Miscellaneous improvements and fixes

src/fs/fs.c, src/runtime/buffer.h, src/runtime/text.h, test/runtime/creat.c, test/runtime/inotify.c, test/runtime/mkdir.c, test/runtime/rename.c, test/runtime/symlink.c, test/runtime/unlink.c, test/runtime/write.c
This change set fixes handling of file names whose length exceeds NAME_MAX, so that -ENAMETOOLONG is returned when appropriate, and allows using symlinks whose target path length is within the PATH_MAX limit.
=> Unix file paths: properly enforce NAME_MAX and PATH_MAX limits

src/aarch64/unix_machine.c, src/riscv64/unix_machine.c, src/unix/filesystem.c, src/unix/filesystem.h, src/unix/syscall.c, src/unix/system_structs.h, src/x86_64/unix_machine.c, test/runtime/time.c
This change adds to the kernel an implementation of the utimensat syscall, which allows programs to use the utimensat() and futimens() POSIX functions.
The new code is being exercised in the runtime tests.
=> Unix syscalls: implement utimensat(2)

src/unix/filesystem.c, test/runtime/time.c
If the program calls utime() or utimes() with a non-existent file path argument, the kernel crashes with "assertion ctx == m->turn failed at src/kernel/mutex.c:263 (IP 0xffffffff800491af)  in mutex_unlock(); halt".
This commit fixes the above issue and adds a test case that would fail without this fix.
=> utime/utimes: fix handling of non-existent files

.gitignore, src/kernel/init.c, src/unix/mmap.c, src/unix/unix.c, src/unix/unix_internal.h, test/e2e/cloud_init/config.json, test/e2e/cloud_init/main.go, test/e2e/e2e.go, test/e2e/node_alloc/alloc.js, test/e2e/node_alloc/config.json, test/e2e/python_alloc/alloc.py, test/e2e/python_alloc/config.json, test/e2e/ruby_alloc/config.json, test/e2e/ruby_alloc/myapp.rb, test/e2e/stressdisk/config.json, test/e2e/stressdisk/main.go, test/go/go.mod
This PR expands the e2e tests beyond testing just for web servers. The
new e2e code can run an arbitrary program, and the new testing code checks
for the exit status message at the end of the output to determine a test
success or failure. The AsyncCmdStart code has been modified to use a
CommandContext with a custom Cancel function in order to provide a
reliable timeout and process status for the command. An additional
Postrun step is added in order to handle any cleanup required after a
test is run.
The new tests include several versions of large memory allocations with
several different language packages, a test for disk full conditions and
data corruption (thanks to @rinor), and a test of some of the cloud init
functionality.
The memory allocation tests revealed two problems in …
=> Additional e2e tests

src/unix/special.c
The sys-info Rust crate has a mem_info() function that reads the contents of the /proc/meminfo file and expects to find a few records (https://docs.rs/sys-info/latest/src/sys_info/lib.rs.html). This change adds the "Buffers", "SwapTotal" and "SwapFree" records so that the mem_info() function doesn't return an error.
=> /proc/meminfo special file: add more records

src/fs/fs.c, test/runtime/mkdir.c
With this change set, mkdir() returns -EEXIST instead of 0 if the user program tries to create a directory that already exists.
In addition, -EROFS is now properly returned when creating a directory or binding a Unix domain socket on a read-only filesystem.
=> filessytem_mkdir: properly handle existing directories and read-only filesystems

src/kernel/init.c
The current version of Ops encodes vector values using the new vector type introduced in TFS version 5; therefore, if multiple expected exit values are specified in the manifest of a given image, the corresponding value decoded by the kernel from the root tuple is a vector.
This change modifies the vm_exit() function so that it can correctly retrieve the expected exit codes when there are multiple such codes; in addition, the checks for string and integer values are being removed because they are redundant: if a value is not a string nor an integer, u64_from_value() returns false.
=> vm_exit(): fix parsing of multiple expected exit codes

klib/Makefile, klib/special_files.c
This new klib will implement miscellaneous special files (e.g. files whose content is dynamically generated, or files that trigger specific actions when written to).
Each special file is enabled by a specific attribute in the "special_files" configuration tuple.
Currently supported attributes:
- "disks" (tuple): special file at /sys/devices/disks, whose contents are a set of records, one for each disk attached to the instance; each record contains the volume name and UUID of the disk, in text format
=> Klbs: add special_files

src/drivers/acpi.c, src/kernel/pci.c, src/kernel/pci.h
A PCI root bridge is a bridge that does not sit downstream another bridge, and as such cannot be detected by probing the host bridge. PCI root bridges are listed in the ACPI tables, where a bridge device handle contains information not only on the memory ranges managed by a given bridge, but also on the "bridge window", i.e. the range of PCI bus numbers managed (directly or indirectly) by the bridge.
This commit amends the ACPI code so that it retrieves both the memory ranges and the bridge windows for all PCI root bridges, and amends the PCI code so that it stores (instead of a vector of PCI buses) a map of bus number ranges (with I/O memory associated to the corresponding root bridge).
The pci_discover() function probes, beside the host bridge, any additional bridges that have been …
=> PCI add support for multiple root bridges

platform/pc/boot/Makefile, platform/pc/boot/stage2.c, src/boot/boot.h, src/boot/elf.c, src/boot/uefi.c, src/kernel/elf.c, src/kernel/elf64.h, src/kernel/klib.c, src/kernel/stage3.c, src/unix/exec.c, src/unix/filesystem.c, src/unix/filesystem.h, src/unix/mmap.c, src/unix/unix.c, src/unix/unix.h, src/unix/unix_internal.h
Until this point, user program executables have been loaded and mapped, in their entirety, using physically-contiguous backed allocations. This practice has the effect of creating pressure on the memory system in the form of fragmentation, which is especially problematic in low memory configurations.
With this change, the user program file and program loader, if any, are now demand paged. Rather than reading the program with filesystem_read_entire(), a small portion is read, which is enough to contain the ELF program headers. The program headers are parsed using load_elf(), but instead of mapping loaded data directly into user memory, the elf_map_handlers instead add pagecache node information to the vmaps covering program text and data, allowing pages for these areas to be faulted in. …
=> fault in user program pages

src/unix/mmap.c, src/unix/unix_internal.h
Requesting a pagecache fill to resolve a page fault for a file-backed mapping can cause the current context to be suspended, e.g. to acquire the filesystem mutex. The context_switch() function, which is called to switch to a kernel context before calling pagecache_map_page(), does not move the stack pointer to the stack of the kernel context; instead, the context will run on the exception/interrupt stack of the current CPU; if the context is suspended, the current CPU can pick up and run a user thread, which can cause a new exception, whose handler will run on the same stack; as a result, when the suspended context is later resumed, it will run on a corrupted stack, leading to a kernel crash.
This change fixes the above issue by removing the use of the context_switch() function (which is …
=> File-backed mappings: request pagecache fill asynchronously

README.md, klib/Makefile, platform/virt/Makefile, rules.mk, src/aarch64/machine.h, src/unix_process/socket_user.c, src/unix_process/unix_process_runtime.c, test/runtime/Makefile, test/runtime/signal.c, test/unit/Makefile, tools/Makefile
This adds support for building nanos on an M1 or M2 based Mac. Several rules
have been rewritten to be more friendly for cross compiling or for determining
CFLAGS based on compiler type and not just platform.
Aarch64 apple clang has several warnings and errors when processing nanos
code and some of them did not have a reasonable solution for making the compiler
happy. Most of these problems were related to the inline assembly. Since homebrew
provides an up-to-date aarch64-elf-gcc, this change uses that instead of clang to
compile the kernel.
While aarch64-elf-binutils works fine for working with the kernel, the linker
appears to have a problem compiling the static runtime tests where the
automatic symbol __ehdr_start is not found. For this reason, a custom
aarch64-linux-binutils formula …
=> Support building with ARM-based Macs

src/kernel/pagecache.c, src/unix/mmap.c, src/unix/unix.c, src/unix/unix_internal.h
This change set fixes two issues that have been introduced by #1904:
1. A call to storage_sync() may suspend the current context, e.g. to acquire the filesystem mutex. Therefore, this function cannot be called directly from the code that handles a page fault exception; instead, an asynchronous thunk should be used. This change modifies the mmap_anon_page() closure function so that it calls storage_sync() first, and the demand_anonymous_page() function so that it invokes the above closure via async_apply_bh(). Closes #1933.
2. Commit https://github.com/nanovms/nanos/commit/3e73a8fb6b32c5bcaa58e160001109f2a2eb379c implemented an OOM killer that sends a SIGKILL to the user program if enough OOM page faults have occurred in a short amount of time. However, the OOM killer is only triggered if …
=> Page faults: fix handling of OOM conditions

src/fs/tfs.h, src/fs/tlog.c, src/kernel/init.c
Instead of silently ignoring volumes whose filesystem cannot be probed, a message is now printed on the console, which makes it easier to identify the reason why an attached volume is not mounted by the kernel (e.g. tfs magic mismatch, tfs version mismatch, or invalid label).
Closes #1926.
=> Volumes: print console message when a filesystem cannot be probed

platform/pc/boot/Makefile, platform/pc/boot/stage2.c, src/runtime/runtime.h
Changes introduced in #1903 caused the size of the stage2 bootloader to increase, exceeding 64KB in some build environments. As described in commit ed5a2f77, stage2 binaries larger than this size may cause boot failures when running under Xen (e.g. AWS EC2).
This PR includes a few commits that ameliorate this inflation. A build-time check is also added which causes the build to fail if the stage2 binary size exceeds 64KB. (This is disabled when building debug images with MEMDEBUG or UBSAN enabled.)
=> reduce stage2 size

platform/pc/boot/Makefile, platform/pc/pci.c, platform/virt/Makefile
This change set fixes a couple of issues preventing the kernel from booting on UEFI-enabled machines.
1. Since the addition of the string and vector tag types, the UEFI bootloader needs to include the code from the string.c and vector.c source files
2. The existing code in the pci_platform_init_bar() function for the PC platform is not handling 64-bit addresses, thus fails to properly read and assign addresses when the 64-bit flag is set for a given PCI BAR
=> UEFI fixes

src/drivers/vga.c
In UEFI systems using a framebuffer display there may still be a working vga pci device, but since it is not set up for text mode, writes to the display buffer can cause the system to hang. This change adds an additional check when probing a vga device to read the miscellaneous output register and check the "RAM Enable" bit, which is required to be set for accessing the display buffer from the system. This bit is cleared in UEFI systems with a framebuffer/GOP display.
=> VGA: check display buffer setting when probing device

src/kernel/log.c
The klog_dump used by the kernel is a buffer passed directly to a storage handler, but some storage drivers like xen require at least sector alignment for the transaction's buffer. The dump was located in the bss at the end of the klog struct, so it had no alignment guarantees. This change moves it to the front of the struct and adds a 512-byte alignment requirement to the struct. This fixes an assertion failure when running klog_save on a xen instance.
=> Klog: Ensure sufficient alignment for dump

src/unix/mmap.c
In the x86_64 architecture, MAP_32BIT is a valid flag for the mmap() syscall. This change brings back support for this flag, which was dropped by mistake in commit 770cbfb8e5b48ec20ff87678e570816eb521a074.
Credits go to @rinor.
Closes #497
=> mmap(): fix handling of MAP_32BIT flag for x86_64

src/http/http.c
Commit 5301c6a7 introduced a regression whereby the "start_line" vector attribute of an http request would be explicitly freed, which would then later cause a double free during parser cleanup. This change corrects this issue by treating the vector as an immutable value (whereas previously it was cloned and thus consumable).
=> fix double free in each_http_request()

klib/syslog.c, src/drivers/netconsole.c, src/net/netsyscall.c
If a udp pcb is created with udp_new(), it appears to default to being an ip4 pcb, which will then reject sending any ip6 traffic with an invalid argument because the pcb doesn't support ip6. This changes all udp_new calls to udp_new_ip_type(IPADDR_TYPE_ANY) which makes the pcb dual-stack. Ip6 udp sockets will now properly transmit
ip6 traffic. This also allows the udp netconsole and syslog to work with ip6 addresses.
=> Create only dual-stack udp pcbs

src/unix/inotify.c, src/unix/io_uring.c, src/unix/notify.c, src/unix/notify.h, src/unix/poll.c, src/unix/signal.c, src/unix/socket.c, test/runtime/Makefile, test/runtime/epoll.c
This change adds support for the EPOLLEXCLUSIVE flag in the epoll implementation, which allows limiting the number of threads waiting on a file descriptor that are woken up when an event set is notified. The EPOLLEXCLUSIVE flag works on a per file descriptor basis, not on a per epoll instance basis, so it can be used with threads waiting on a given file descriptor via one or more epoll instances.
The event_handler closure type in the notify subsystem has been changed to return a u64 value instead of a boolean value, so the event handlers can indicate whether they have "consumed" the events being reported. A notify entry is now associated to a set of flags, used to indicate whether a handler is exclusive. When an event set is notified, the notify subsystem calls all non-exclusive handlers, …
=> epoll: add EPOLLEXCLUSIVE support

src/kernel/stage3.c, src/net/net.c, src/net/net.h
This change implements a new kernel configuration option "exec_wait_for_ip6_secs", which instructs the kernel to wait for an IPv6 address to be acquired before starting the user program; the value of this option indicates a timeout, expressed in seconds, after which the kernel starts the program even without an IPv6 address.
IPv6 address acquisition is considered complete when one of the IPv6 addresses associated to a network interface is a global address in a valid state. Both dynamic address acquisition via DHCPv6 and static configuration via the "ip6addr" option lead the network interface to reach a state which allows the kernel to start the user program.
In addition, this change allows both the "exec_wait_for_ip6_secs" option and the already existing "exec_wait_for_ip4_secs" option to …
=> Network: add support for starting program after IPv6 initialization

klib/Makefile, klib/test/lock.c, src/drivers/vga.c, src/kernel/kernel.h, src/unix/special.c, src/unix/unix_internal.h, test/runtime/ktest.manifest
This change set allows building and running the latest version of the Nvidia GPU klib (https://github.com/nanovms/gpu-nvidia/):
1. the spin_tryrlock() and spin_trywlock() functions have been added to the R/W spinlock implementation 
2. for Unix special files, the special_file_wrapper struct definition has been moved to a header file so that it can be used by klib code
3. the VGA console driver has been amended to check whether the device being probed is configured in VGA mode 3
=> Miscellaneous features for new Nvidia GPU klib

src/aarch64/unix_machine.c, src/riscv64/unix_machine.c, src/unix/syscall.c, src/x86_64/unix_machine.c, test/runtime/readv.c, test/runtime/writev.c
These syscalls are analogous to readv and writev, but take an additional file offset argument and do not change the internal file offset.
The existing readv and writev functions have been refactored to de- duplicate code, with a new iov_internal() function which is now called by readv, writev, preadv and pwritev.
The readv and writev runtime tests have been amended to exercise preadv and pwritev as well.
=> Syscalls: add support for preadv and pwritev

src/unix/coredump.c, src/unix/signal.c, src/unix/system_structs.h, src/unix/thread.c, src/unix/unix.c, src/unix/unix_internal.h, test/runtime/signal.c
This change set fixes two issues in the Unix signal implementation:
- If a poll request is issued on a signalfd file descriptor to poll for the delivery of a blocked signal (i.e. a signal that is in the process signal mask), the poll syscall does not return when the signal is raised
- Ignored signals are not detectable via sigwaitinfo(), sigtimedwait() or sigwait(), nor via signalfd
=> Unix signals: fix polling for blocked signals via signalfd, fix handling of ignored signals

platform/pc/boot/Makefile, platform/virt/Makefile, src/kernel/pagecache.c, src/kernel/pagecache_internal.h, src/runtime/range.h
Using a limited-size queue to store pagecache node sync requests can lead to a failure to enqueue a request if the user program issues many parallel fsync() syscalls on a given file. In addition, using this queue to store both commit closures and sync completion status handlers can cause failure to clear the `committing` flag in the pagecache_node struct (because a completion status handler will not call the commit_dirty_node_complete() function, which is where the flag is cleared), which can lead to a deadlock where fsync() calls by the user program will never return.
This change replaces the limited-size queue and the `committing` flag with an operation list where commit closures and completion status handlers are stored (wrapped in a struct which contains information on the type of …
=> Pagecache nodes: replace dirty_commits queue with operation list

src/unix/system_structs.h, src/unix/timer.c, src/unix/unix_clock.c, src/unix/unix_internal.h, test/runtime/time.c
The clock_gettime(), clock_getres() and timer_create() syscalls can be invoked with clock id values returned by the
clock_getcpuclockid() and pthread_getcpuclockid() C library functions.
This change modifies the logic of the above syscalls so that they can properly decode such clock id values. For POSIX timers, in case a timer is created with a clock id corresponding to the CPU time of an arbitrary thread, a reference to this thread is kept in the timer struct, because the thread's timer queue must not be deallocated until the timer is closed.
Closes #1946
=> Unix clocks: add support for {clock,pthread}_getcpuclockid()

src/kernel/page.c
Even though there is no need to invalidate TLB entries and invoke a TLB shootdown after mapping a virtual address that was previously not mapped, invalidation of newly mapped pages on the local CPU is being retained in the map_level() function to avoid the possibility of a CPU having a stale mapping in its TLB as a result of a not yet executed TLB shootdown handler triggered by a previous unmapping from another CPU. However, in order for a TLB invalidation to be complete, the flush_tlb() function needs to be called, which is not being done in the current code.
This change adds a call to flush_tlb() in the map_with_complete() function, at the end of a mapping operation.
This fixes an issue observed when running on Mac M1 (ARM64) hosts, where a data abort exception occurs when a virtual …
=> map(): call flush_tlb() after mapping a virtual address

platform/virt/Makefile, platform/virt/service.c, src/hyperv/vmbus/hyperv.c, src/kernel/init.c
This change set ensures that the exit status of the user program is reflected in Qemu's exit status only if the "debug_exit" option is specified in the manifest. This fixes two minor issues:
- when running on-prem instances on x86_64 machines, Ops no longer outputs the spurious "exit status 1" error message
- when running on an Aarch64 machine that does not support the Angel shutdown command (such as Apple M1 and M2 machines), the kernel no longer outputs the "QEMU exit code will not reflect program exit code" error message
In order for the exit status of the user program to be reflected in Qemu's exit status (or for an error message to be output if this is not supported), the "debug_exit" option has to be specified in the manifest. Example configuration when using Ops:
``` …
```
=> VM shutdown fixes

src/fs/tlog.c
When the current log extension of a TFS filesystem is full and a new extension is created, any log entries that could not fit in the current extension must be written to the staging buffer of the new extension.
This change fixes a regression introduced in commit d151508. In addition, it fixes a build failure when the TLOG_DEBUG_DUMP preprocessor #define is present.
Closes #1970.
=> TFS log_write_internal(): fix writing to new log extension

src/unix/vsock.c, src/virtio/virtio_internal.h, src/virtio/virtio_socket.c, src/virtio/virtqueue.c
This changeset fiexs two issues in the vsock code when run in multi-processor machines:
1. A lock inversion problem could cause deadlocks when a vsock file descriptor was registered in an epoll instance operated by multiple threads
2. The requirement of the stream socket type that guarantees delivery of ordered packets during a connection was not satisfied
=> Vsock fixes

src/net/netsyscall.c
This change enhances the getsockopt() implementation for network sockets by adding support for a few options at the TCP socket option level. These options are used by the AMQP client for Python at http://github.com/celery/py-amqp.
Closes https://github.com/nanovms/ops/issues/1541.
=> netsock_getsockopt(): add more TCP options

src/aarch64/interrupt.c, src/drivers/acpi.c, src/hyperv/utilities/vmbus_shutdown.c, src/kernel/init.c, src/kernel/kernel.c, src/kernel/kernel.h, src/kernel/schedule.c, src/riscv64/interrupt.c, src/unix/coredump.c, src/unix/signal.c, src/unix/syscall.c, src/unix/thread.c, src/unix/unix.c, src/x86_64/interrupt.c, src/xen/xen.c
Not sure if this is the best way, but it should work for clean differentiation of shutdown origin when checking/executing  hooks like `reboot_on_exit` so they don't interfere on "normal" shutdown/stop requests
=> feat(shutdown): record shutdown sources

klib/ntp.c, src/aarch64/clock.c, src/aarch64/gic.c, src/aws/ena/ena.c, src/aws/ena/ena_com/ena_com.c, src/aws/ena/ena_com/ena_com.h, src/aws/ena/ena_com/ena_defs/ena_admin_defs.h, src/drivers/ns16550.c, src/drivers/nvme.c, src/kernel/clock.c, src/kernel/init.c, src/runtime/clock.h
This change set enhances the AWS ENA network interface driver to add support for retrieving the current time from a PTP hardware clock, when supported by the network interface.
In addition, the NTP klib has been enhanced to be able to retrieve time from the PTP clock alternatively to using NTP; if the root tuple contains a "chrony" tuple that has a "refclock" attribute with "ptp" value, then the NTP klib uses the PTP clock for synchronizing the system time; if a PTP clock is not available, the klib falls back to NTP.
These features can be used on selected AWS instances (currently, from the R7g (ARM Graviton3) instance family in the Asia Pacific (Tokyo) region) to synchronize the system time with the PTP clock.
The first 5 commits fix a few issues encountered when running on AWS R7g …
=> AWS: add support for PTP hardware clock

src/runtime/management.c
This change fixes a "variable 'v_copy' is used uninitialized whenever 'if' condition is true" error output by the clang compiler, which is causing a failure in Mac nightly builds.
=> tuple_notifier_cow_iterate_each(): fix variable initialization

test/e2e/e2e.go, test/e2e/ruby_3.1.2/config.json
The ruby_3.1.2 package already includes the sinatra gem, thus it is not necessary to install it locally in order to run a Ruby web server. This change removes the sinatra gem installation step in the Rubty e2e test; in addition, the GEM_HOME environment variable is being removed from the Ops configuration file because the Ruby package already provides a correct value for this variable (consistent with the contents of the package).
This change fixes a 'Sinatra could not start, the "rackup" gem was not found' error that occurs when trying to run the (locally installed) latest release of the sinatra gem during the e2e tests.
=> E2E tests: ruby: remove sinatra gem install and GEM_HOME env var

klib/cloud_init.c, test/e2e/cloud_init/config.json
Attempting to connect to a cloud_init server before an IP address is acquired via DHCP results in a connection error, which causes the cloud_init klib to fail to initialize (and thus the VM to be stopped without executing the user program). This is causing sporadic "program startup failed before exec: (result:connect failed (-4))" errors to occur when running the cloud_init e2e test as part of the Jenkins CI tests.
This change fixes the above issue by adding a check for a suitable IP address configuration before attempting to connect to a server or resolve its host name, and retrying connecting at a later time if this check fails.
The code to retry a connection when the DNS query function returns ERR_INPROGRESS has been removed, and a call to
cloud_download_connect() has been added in the …
=> cloud_init: fix errors when loaded before acquiring IP address

src/unix/exec.c
This change adds the AT_BASE entry (which contains the base address of the interpreter for the user program, or zero if there is no interpreter) to the auxiliary vector that is set up on the user stack when executing the program. This is needed by the musl dynamic linker, which would otherwise calculate a wrong base address during startup, resulting in a segmentation fault.
=> ELF exec: add AT_BASE entry to auxiliary vector

platform/pc/boot/stage2.c, src/boot/uefi.c, src/config.h, src/kernel/init.c, src/kernel/kernel.h, src/kernel/page.c, src/kernel/pagecache.c, src/kernel/pagecache.h, src/kernel/pagecache_internal.h, src/runtime/kernel_heaps.h, src/unix/mmap.c, src/unix/special.c, src/unix/unix_internal.h, test/runtime/mmap.c, tools/dump.c, tools/mkfs.c, tools/tfs-fuse.c
This new heap is a caching heap that allows allocating single memory pages, while avoiding complete exhaustion of physical memory and minimizing memory fragmentation. It is used by both the pagecache code (instead of a pagecache-specific caching heap) and the mmap code (instead of the page_backed heap), which now avoid accessing directly the physical heap. The page heap is drained by the MM service when the kernel is running out of memory.
This change fixes a memory fragmentation issue that occurs when the user process makes heavy use of map() and unmap() system calls and may cause failure to allocate 2MB chunks of memory (https://github.com/nanovms/ops/issues/1570#issuecomment-1895947857).
The first 2 commits refactor the mmap code to remove code duplication, the third commit fixes a bug …
=> Kernel heaps: add page heap

src/hyperv/netvsc/netvsc.c
The existing code is setting the tot_len field of the first struct of a pbuf chain to a value double the correct value, and is failing to update the tot_len value of all pbufs in a chain when appending received data.
This change fixes the above issues, which were causing a page fault in the pbuf_realloc() lwIP function during reception of an IPv6 packet.
=> Hyper-V: netvsc: fix setting of pbuf length in received packets

src/kernel/kernel.c, src/unix/aio.c, src/unix/io_uring.c
This changeset fixes memory leaks that have been discovered while load-testing mysql with HammerDB (https://github.com/nanovms/nanos/issues/1999).
=> Memory leak fixes

src/virtio/virtio_internal.h, src/virtio/virtio_net.c, src/virtio/virtio_socket.c, src/virtio/virtio_storage.c, src/virtio/virtqueue.c
This changeset fixes a few issues on the virtio_net and virtio_blk drivers that have been observed when load-testing mysql running on AWS Firecracker.
Closes #1999.
=> virtIO fixes

klib/tmpfs.c
The `fss` variable, which contains the return value of the tmpfs_create() function, is not being initialized when creating non-regular files. This issue is detected by the clang compiler with "error: variable 'fss' is used uninitialized whenever 'if' condition is false".
=> tmpfs_create(): add missing initialization of return value

src/unix/syscall.c
With this change, it is possible to configure the kernel to insert arbitrary strings in the `sysname` and `release` fields of the struct used in the uname syscall. This allows running user programs that expect these fields to have specific values (e.g. programs that expect the sysname to be "Linux", or programs that parse the release string to infer a Linux kernel version).
To configure the sysname and release fields, a "uname" configuration tuple is used: this tuple can contain a "sysname" string and a "release" string, which allow configuring the respective fields; if a given string is not present in the configuration, its default value is used (i.e., "Nanos" for the sysname field, and "5.0-<NANOS_VERSION>" for the release field). Example snippet of Ops configuration file:
``` …
```
=> uname: add configurability of sysname and release

platform/pc/boot/Makefile, platform/pc/boot/linker_script, platform/virt/Makefile, rules.mk, src/aarch64/klib.lds, src/riscv64/klib.lds, src/x86_64/klib.lds
This changeset fixes linker warnings that appeared starting with release 2.39 of the GNU binutils.
In addition, it amends the x86 bootloader linker script so that the size of the bootloader binary file is decreased by around 2%.
Closes #1870 and #2010
=> Fixing linker warnings

src/kernel/pagecache.c
When a page fault occurs on a file-backed mapping for a page that was previously in the page cache but has later been evicted, the fault handler calls pagecache_map_page_if_filled(), which should return `false` because the newly re-allocated page has not been filled yet. Commit 132a832e79c8a50fd9f5d47b0661fd3295b8605f introduced a regression which causes pagecache_map_page_if_filled() to return `true` instead; this leads to page cache contents inconsistent with file contents and erroneous data accessed by the user program via the file-backed mapping.
This change fixes the above issue by amending the touch_or_fill_page_nodelocked() function so that it returns `false` when the relevant page is in the ALLOC state.
=> pagecache: fix on-demand mapping of evicted pages

src/runtime/tuple.c
A given status tuple may contain another status tuple as value for one of its attributes (e.g. when a status tuple is generated via a call to `timm_up()`), and the inner tuple can be an arbitrary tuple, including `timm_oom` (i.e. the global tuple that is allocated during kernel initialization and is used to indicate out-of-memory conditions). The `timm_oom` tuple must never be deallocated, but the existing code deallocates it if it is the value for an attribute of an outer status tuple.
This change fixes the above issue.
=> timm_dealloc(): fix handling of tuples that reference `timm_oom`

src/fs/tfs.c, src/fs/tfs_internal.h
PR #1578 implemented deferred execution of storage operations for TFS file extents that are transitioning from uninited to initialized state. This creates a problem when a pagecache node I/O request spans multiple extents: if one extent is uninited and the next extent is initialized, (a portion of) the SG buffers destined to the first extent are written into the second extent, and vice versa.
In order to properly assign SG buffers to extents, the SG list supplied in a given node I/O request must be consumed by each extent in the exact order in which the different extents cover the file range of the I/O request. If a storage operation for a given extent is deferred, this requirement may not be satisfied, which leads to corruption of file contents.
This change fixes the above issue by …
=> TFS: fix handling of storage operations on uninited extents

platform/pc/service.c, src/x86_64/page.c, src/x86_64/page_machine.h
Depending on the address of the initial pages allocated in setup_initmap(), the map_setup_2mbpages() function may not find an existing PDPT and or PDT in the page tables, and thus may need to use a new PDPT and/or a new PDT. However, the PDPT and PDT addresses passed to this function correspond to in-use pages, and as such cannot be reused and assigned to new PTEs. Moreover, when creating a new PTE, the map_setup_2mbpages() function is simply OR-ing the page address with the page flags, failing to set the USER flag and thereby preventing any pages referenced by this directory entry from being mapped for user space access; this may cause bogus segmentation fault signals to be delivered to the user process (https://github.com/nanovms/nanos/issues/1999#issuecomment-2072735021).
This change …
=> x86: setup_initmap(): fix mapping of initial pages

src/x86_64/kernel_machine.h
In the x86_64 architecture, the KERNEL_LIMIT constant is currently set to 0xfffffffffffff000; if the KASLR process places the kernel near the end of the allowed address range, kernel addresses may overlap with the vsyscall page, which always starts at a fixed address (0xffffffffff600000); this may cause boot failures such as in https://app.circleci.com/pipelines/github/nanovms/nanos/4631/workflows/1400a162-d5c4-478d-8cc8-bdf84ab2536a/jobs/16261.
This change fixes the above issue by changing the KERNEL_LIMIT constant to coincide with the start of the vsyscall page.
=> x86: fix overlapping of kernel addresses with vsyscall page

klib/Makefile, klib/azure.c, klib/azure.h, klib/azure_diagnostics.c, klib/cloud_azure.c, klib/cloud_init.c, klib/cloudwatch.c, klib/gcp.c, klib/mbedtls.c, klib/net_utils.c, klib/net_utils.h, klib/xml.c, klib/xml.h, src/fs/tlog.c, src/gdb/gdbstub.c, src/gdb/gdbutil.c, src/http/http.c, src/kernel/init.c, src/kernel/kernel.h, src/kernel/klib.c, src/runtime/buffer.c, src/runtime/buffer.h, src/runtime/extra_prints.c, src/runtime/runtime.h, src/runtime/runtime_init.c, src/runtime/symbol.c, src/runtime/tuple.c, src/runtime/tuple.h, src/xen/xennet.c
This change set enhances the cloud_init klib by implementing an Azure VM agent (this fixes the "virtual machine agent status is not ready" warning that is currently displayed for Nanos instances in the Azure portal), and adds a new "azure" klib that implements an Azure extension similar to the Linux Diagnostic extension.
The current implementation supports sending 4 types of memory metrics (i.e. available and used memory, as both number of bytes and percentage of total memory). The azure klib is configured in the manifest options via an "azure" tuple; the diagnostic functionalities in this klib are enabled and configured by inserting a "diagnostic" tuple with the following attributes:
- `storage_account`: indicates the Azure storage account to be used to store metrics data generated by …
=> Azure: implement sending memory metrics via diagnostic extension

src/virtio/virtio_9p.c
Since commit d037970c, in multi-vCPU instances root filesystem initialization can complete before PCI bus discovery; this means that any filesystem mount points specified in the manifest options can be already processed by the time a virtio-9p device is probed and a corresponding volume is added; this in turn means that the `volume_add()` function called by `v9p_dev_attach()` can trigger a direct call to `v9p_fs_init()`.
The `v9p_fs_init()` function uses the `general` field of the `virtio_9p` struct, which in the current code is initialized after calling the `volume_add()` function; this causes `v9p_fs_init()` to access an uninitialized pointer, leading to an unhandled page fault. The same issue applies to the `backed` field of the struct.
This change fixes the above issue by moving the …
=> Virtio-9P device attach: fix initialization of virtio_9p struct

src/aarch64/interrupt.c, src/aarch64/page_machine.h, src/kernel/pagecache.c, src/kernel/pagecache.h, src/riscv64/interrupt.c, src/unix/mmap.c, src/unix/thread.c, src/unix/unix.c, src/unix/unix_internal.h, src/x86_64/interrupt.c
When on-demand paging of the program file is enabled, BSS areas in pages faulted-in on demand are zeroed in-place, i.e. a newly mapped page retrieved via the page cache is zeroed starting from the BSS offset set up when initializing the relevant vmap. This creates a problem if the page contains other data (e.g. from another loadable section of the program) at or after the BSS offset, in which case this data would be overwritten.
This change fixes the above issue by using a separate page (instead of the page from the page cache) where the initialized program data (located before the BSS offset) is copied from the page cache page, and the rest of the page (starting at the BSS offset) is zeroed out. Closes https://github.com/nanovms/ops/issues/1629.
The last commit fixes an assertion failure …
=> On-demand program file paging: fix initialization of BSS areas

platform/virt/service.c
In instances where the physical memory start address is fixed to a hard-coded value (such as when instantiating a Qemu "virt" machine type), the memory end address should be calculated from the hard-coded start value instead of from the start of usable memory.
This change fixes a "frame 0x00ff800042200800 already full" fatal error caused by a "data abort in el1 write" exception that is triggered when the kernel allocates memory at an address range past the end of physical memory (e.g. when the user process tries to use more memory than available).
=> Aarch64 physical ID heap: fix setting of memory end address

klib/test/page_table.c, src/aarch64/page_machine.h, src/kernel/flush.c, src/kernel/page.c, src/kernel/page.h, src/kernel/pagecache.c, src/kernel/stage3.c, src/riscv64/page_machine.h, src/runtime/heap/id.c, src/unix/exec.c, src/unix/mmap.c, src/unix/system_structs.h, src/unix/unix_internal.h, src/x86_64/page.c, src/x86_64/page_machine.h, test/runtime/mmap.c
Memory areas mapped in the user process virtual address space are paged on-demand when the process causes a page fault by de-referencing a virtual address. In the existing implementation, a single 4-KB memory page is allocated and mapped after a page fault; with THP, memory pages belonging to anonymous mappings can be allocated and mapped using larger sizes (up to 2 MB); this decreases the number of page faults triggered when the process accesses a large memory area, resulting in improved performance. In addition, by allowing user pages to be mapped at a block level (i.e. in 2MB chunks) instead of being limited to page-level mappings (i.e. 4KB chunks), TLB usage is optimized and TLB hit rates are increased.
The THP feature is enabled by default in memory areas mapped via the mmap() …
=> Memory mapping: add support for Transparent Huge Pages (THP)

platform/virt/pci.c, platform/virt/service.c, src/aarch64/kernel_machine.c, src/aarch64/kernel_machine.h, src/devicetree/devicetree.c, src/devicetree/devicetree.h, src/kernel/pci.c
This change set adds parsing of the device tree blob during kernel initialization when running on ARM machines, in order to retrieve the number of vCPUs and the base address of the PCI configuration space.
This allows the kernel to:
- properly detect the number of vCPUs when ACPI tables are not present (e.g. when running an on-prem instance with Ops)
- run without the 'highmem=off' Qemu command line option
The first commit fixes a "set_gap error" message that is printed on the console when running an ARM instance using a QEMU "virt" machine with the "highmem" setting enabled and with UEFI firmware.
=> ARM: add parsing of device tree blob

src/unix/mmap.c
If the kernel manifest contains a "transparent_hugepage" option with a value set to "never", the THP feature is disabled, i.e. process memory is mapped using 4KB pages only.
Example snippet of Ops configuration file to disable THP:
```
"ManifestPassthrough": {
"transparent_hugepage": "never"
}
```
=> Transparent Huge Pages: add configuration option to disable feature

src/kernel/init.c, src/unix/coredump.c, test/extended_tests.py
This change set fixes creation of the core dump file when the user program terminates abnormally.
In addition, the core dump test in the test suite has been made more robust by adding a file size check, so the test will fail if a zero-sized core dump file is generated.
=> Core dump: fix writing of core dump file data to disk

src/kernel/page.c
The range passed to the range handler should be the same range that has just been unmapped.
This change fixes an incorrect deallocation of physical memory that happens when a memory range being unmapped contains a 2MB-sized page that covers a portion of the tail of the unmapped range (and that is thus split into 4KB pages); see the "bitmap_dealloc error" messages in https://github.com/nanovms/ops/issues/1654.
=> Page tables: unmap_page(): fix call to range handler

src/unix/filesystem.c, src/unix/unix_internal.h
The size and offset fields of struct sg_buf are 32-bit fields, thus a single SG buffer can only be used for data sizes smaller than 4 GB.
This change amends the iov_to_sg() function so that it creates multiple SG buffers if an iovec entry length is 4GB or larger.
Fixes https://github.com/nanovms/ops/issues/1654
=> iov_to_sg(): fix SG buffer creation for iov entries larger than 4GB

src/kernel/pagecache.c
Throughout the page cache code, when both a cache node and the cache state need to be locked at the same time, the node must be locked first. The existing implementation of pagecache_read_sg_finish() is locking the cache state first, thereby creating a locking order inversion that can cause the kernel to deadlock in multi-vCPU instances, for example if multiple reads from the page cache are executed concurrently (the CI test failure at
https://app.circleci.com/pipelines/github/nanovms/nanos/4810/workflows/d6be64e2-18b7-4d4a-bb4c-8426ac35239c/jobs/16820 is caused by this).
Bug introduced in commit 8225e715.
=> pagecache_read_sg_finish(): fix locking order inversion

src/fs/tfs.c
If there is not enough storage space to extend a TFS file extent to the requested size, the extent size should be adjusted to match the available space. The existing code is updating the extent size as if the storage space limit had not been reached; this can cause the TFS driver to issue disk I/O requests with invalid block ranges, which results in EIO syscall errors.
=> TFS extent extension: fix handling of exhausted disk space

src/kernel/kernel.h, src/kernel/schedule.c, src/runtime/timer.c, src/runtime/timer.h
Before running a user thread, if the local timer of the current CPU is not armed (because either the timer interrupt already fired since doing the last timer update, or the timer has never been armed), the `timeout` variable in the current code in runloop_internal() is negative, thus the `timeout > (s64)max_timeout` condition is always false; this results in the CPU timer not being armed and the user thread potentially running indefinitely. This issue causes the umcg runtime test to hang if run on an instance with more than 4 vCPUs.
This change fixes the above issue by using the `last_timer_update` field of the cpuinfo struct to check the timestamp at which the next timer interrupt will fire (with a 0 value in this field indicating that the timer is not armed). In addition, unnecessary …
=> Runloop: fix check for unset CPU timer when running a user thread

SECURITY.md, src/kernel/page.c, src/unix/mmap.c, src/unix/unix_internal.h, test/runtime/mmap.c
A mapping with this flag can be expanded downwards dynamically (up to the PROCESS_STACK_SIZE limit) by "touching" addresses lower than the base of the mapping.
This feature requires that a guard gap is kept between a MAP_GROWSDOWN mapping and any adjacent mappings. The second commit implements enforcing of the guard gap next to the process stack, which is a security feature because it greatly
decreases the likelihood of a stack overflow not being detected and prevents the exploitation of many application vulnerabilities
that involve overflowing the stack.
The first commit fixes a bug in the paging code that was causing sporadic failures when running the mmap runtime test.
=> mmap(2): add support for MAP_GROWSDOWN flag

src/kernel/pagecache.c, src/unix/mmap.c, src/unix/unix_internal.h
This allows custom mmap() implementations for specific file descriptors to handle page faults on mmap()ed memory. This feature
is used by the Nvidia GPU klib.
The first commit allows reading from the page cache with non-contextual completion closures, such as when the reading context suspends itself and the completion resumes the suspended context (this happens in the Nvidia GPU klib when reading the GPU firmware file).
=> Page faults: add support for custom fault handlers

platform/pc/boot/Makefile, platform/pc/boot/stage1.s
Following a recent update of the hypervisor and/or the BIOS firmware on AWS Xen-based instances (e.g. t2 instances), the BIOS never returns from the INT 13H routine that the stage1 bootloader uses to read stage2 code from disk. This prevents the kernel from booting on those instance types.
This change fixes the above issue by disabling the 8259 PIC only after reading stage2 code from disk. This allows the BIOS firmware to work properly when executing the INT 13H routine, and also allows this routine to be executed more than once. Therefore, the limitation of 64 kB on stage2 code size is being lifted, since a larger stage2 binary (which requires more than one INT 13H call in order to be read from disk) is now properly handled on AWS instances.
=> x86 bootloader: keep 8259 PIC enabled when reading from disk

src/net/netsyscall.c, src/unix/blockq.c, src/unix/exec.c, src/unix/filesystem.c, src/unix/filesystem.h, src/unix/io_uring.c, src/unix/mmap.c, src/unix/netlink.c, src/unix/socket.c, src/unix/socket.h, src/unix/syscall.c, src/unix/unix.c, src/unix/unix_internal.h, src/unix/vsock.c, test/runtime/io_uring.c, test/runtime/symlink.c
This change set implements new features that allow running TigerBeetle (https://github.com/tigerbeetle/tigerbeetle) on Nanos:
- io_uring supports accept, openat, statx, send and recv operations
- setrlimit() and prlimit64() allow changing the process stack limit
- file permissions returned by stat() and similar syscalls are retrieved from file metadata
=> New features to support TigerBeetle

README.md, kernel.mk, src/kernel/storage.c, src/unix/unix.c, test/runtime/README.md, test/unit/udp_test.c
**Build is not working due to following issues:**
- ```go``` is not documented as dependency in the description for Linux
```bash
GO	/home/user/repos/nanos/output/test/runtime/bin/webg
/bin/sh: line 1: go: command not found
```
- there is an issue with a new line that is not printed due to ```echo``` not processing ```\n```
```bash
VERSION	/home/user/repos/nanos/output/platform/pc/gitversion.c
CC	/home/user/repos/nanos/output/platform/pc/output/platform/pc/gitversion.o
/home/user/repos/nanos/output/platform/pc/gitversion.c:1:21: error: extra tokens at end of #include directive [-Werror]
1 | #include <runtime.h>\nconst sstring gitversion = ss_static_init("243c5a2010916b8fd69f86b290d637ad0efc1dbd");
|    
```
**Test-Build is not working due to following issues:**
- ```ops``` is not …
=> fix doc and build issue (for linux)

src/net/netsyscall.c, src/unix/system_structs.h
This socket option controls the setting of the DF (don't fragment) flag in output IPv4 packets.
Depends on https://github.com/nanovms/lwip/pull/14.
=> Network socket options: add support for IPPROTO_IP/IP_MTU_DISCOVER

src/unix/notify.c, src/unix/notify.h, src/unix/poll.c, test/runtime/epoll.c
In addition, epoll_ctl() now returns -EINVAL if called on a non-epoll file descriptor, or if the file descriptor being added, deleted, or modified is the same as the epoll file descriptor on which epoll_ctl() is called.
Closes #1192.
=> epoll: add support for polling on epoll file descriptors

platform/virt/Makefile, platform/virt/kernel_platform.h, platform/virt/service.c, src/aarch64/gpio.c, src/aarch64/gpio.h, src/devicetree/devicetree.c, src/devicetree/devicetree.h
If ACPI tables are not present in a given Qemu aarch64 instance (e.g. when running an instance with the "virt" machine type and without a UEFI firmware), upon reception of the "system_powerdown" command (which is used to gracefully shut down the instance), Qemu toggles the "poweroff" GPIO instead of generating an ACPI event.
This change set adds parsing of GPIO key information from the device tree, and if such information can be found, enables interrupt generation on the PL061 GPIO controller when the poweroff GPIO is toggled, so that the kernel can be shut down by the interrupt handler.
This allows a graceful shutdown to be performed when an on-prem instance launched with `ops run --arch=arm64` is terminated with CTRL-C.
=> Aarch64 powerdown: add support for GPIO power key

src/virtio/virtio.c, src/virtio/virtio_balloon.c, src/virtio/virtio_mmio.c, src/virtio/virtio_mmio.h
This allows the virtio memory balloon driver to work with AWS Firecracker, which instantiates MMIO devices.
=> virtio_balloon: add support for MMIO devices

src/aarch64/crt0.S, src/aarch64/kernel_machine.c, src/aarch64/kernel_machine.h, src/riscv64/kernel_machine.h, src/unix/unix.c, src/x86_64/kernel_machine.h
Starting with Go version 1.23, the Golang runtime for Arm64 during initialization tries to retrieve the values of some system registers (via the MRS instruction) in order to evaluate the features implemented by the processor. This instruction causes a CPU exception, which is not properly handled by the kernel; as a result, Go programs built with Go version 1.23 do to not work on Arm.
This change set adds emulation of the MRS instruction to retrieve the values of the system registers used by the Go runtime, so that Go 1.23 works properly on Arm.
=> Arm fault handler: add emulation of MRS instruction

klib/cloud_azure.c, platform/virt/service.c
The memory range that is identity-mapped during boot is used, among other things, as temporary stack for both the boot processor and the secondary processors; therefore, it should not be included in the physical memory ranges, otherwise a secondary processor can corrupt memory that has been allocated for other kernel uses. This fixes unhandled exceptions that cause boot failures when running the kernel on Azure Standard_D2ps_v5 instances.
In addition, the Azure cloud_init code is being amended to avoid printing a potentially misleading error message if an unsuccessful attempt to connect to the Azure Wire Server is made before the network interface acquires a DHCP address.
=> ARM physical heap: exclude all identity-mapped memory

src/kernel/stage3.c, src/unix/exec.c, src/unix/filesystem.c
This allows an application to be run on images where the files at the program path and interpreter (dynamic loader) path are symbolic links.
=> fsfile_open(): follow symbolic links

platform/pc/Makefile, platform/riscv-virt/Makefile, platform/virt/Makefile, rules.mk, src/fs/tlog.c, src/kernel/init.c, src/kernel/kernel.h, src/kernel/vmem_heap.c, src/runtime/kernel_heaps.h
Since commit 14625267b7 "Physical heap: switch from id heap to buddy memory allocator", the physical memory heap does not support allocation requests larger than 2 MB; this is done in order to keep the heap implementation efficient in terms of both runtime performance and memory overhead. However, there are rare cases where the kernel needs memory allocations that exceed this limit: for example, when booting images with large filesystems, the tuple staging buffer for the TFS log can grow in size to several MB, and if memory allocation fails, the kernel panics with "_assertion buffer_write(tl->tuple_staging, buffer_ref(b, 0), length) failed_".
In order to allow the kernel to allocate large chunks of memory while keeping the physical memory allocator efficient, add a new kernel heap that …
=> Kernel heaps: add vmem heap
