nanovms/nanos

- src/unix/pipe.c
This is needed by Redis (ticket #291).
> pipe: add support for non-blocking operation

- test/e2e/e2e.go
This is an attempt to fix the spurious "connection reset" errors during CI runs. This removes the fixed 10 second delay instead tries the first http request of each test up to 5 times (with exponential backoff) before giving up.
> replace fixed timeout in e2e tests with retry with exponential backoff

- src/unix/mmap.c
> add newlines to msg_err calls

- test/runtime/signal.c
Use syscall(SYS_getpid) rather than getpid() in tests that use
pthreads. This is needed for older glibcs (see #970)
> getpid() --> syscall(SYS_getpid)

- src/net/netsyscall.c
- src/runtime/merge.c
- src/tfs/tfs.c
- src/tfs/tlog.c
- src/unix/blockq.c
- src/unix/eventfd.c
- src/unix/exec.c
- src/unix/futex.c
- src/unix/mmap.c
- src/unix/notify.c
- src/unix/notify.h
- src/unix/pipe.c
- src/unix/poll.c
- src/unix/signal.c
- src/unix/socketpair.c
- src/unix/syscall.c
- src/unix/thread.c
- src/unix/unix_clock.c
- src/virtio/virtio_net.c
- src/virtio/virtio_scsi.c
- src/virtio/virtio_storage.c
- src/virtio/virtqueue.c
- src/x86_64/service.c
- src/x86_64/symtab.c
- src/xen/xennet.c
- stage3/stage3.c
- test/unit/Makefile
- test/unit/range_test.c
Self-explanatory follow up to #981. Tuple parser updates will be addressed separately.
> closure deallocation roundup

- src/net/netsyscall.c
Remove unnecessary (and broken) lwIP TCP error handler which was causing crashes after a TCP connection close (during node 'hi.js' test on macOS).
> remove duplicate lwIP TCP connection error handler

- boot/stage2.c
Change out empty stub for an uncalibrated delay function. This is intended to address reports of a spurious ata_probe timeout in stage2. Since I can't reproduce the issue, it's kind of a shot-in-the-dark, but leaving kern_sleep as an empty stub is pretty risky IMO.
> kern_sleep for stage2

- Makefile
- src/unix/mmap.c
- src/unix/syscall.c
- src/unix/system_structs.h
- test/runtime/Makefile
- test/runtime/fcntl.c
- test/runtime/fcntl.manifest
Per the conversation in https://github.com/nanovms/nanos/issues/829#issuecomment-557301456, this PR implements the support for the `F_GETLK`, `F_SETLK`, `F_SETLKW` _fcntl_ operations.
> fcntl: add F_GETLK, F_SETLK, F_SETLKW

- Makefile
- src/unix/poll.c
- test/runtime/Makefile
- test/runtime/epoll.c
- test/runtime/epoll.manifest
Demonstrates and resolves #1033
> epoll_ctl: allow NULL event pointer for EPOLL_CTL_DEL

- src/unix/syscall.c
sendfile(2) was not handling -EAGAIN or 0 return values from writes, causing errors e.g. upon filling a tcp output window.
> sendfile(2): fix handling of output buffer full condition

- boot/stage2.c
- src/drivers/ata.c
- src/x86_64/service.c
- VMware IDE does not support LBA48
- Detect missing IDE primary master properly
> ATA LBA28 support

- src/net/netsyscall.c
> Network socket fixes

- src/runtime/buffer.h
- src/unix/mmap.c
- src/unix/special.c
- src/unix/unix_internal.h
This file contains the currently mapped memory regions and their access permissions.
#1075
> Special files: add /proc/self/maps

- src/runtime/table.c
- src/runtime/table.h
- src/runtime/tuple.c
- src/runtime/tuple.h
- src/tfs/tfs.c
- test/unit/table_test.c
This PR fixes the updating of tuples in the filesystem log, which was breaking filesystem persistence.
> Filesystem persistence fix

- src/unix/futex.c
- src/unix/system_structs.h
Besides fixing wait timeout handling, this PR adds support for absolute futex timeout values.
> Fixes for futex wait timeout handling

- mkfs/mkfs.c
The 's' command line option can be used to specify a file size for the disk image being created. The size can be expressed in bytes, KB (with k or K suffix), MB (with m or M suffix), and GB (with g or G suffix); if not multiple of the disk block size, it is increased to the next block size multiple. If the specified size is less than the minimum size required to create the file system, this command line option is ignored.
This change allows creating disk images with an arbitrarily large free disk space.
Closes #1136.
> mkfs: add commmand line option to set minimum file size

- src/unix/timer.c
Since we only have one process, monotonic system time should suffice to implement ITIMER_PROF.
Resolves #789 (setitimer failure in php internal webserver)
> setitimer: enable use of ITIMER_PROF

- src/unix/syscall.c
We currently don't have a memory swap area.
Closes #1142.
> Syscalls: stub mlock/munlock

- src/xen/xennet.c
The ID assigned to a xennet_tx_buf is used, after left-shifting by 8 and ORing with a page ID, to create a Xen TX request ID. Since Xen network TX request IDs are 16-bit values, any xennet_tx_buf ID large than 255 overflows the 16-bit request ID, and as a result when the corresponding response is consumed from the TX ring the front driver associates the response to the wrong xennet_tx_buf.
This commit changes the bit shift value from 8 to 5 (since the maximum pbuf length is 64 KB, the maximum number of pages that may be needed for a single pbuf is 17) in order to allow up to 2048
xennet_tx_buf structures to be used, and adds checks to ensure that the limit on the number of allocated xennet_tx_buf structures is not exceeded.
Closes #1157.
> xen network: fix handling of 16-bit IDs in TX requests

- src/unix/syscall.c
- src/unix/system_structs.h
- src/unix/thread.c
- src/unix/unix.c
- src/unix/unix.h
- src/unix/unix_internal.h
- src/x86_64/schedule.c
- src/x86_64/x86_64.h
> Syscalls: getrusage

- src/unix/blockq.c
If a blockq item has an associated timeout but is completed before the timeout expires, the timeout closure is never invoked, and as a result closure_finish() is never called; this causes a memory leak.
Fix this issue by embedding the timeout closure in the blockq_item struct, so that it is allocated and deallocated together with the struct.
Closes #1170.
> blockq timeout: fix memory leak when timeout does not expire

- mkfs/dump.c
The mkfs/dump tool now accepts the '-t' command line option, which makes the tool display the filesystem from a given image as a tree. In the displayed tree, directory entries are blue, symbolic links are cyan (with indication of the link target path), and regular files are white.
The existing functionality to dump filesystem contents into a given directory can now be invoked via the '-d <target dir>' command line option.
Closes #564.
> Filesystem dump: add option to display filesystem as a tree

- src/net/netsyscall.c
When sendto() is called with non-NULL destination address on a UDP socket, calling the udp_connect() lwIP function to set the remote endpoint is wrong, because it puts the socket in a "connected" state where it is unable to receive packets from any remote address other than the address used when calling udp_connect().
This commit fixes the above issue by removing the call to udp_connect(), and calling udp_sendto() (instead of udp_send()) when the destination address is non-NULL.
> UDP socket send(): fix handling of packet destination address

- README.md
> update README.md: TARGET is make var

- src/hyperv/storvsc/storvsc.c
- src/virtio/scsi.h
> StorVSC A0/A1 fix

- platform/pc/service.c
- src/unix/socket.h
> Fixes for compilation errors with gcc 10

- platform/pc/Makefile
- src/hyperv/include/atomic.h
- src/hyperv/include/hyperv.h
- src/hyperv/include/hyperv_internal.h
- src/hyperv/vmbus/hyperv.c
- src/hyperv/vmbus/hyperv_var.h
- src/hyperv/vmbus/vmbus.c
- src/hyperv/vmbus/vmbus_et.c
- src/hyperv/vmbus/vmbus_var.h
- src/runtime/clock.h
- Reference TSC page support
- VMBUS ET timer
> Hyper-V: pv timer

- src/hyperv/storvsc/storvsc.c
Fixes Hyper-V boot on recent master
> Hyper-V storvsc: 256KB maxio support

- platform/pc/Makefile
- platform/pc/service.c
> Fix booting on Xeon 5520

- platform/pc/Makefile
- platform/pc/service.c
- src/hyperv/include/hyperv_internal.h
- src/hyperv/include/vmbus.h
- src/hyperv/utilities/vmbus_ic.c
- src/hyperv/utilities/vmbus_icreg.h
- src/hyperv/utilities/vmbus_icvar.h
- src/hyperv/utilities/vmbus_shutdown.c
- src/hyperv/vmbus/hyperv.c
- src/hyperv/vmbus/vmbus_chan.c
- src/runtime/runtime.h
- src/x86_64/hyperv_platform.h
This implements proper VM shutdown when running in Hyper-V or Azure
> Hyper-V support: shutdown driver

- src/unix/exec.c
- test/runtime/ftrace.c
Just some small changes to get ftrace working again (as well as ftrace test working).
> Fix ftrace

- src/net/direct.c
Fix regression in net direct output by using a tcp_sent callback to send spooled data.
supersedes #1286
> net direct: implement tcp_sent callback

- src/unix/thread.c
The only function call that needed the kernel lock was thread_log_internal(), which is now being changed to allocate its buffer from the stack instead of a global heap; as a side effect, this fixes a memory leak in thread_log_internal(), because the buffer was never deallocated and the "transient" heap is not actually transient.
> Unix run_thread_frame(): avoid taking kernel lock

- test/runtime/mmap.c
added documentation to mmap tests and organized isolated tests into separate functions for improved readability
issue #936
> refactor mmap test code

- src/kernel/elf.c
The initial_len calculation was not zeroing out the remainder of the page
after the bss size. The ld-linux loader uses that space and expects it to be 
zero. The fix and elf debug code pulled from @wjhun's arm branch.
> Zero out rest of page after bss during elf load

- .circleci/config.yml
- Makefile
> Add dump tool to nightly builds and releases

- platform/pc/Makefile
> add src/aws to CLEANDIRS

- klib/ntp.c
Clang compiler emits warnings such as "taking address of packed member 'transmit_ts' of class or structure 'ntp_packet' may result in an unaligned pointer value". But in fact all the ntp_ts structs packed in the ntp_packet struct are 4-byte aligned, since they are at offsets from the beginning of the structure that are multiple of 4 bytes, thus their u32 members are always at aligned addresses.
This change casts the struct ntp_ts pointers to void* to silence the warnings.
> NTP: silence unaligned packed member address compiler warnings

- klib/radar.c
The first message to the radar server containing resource utilization data is now sent without waiting 5 minutes (since memory usage figures for the past 5 minutes are not available right after boot, each of the elements of the `memUsed` JSON array in the first message contains the current memory usage).
> Klibs: radar: send first stats message right after boot

- src/net/net.c
Implements https://github.com/nanovms/ops/commit/587cbf9ce2ded490d8c1319eb2f91713b9b5e146 in nanos, so VM instances (created
by `ops instance create`) can also use the same defaults as `ops run`.
See https://github.com/nanovms/ops/issues/944#issuecomment-796829571.
> Set default GW and NetMask when IP is present

- src/unix/poll.c
When a file descriptor is added to an epoll file, the corresponding epollfd structure must be initialized with the user-supplied event mask and data.
The existing code was failing to do the above in cases where the file descriptor being added was already present in the fd vector of the epoll file. This change fixes the issue by defining a new function called reset_epollfd() that properly resets an already-allocated epollfd structure with new values for the event mask and data; this function is now used for both epoll_ctl(EPOLL_CTL_ADD) and poll().
> EPOLL_CTL_ADD: fix setting of event mask and data

- src/net/netsyscall.c
- test/runtime/netsock.c
With this change, the connect syscall now supports non-blocking mode (SOCK_NONBLOCK/ O_NONBLOCK). The netsock runtime test verifies that an attempt to connect over the loopback device gives an EINPROGRESS result. It also checks that EPOLLOUT is subsequently reported on behalf of the socket fd once the connection is established.
> connect(2): honor non-blocking flag

- src/runtime/buffer.h
I've run into a couple situations where I got kernel page faults with strange addresses that were caused by moving
and accessing a buffer start pointer beyond the end or the length. This change adds assertions to enforce a
start<=end<=length invariant to avoid harder to debug crashes from out of bounds memory access. It also uses
a different macro name for assert so that klibs can skip the asserts which would require them to import at least
two additional symbols.
> Add length assertions to basic buffer operations

- src/tfs/tlog.c
A log extension keeps a pointer to the log structure, and needs to safely access this pointer. Thus, it should prevent the log from being deallocated as long as the extension is open, and not only during a flush to disk.
This change fixes a page fault that occurs during log compaction if the log being retired is deallocated (by the log_switch_complete() function) while its current extension is still being flushed to disk. This fault was caused by log_ext_free() accessing the heap member of an already deallocated log struct.
Since open_log_extension() now bumps the log refcount, the call to this function in log_new() is being moved to after the initialization of the log refcount.
> TFS log: prevent log deallocation while a log extension is open

- src/x86_64/apic.c
Using the "all but self" (TARGET_EXCLUSIVE_BROADCAST) address in an IPI on x86
leads to a significant performance penalty. The broadcast may target disabled
cpus or delay waiting for a response that doesn't come. This patch changes
the broadcast to an iterative approach that unicasts to discovered cpus.
Prior to this patch, the fs_full test took twice as long with a single cpu but SMP_ENABLED
as with a single cpu without it enabled. After the patch, the runtime is identical.
> Use iterative unicast of discovered cpus for IPI broadcasts

- src/tfs/tfs.c
This PR resolves a crash that occurred while trying to reproduce https://github.com/nanovms/nanos/issues/1473 on a Raspberry Pi 4. If extents_range_handler was called during the allocation stage of a tfs write and a subsequent call to update_extent_length returned a failure, an apply_merge would be called with a null pointer. This changes the extend call to mirror fill_gap, returning a failure status instead of trying to apply it directly to a merge. Also, since the presence of a merge indicates extent writing is in process, eliminate the redundant write flag parameter in extent_range_handler, fill_gap and extend.
> extents_range_handler: properly handle extend failure when allocating

- src/unix/syscall.c
https://github.com/nanovms/nanos/issues/1502
> change pugnix -> Nanos for os name for run-time ident

- src/unix/syscall.c
The previous implementation of brk(2) was not unmapping and deallocating pages on reduction of heap size. The effects of this omission were masked due to the x86_64 page table code allowing entries to be overwritten. This would result in leaked pages if the process heap was lowered and then later raised again. This change unmaps and deallocates pages that become unassociated with the process heap after a call to brk(2).
This also remedies an existing bug which was forcing the reported process break to be page-aligned. The process should be able to set the break to an unaligned address, and the returned break value should equate to the value set.
> brk(2): unmap and deallocate pages when heap size is reduced, do not force alignment on brk value reported to userspace

- src/net/netsyscall.c
The current code makes the accept() syscall return -ECONNRESET if the TCP socket just created has been disconnected already. This error code is not among the errors returned by other operating systems for this syscall (even Linux, which may return network errors on the new socket as error codes from accept(), never returns -ECONNRESET), and is likely to be considered as a fatal error by user programs (notably, it causes Golang web server functions such as http.ListenAndServe() and
http.ListenAndServeTLS() to exit with error).
This PR changes accept_bh() so that it returns the file descriptor of the newly created socket even if the socket is disconnected (in this case, the peer address cannot be retrieved and will be set to a dummy value). As a side effect, the newly created socket is no …
> accept(): return socket file descriptor even if connection is reset

- platform/pc/boot/stage2.c
- platform/pc/service.c
- platform/virt/service.c
- src/aarch64/kernel_machine.c
- src/config.h
- src/kernel/init.c
- src/kernel/kernel.h
- src/net/net.c
- src/x86_64/kernel_machine.c
The PR improves efficiency in utilization of physical memory, which makes the kernel able to run in machines with low amounts of available memory, while not affecting performance in high-memory machines.
> Decrease memory utilization

- src/unix/ftrace.c
This fixes a regression introduced with the timer changes.
> update ftrace to use latest timer interface

- src/net/netsyscall.c
- test/runtime/netsock.c
In Linux, a TCP socket that has never been connected reports (POLLHUP | POLLOUT) events when polled, and a TCP socket whose connection with the remote peer has been closed reports (POLLIN | POLLOUT).
This commit modifies the events reported in socket_events() to match the Linux implementation. This fixes an issue that makes the redis server (version 5.0.5) use 100% CPU when subject to a workload from YCSB; more specifically, the redis server relies on TCP sockets whose connection with the remote peer has been closed to report the EPOLLIN event.
> Network socket: modify poll events to match Linux implementation

- src/drivers/vga.c
The vga buffer physical was being mapped to the identity virtual address
which is in the user virtual address area. This change allocates a new
virtual address from kernel virtual addresses to map to the vga buffer.
> Allocate vga buffer address from kernel va space

- test/go/common.go
https://github.com/nanovms/ops/pull/1246
> update go test to use NameServers field in config

- src/unix/pipe.c
A deadlock may occur in the following scenario: pipe_read_bh or pipe_write_bh
invoke notify_dispatch, with the pipe lock held, to indicate a cleared
condition (EPOLLIN or EPOLLOUT, respectively). A coincident epoll_wait takes
the efd lock and then invokes pipe_read_events, which tries to acquire the
pipe lock. The notify_dispatch invokes wait_notify, which in turn is blocked
waiting for the efd lock. This patch eliminates the deadlock by moving these
notify_dispatch invocations to follow release of the pipe lock.
This deadlock would materialize when testing webg on qemu with large number (n
= 16) of cpus and 'ab -n 1000000 -c 100', which would hang after a few passes.
> fix deadlock scenario in pipe reads and writes

- test/runtime/fs_full.c
The fs_full test tries to fill up the disk in several different circumstances,
but sometimes a small amount of additional space may become available
after the first write error indicating the disk is full. This has an effect on
write checks which may then not report the correct amount that could
be written and failing the test. The write function has been modified to
retry failed writes twice after a brief delay to ensure all sectors that can
be written to the disk have been written.
> fs_full test: retry errored writes to ensure disk is full

- src/net/netsyscall.c
- test/runtime/netsock.c
If the socket on which getsockopt/setsockopt is called is in listening state, it is not possible to get or set TCP options on the lwIP PCB structure, because the structure associated to a listening socket is a struct tcp_pcb_listen, not a struct tcp_pcb. A struct tcp_pcb_listen does not have a TCP flags field, thus trying to access this field leads to a potential corruption of other fields in struct tcp_pcb_listen.
This commit fixes the above issue by adding a tcpflags_t field to the netsock structure and accessing this field in getsockopt/setsockopt if there is no struct tcp_pcb to be accessed. To match the Linux implementation, any socket created from a listening socket inherits its TCP options.
> getsockopt/setsockopt: fix handling of TCP_NODELAY socket option

- src/kernel/pagecache.c
- src/virtio/virtqueue.c
This PR fixes a few memory leaks found in the page cache and virtqueue code.
> Fix memory leaks

- src/unix/netlink.c
- test/runtime/netlink.c
This work allows IP routing table information to be extracted from the kernel
using RTM_GETROUTE netlink messages. As with the remainder of netlink code,
only IPv4 is supported at the moment. This support is sufficient for
retrieving the gateway address for each interface. The netlink runtime test
has been expanded to test this functionality as well as optionally dump
details from rtmsg responses received from the kernel.
Based on PR #1700
> add netlink support for RTM_GETROUTE requests 

- src/hyperv/storvsc/storvsc.c
This change adds support in Azure for attaching and detaching volumes
at runtime. This also fixes a bug where only one volume could be mounted
in an Azure instance as well as a bug where uninitialized command memory
could cause erroneous request failures.
> Azure: Add hot-plug storage devices

- src/unix/exec.c
build_exec_stack() was passing the user stack pointer in the AT_RANDOM field
without actually placing random data at that location. This allocates 16 bytes
at the top of the stack, fills it with random data, and passes that to the
user program via the AT_RANDOM field. This random data is needed by glibc to
produce entropy when initializing the pointer and stack guards.
> build_exec_stack: point AT_RANDOM at random values

- src/virtio/virtio_storage.c
The set of features negotiated between a virtio driver and a device is the logical AND of the features supported by the driver and
those supported by the device. The driver was failing to set VIRTIO_BLK_F_SEG_MAX among its supported features, which was preventing the driver from detecting that this feature is supported by the virtio block device implementation in Qemu. Setting this feature bit allows the driver to retrieve from the device the maximum number of segments (which is 254 in Qemu v5.2.0) allowed in a virtio request.
The previously held assumption that a device that does not support this feature can handle up to (virtqueue_size - 2) segments is wrong and was causing a failure to boot on AWS Firecracker (which does not support this feature). This change fixes the issue by setting …
> virtio block driver: fix handling of VIRTIO_BLK_F_SEG_MAX feature

- klib/cloud_azure.c
When the Azure cloud init issues a GET request for the goal state in order to
report status, the XML reponse from the wireserver may be large enough to
require multiple packets. This change fixes a bug where the response
was assumed to fit in a single packet, so the request parser was never
called unless the response was small enough. The http parser is moved
to the receive handler from the packet handler so that parser state is
preserved between packets. The response parser now closes the connection
when any complete http response is received.
> Azure: Handle multi-packet goalstate response from wireserver

- SECURITY.md
This change lists the main RNG features supported in the kernel.
> Security: add random number generation features to documentation

- src/x86_64/unix_machine.c
Even though the segment selectors in the CS and SS fields of a ucontext are not copied to a thread frame when restoring the context interrupted by a signal handler, the bit that selects between the sysret and iret paths should be copied, otherwise the wrong frame_return path could be taken, resulting in corruption of CPU registers when the user thread is resumed.
> x86 restore_ucontext(): properly restore bit to select return path

- test/runtime/fs_full.c
This test was failing frequently with false test failures. The tfs log flush
may be delayed a second after the last write that fills the disk, and that
flush may free disk space if an old log gets removed. Write_blocks has
been refactored so that it will retry after at least twice the tfs log flush 
delay to ensure enough time for the log flush and completions to run
so that any eligible log space will be freed before giving up on the write.
The write test when the filesystem is full now allows writing up to bfree 
blocks instead of assuming that any write will fail. The file remove and 
free space check now syncs and waits after the remove is called to
allow time for the free space to be updated before calling stat.
> Improve robustness of fs_full test

- klib/ntp.c
With this change, it is possible to configure the NTP klib with multiple NTP servers, by inserting an `ntp_servers` array in the root tuple of the manifest, where each array element follows the syntax `<addr>[:<port]`; `<addr>` can be an IP address or a fully qualified domain name; if the optional `<port>` is not present, the default NTP port 123 is used.
Example configuration with 2 servers: `ntp_servers:[us.pool.ntp.org 12.34.56.78:1234]`
When multiple servers are configured, the NTP klib starts by using the first server, and switches to the next server (in a round robin fashion) if no valid response is received from the current server.
> NTP: add ability to configure multiple servers

- klib/ntp.c
The first commit allows the NTP klib to work on VMs with IPv6 internet connectivity.
The second commit changes the behavior of the klib so that if multiple NTP servers are configured, all servers are probed in parallel: this prevents non-reachable or invalid servers from delaying synchronization of the VM system time if there is at least one valid and reachable server.
> Klibs: ntp: add IPv6 support and improve handling of multiple NTP servers

- src/kernel/pagecache.c
pagecache_commit_dirty_node() copies any dirty ranges in a node to a buffer and removes them from the `dirty` rangemap; then, it triggers the actual committing of the dirty ranges. If pagecache_commit_dirty_node() is called when the rangemap is empty, the completion closure is invoked immediately even if the committing is ongoing, which is incorrect and can cause issues such as a premature deallocation of fsfiles that have not been synchronized to disk.
In addition, the buffer is not properly deallocated when the rangemap is empty.
This change fixes the above issues.
> pagecache: fix committing of nodes with empty `dirty` rangemap

- src/tfs/tlog.c
Using the kernel page cache as an intermediary between the TFS log code and the storage device has a number of disadvantages:
- log extensions read during system startup are copied twice in memory (first in the page cache and then in the TFS log buffers), and one of the two copies (the one in the page cache) is never used afterwards
- log extensions written (by the log_flush function) after a filesystem modification are not immediately flushed to disk, which is inconsistent with the semantics of the fsync() syscall
- each write of a log extension chunk that begins at a page boundary and does not span an entire page triggers an unnecessary read from disk in the page cache code
- when the TFS log is rebuilt, the storage space occupied by the extensions of the log being retired is freed …
> TFS log: do not use the page cache

- src/hyperv/storvsc/storvsc.c
A storvsc disk has a limit on how many segments (i.e. pages) can be transferred in a given I/O request. This PR changes storvsc_io() so that requests coming from the upper layers exceeding that limit are split into multiple I/O requests. This fixes booting on Azure instances.
> Hyper-V: storvsc_io(): honor maximum segment count for I/O requests

- src/unix/special.c
A given image may be created with a /proc/self directory. The existing code is skipping creation of the /proc/self/exe symlink when the /proc/self directory exists; this PR changes the code so that the symlink is always created when not present, regardless of the presence of the containing folder.
> Unix: create /proc/self/exe even when /proc/self directory exists

- src/unix/poll.c
When poll(2) is called on a given thread, the type of the epoll structure associated to the thread is set to EPOLL_TYPE_POLL; this does not always happen when select(2) is called; when a program calls select() after poll(), the epoll type remains set to EPOLL_TYPE_POLL, which may cause the check_fdesc() function to call poll_notify() instead of select_notify() on the epoll_blocked structure, thereby accessing invalid fields in the internal union of this structure.
This change fixes the above issue by adding an epoll type parameter to the select_get_epoll() function (which is being renamed to thread_get_epoll because it is not used just for select), and properly setting the epoll type in this function according to the argument value.
> select(2): properly set the epoll type for the current thread

- src/unix/signal.c
- test/runtime/signal.c
If dequeue_signal is working on the process signal queue, then multiple threads may be trying to access that queue simultaneously in an smp machine. The pending check was happening outside the queue lock which could result in a thread trying to dequeue an already processed signal from a now empty queue, resulting in an assertion failure.
This changes the assert in sigstate_dequeue_signal() to be a check that returns INVALID_ADDRESS if the queue is empty. A new smp signal test for this condition has been added to the signal runtime tests.
> Handle empty queue when dequeuing signal

- src/kernel/kvm_platform.c
When running under QEMU with KVM acceleration, the hypervisor signature reported at CPUID function 0x40000000 may not be the KVM signature; specifically, if Hyper-V Enlightenments are enabled in the QEMU command line (for example, with the command line option `--cpu host,hv_relaxed`), the hypervisor reported at CPUID function 0x40000000 is Hyper-V, whereas KVM is reported at CPUID function 0x40000100 (see https://github.com/qemu/qemu/blob/d73c46e4a84e47ffc61b8bf7c378b1383e7316b5/docs/hyperv.txt).
This change fixes the hypervisor detection logic so that KVM is properly detected when Hyper-V Enlightenments are enabled. In addition, the check on the eax value (which indicates the maximum cpuid function present in a given leaf) is being fixed so that the detection works properly on VMs (such …
> KVM: fix detection logic when Hyper-V Enlightenments are enabled

- src/unix/poll.c
- src/virtio/virtio_net.c
This change set amends the Unix epoll code and the virtio-net driver in order to improve network performance (especially on GCP instances with a high vCPU count).
Analyzing lock stats while stress-testing a Go web server running on a multi-core instance revealed a high contention of the lock that protects the file descriptor list associated to an epoll instance. Since this list is only modified when adding or removing a file descriptor to/from an epoll instance (and not when invoking the epoll_wait syscall, which happens more frequently), replacing the lock with a read-write lock decreases the lock contention and improves the performance of the web server when servicing multiple connections simultaneously.
The same analysis of lock stats also revealed a high contention of the lock that …
> Network performance improvements for VMs with high vCPU count

- src/net/netsyscall.c
The shutdown syscall can be invoked on a given socket multiple times; if it is invoked once with `how` set to SHUT_RD and once with `how` set to SHUT_RW, at the second call both directions of the underlying TCP connection are shut down, which means that the lwIP tcp_pcb structure can be deallocated at any time and is therefore unsafe to reference. The existing code is failing to detect this condition, which may cause lwIP functions to be called on a tcp_pcb structure that has already been deallocated.
This change fixes the above issue. In addition, the initial check on the state member of the socket structure is now performed with the lwIP lock held, for multi-thread safety.
> netsock_shutdown(): fix handling of multiple calls on a socket

- src/kernel/pagecache.c
- test/runtime/mmap.c
Writing to a file-backed memory area must not cause the length of the underlying file to change, even if the write happens to a location beyond the current file length (e.g. when the file length is not a multiple of the page size). The kernel page cache code that implements writeback of dirty pages written by userspace via mmapped memory is invoking the fs_write closure with a range argument corresponding to a full page size (or a multiple of the page size), which may cause the filesystem code to change the file length.
This change fixes the above issue, and adds to the mmap runtime tests a test case that would fail without this fix.
> pagecache_commit_dirty_ranges(): do not write past node length

- src/unix/netlink.c
If a recvfrom() or recvmsg() call on a netlink socket results in an error (e.g. when no messages have been received and the socket is non-blocking), the source address and corresponding length value passed to the syscall should not be touched.
This change moves the code that sets the source address (and other fields in struct msghdr) to the nl_read_bh closure, so this code is only executed when messages have been received on the socket.
Closes #1824.
> netlink recvfrom/recvmsg: don't set source address in error cases

- src/unix/socket.c
The existing code in unixsock_close() could create a condition whereby a
reference for a deleted child socket would remain in the process file
descriptor vector. This could materialize as a use-after-free and crash upon
process exit.
The remedy presented here allows the child socket to be created upon
connection, but defers the allocation of an fd until the child is accepted
from the listening socket. When a listening socket is closed, its child
sockets are closed via the usual method rather than deleted outright.
> unixsock_close: close rather than deallocate sockets in conn_q

- klib/syslog.c
Since the network stack needs to do an initial ARP query in order to retrieve the MAC address to be used for packets with a given destination, if many such packets are sent to the same destination before a response to the ARP query is received, the ARP driver queues only a limited number (currently 3) of them. As a result, if the user application prints many messages in short succession during startup and expects these messages to be delivered to a syslog server, from the initial burst of messages, only the 3 most recent ones are delivered. To work around this issue, the first commit changes the syslog klib so that the number of UDP packets sent in the first batch does not exceed the size of the ARP queue.
The second commit amends the syslog klib so that any buffered messages are flushed …
> syslog: ensure initial and final messages are delivered

- klib/gcp.c
This change set enhances the gcp klib so that it can now be configured for sending memory usage metrics to the GCP monitoring service, thus emulating the GCP ops agent.
The ID of the running instance and the zone where it is running (which are necessary to be able to send API requests to the
monitoring server) are retrieved from the instance metadata server.
The metrics being sent are related to memory usage (see https://cloud.google.com/monitoring/api/metrics_opsagent#agent-memory), and more specifically are the `bytes_used` and `bytes_percent` metric types; for each type, a value is sent for each of the "cached", "free" and "used" states.
Sending of memory metrics is enabled by inserting a "metrics" tuple in the "gcp" configuration tuple; it is possible to modify the time interval at …
> Klibs: gcp: add support for sending metrics to monitoring service

- src/runtime/tuple.c
- test/unit/tuple_test.c
This change modifies the tuple encoding functions to only encode a tuple's content once per call, thus avoiding infinite recursion in cases where there exists a cycle in a tuple structure (for instance, if a ".." directory entry is mistakenly encoded and the current directory metadata is revisited as a child of the parent directory). It achieves this by passing a table of visited tuples through the call stack, recording each encoded tuple (immediate or reference) in the table. Future attempts to encode any tuple found in the table (within the span of the encode_tuple(), encode_eav() or encode_value() call) will result in a reference to the tuple being encoded with a zero attribute count. The tuple_test unit test has been updated accordingly to reflect this behavior, and a check has been …
> prevent infinite recursion when encoding tuples

- klib/ntp.c
Instead of printing a "failed to receive server response" message every time the response to an NTP query packet is not received (which is not uncommon, especially if the NTP server is geographically distant from the instance, given that NTP uses UDP as transport protocol), with this change the NTP klib prints a message only if no response is received in a given interval (which is initialized based on the configured NTP query interval, and is incremented after printing a message in order to avoid spamming the console).
> Klibs: ntp: add backoff time for missing response error messages

- src/net/direct.c
This change set fixes memory leaks found in the net/direct.c code:
- tcp_pcb reference counting for TCP client connections is being fixed, so that the tcp_pcb structure is properly deallocated when a TCP connection is shut down
- the send and receive queues of the direct_conn structure are now properly cleaned up and deallocated.
Closes #1912
> net/direct.c: fix memory leaks

- src/net/netsyscall.c
PR #1761 increased the TCP send buffer size and TCP window size from 0xffff to 0x34000 bytes, which improved performance of large network transfers. However, the tcp_sndbuf() macro caps the returned value to 0xffff, and the maximum data length that can be passed to the tcp_write() function is still limited to 0xffff bytes; this means that the kernel can call tcp_write() multiple times with a data length set to the value returned by tcp_sndbuf(), while still remaining within the limit of the send buffer size. This change modifies the socket_write_tcp_bh() function so that the send buffer size is retrieved after each call to tcp_write(), in order to be able to use the entire send buffer when large write requests are made by the user program.
Beside improving the performance of socket write …
> socket_write_tcp_bh(): fix check of TCP send buffer length

- src/net/netsyscall.c
In the existing TCP network socket code there is a race condition that can be triggered when running on a multi-CPU machine, as shown by the following scenario:
- a thread on CPU0 calls close() on a connected TCP socket, the code in socket_close() retrieves the tcp_pcb struct and tries to lock it via netsock_tcp_get()
- the remote end of the TCP link closes the connection, which causes the lwip_tcp_conn_err callback function to be run on CPU1, which decrements the tcp_pcb reference count via tcp_unref()
- the code running on CPU0 acquires the tcp_pcb lock, calls tcp_close() (which is wrong because this function must not be called on a tcp_pcb that has been disconnected), then calls tcp_unref() (which is wrong because it duplicates the tcp_unref() call made by the callback function)
A …
> Network socket close/shutdown: fix race with lwIP error callback

- klib/gcp.c
**todo**:
- _default_ **disabled** - `"disk": {}` to enable.
- _default_ **readonly mount(s) are not reported** - `"include_readonly": "t"` to enable.
```json
"ManifestPassthrough": {
"gcp": {
"metrics": {
"interval": "60",
"disk": {
"include_readonly": "true"
}
}
}
}
```
> feat(gcp): disk metrics

- src/unix/mmap.c
In the current code, the vmap_update_protections_intersection() function is overwriting the entire contents of a vmap entry while this entry is inserted in the process memory map; this can corrupt the entry fields specific to the rangemap implementation (i.e. the red-black tree), which can cause a crash when the map is accessed later.
This change fixes the above issue by adding a vmap_set_offsets() static function that overwrites only the vmap-specific fields that need to be overwritten, and calling this function to overwrite the contents of a vmap entry inserted in the virtual memory map. altered_vmap_key() has been refactored to use this function. This fixes a kernel hang observed when the mprotect() syscall is invoked on a kernel built with the Clang compiler.
> Unix mprotect(): fix update of process virtual memory map

- src/kernel/init.c
based on comments from https://github.com/nanovms/nanos/pull/1974
- reboot on **non zero exit code** - use `"t"` or `"!0"`
```json
{
"ManifestPassthrough": {
"reboot_on_exit": "t"
}
}
```
or
```json
{
"ManifestPassthrough": {
"reboot_on_exit": "!0"
}
}
```
- reboot on **any exit code** - use `"*"`
```json
{
"ManifestPassthrough": {
"reboot_on_exit": "*"
}
}
```
- reboot on a **single exit code** - use `"replace_me_with_exit_code"`
```json
{
"ManifestPassthrough": {
"reboot_on_exit": "0"
}
}
```
- reboot on a **list of exit codes**
```json
{
"ManifestPassthrough": {
"reboot_on_exit": ["0","1","6"]
}
}
```
---
**Note**: `ops` behavior remains unchanged for `"RebootOnExit": true` or   `"Debugflags": ["reboot_on_exit"]`
---
**Question**: Do we want to add other negating possibilities other …
> feat(reboot_on_exit): additional triggering patterns

- src/net/direct.c
- src/net/netsyscall.c
- src/virtio/virtio_net.c
This patchset enhances the virtio-net driver to support TCP segmentation and UDP fragmentation offload, which allows the virtIO device to merge multiple received packets into one large packet; in addition, the driver now supports the MRG_RXBUF feature, so that it is not necessary for the driver to allocate large RX buffers in order to receive large packets.
These changes bring a performance improvement to applications receiving large amounts of data over a network link, e.g. when a VM uses virtual network interfaces backed by tap interfaces on the host.
The first commit is a fix to the network socket code that was causing a performance penalty in data transfers on TCP connections with the window scaling option enabled.
> virtio-net: add support for segmentation offload

- klib/pledge.c
- src/net/net_system_structs.h
- src/net/netsyscall.c
- src/unix/netlink.c
- src/unix/socket.c
- src/unix/vsock.c
These getsockopt values are used by iperf3.
> getsockopt(SOL_TCP): add support for TCP_INFO and TCP_CONGESTION

- src/unix/exec.c
Configuration of the current working directory via the `cwd` attribute of the manifest was being done only for statically linked program executables. This change enables the `cwd` attribute to take effect also for non-static executables.
In addition, a missing deallocation of the executable file buffer for non-static executables is being fixed.
Closes https://github.com/nanovms/ops/issues/1632
> exec_elf_finish(): add setting of cwd for non-static executables

- src/kernel/pci.c
There are platforms (such as the platform used by ARM-based t2a instances in Google Cloud) where the PCI device at 00:00:0 is not a host-to-pci bridge but PCI bus 0 is still present and should be enumerated. This change ensures that PCI bus 0 is always enumerated.
Enumeration of a PCI bus is being optimized by avoiding probing device functions 1 to 7 in a given device slot when device function 0 does not exist in that slot.
> pci_discover(): fix missing probe of bus 0

- src/fs/9p.c
A given file can be deleted and renamed while still open, and all I/O operations should still be possible after file deletion or renaming.
This change fixes the 9P filesystem driver so that it meets the above requirements:
- the SETATTR command to set the file size before writing to a file has been removed, because it doesn't work (the server returns an error) if the file has been deleted or renamed
- deletion of the dentry structure associated to a file has been removed from the functions that delete or rename the file, so that an open file can still be used after deletion or renaming
- on file closure, a check on the existence of the file metadata tuple has been added, so that access to non-existing metadata is avoided
Fixes #2047.
> 9P filesystem: fix operation with deleted and renamed files

- src/aarch64/interrupt.c
When an exception (such as a page fault) occurs in user mode (EL0), the exception handler uses the EL1 stack pointer; if the handler returns directly to EL0, any stack space consumed by the handler should be unconsumed before switching back to EL0, otherwise the handler of the next exception taken from EL0 may use the modified stack pointer (and consume more stack space), which could lead to a stack overflow if a large number of such exceptions occurs before the next runloop invocation.
The CI test failure at https://app.circleci.com/pipelines/github/nanovms/nanos/4803/workflows/2a037461-68e5-4804-afb1-2b2aa95a8732/jobs/16793 might have been caused by this bug.
> ARM exception handler: restore stack pointer when returning to EL0

- klib/tun.c
When a tun file descriptor is closed, and there are no other file descriptors associated to the tun device, the `next_tx` field of the tun struct should be cleared; in addition, the network interface output function should check if the `next_tx` field points to a valid file descriptor.
This change fixes an unhandled fault that occurs when closing a file descriptor on a tun device that has open TCP connections. Closes #2061.
> tun_close(): properly update `next_tx` file descriptor reference

- klib/strace.c
- klib/strace_file.c
- src/unix/filesystem.c
- src/unix/filesystem.h
- src/unix/syscall.c
- src/unix/system_structs.h
- src/x86_64/unix_syscalls.h
- test/runtime/pipe.c
- test/runtime/symlink.c
Specific support for this syscall is also being added to the strace klib.
> Syscalls: add statx(2) implementation
